### ISSUE TITLE
Support for Identity Providers API

### ISSUE THREAD

**Issue by AlainODea** [okta/okta-sdk-java#101]
We use the [Identity Providers API](https://developer.okta.com/docs/api/resources/idps.html) in production to:

 1. Allow customers to create and update their IdPs with necessary security restrictions from our application for SSO self-enrolment.
 2. Allow customers to see logs specific to their IdP for SSO self-troubleshooting (used to get target ID for use with Events API)

**Comment by AlainODea** [comment]
@bdemers this is the IdP API we are using in production. We can't migrate to the new style of SDK until this is in it.

**Comment by AlainODea** [comment]
@bdemers when will the Identity Providers API be added to this SDK?

**Comment by bdemers** [comment]
Hey @AlainODea sorry I didn't reply to this one! or #102. 

I'll pass the buck to @nbarbettini ;)

**Comment by AlainODea** [comment]
No worries 😄

I think Identity Providers can be supported (in a basic way) with changes to api.yaml and running the Swagger codegen. If I understand it correctly, most of API client plumbing (per API endpoint) is generated by Swagger. That's awesome!

**Comment by nbarbettini** [comment]
@AlainODea The API client plumbing is indeed generated via Swagger (OpenAPI). The IdP API isn't one we have worked on adding yet, but it's in the backlog. 👍

**Comment by nbarbettini** [comment]
@AlainODea Just curious, other than this API, what other features would you like to see in this SDK? What would make it a really great Java experience?

**Comment by AlainODea** [comment]
I work on an Cloud-based multitenant app that integrates extensively with Okta.

Okta enables SAML SSO, MFA, and seamless access to a community/support site for the tenants and their users.

The major things we use are:
* Users: so we can set passwords, unlock, and reset password
* UserGroups: to move Users to groups that have an MFA enforcement policy and to lock Inbound SAML users to the correct tenant isolation config
* AppUsers: to individually assign users to federated apps like the community/support site (some customers prefer to restrict this to managers or IT on their side)
* AppUserGroups: to assign entire tenants and all their users to our Okta Sign-On Widget app and our Inbound SAML app
* Identity Providers: (this) to support SSO self-enrolment
* Factors: to support MFA self-enrolment
* Events (or equivalent): to get Identity Provider logs for self-enrolment and self-troubleshooting by our tenants
* (emerging req) Schemas: to add custom attributes to support user roles on Inbound SAML 
* (emerging req) Mappings: to map those custom attributes to custom Okta User attributes to support user roles on Inbound SAML (not strictly speaking a public API, but it supports API tokens 😁)

I can get a more complete mapping of our use of the legacy SDK when I’m at my laptop tomorrow.

**Comment by arvindkrishnakumar-okta** [comment]
Update: We have just release v2.0.0 of this SDK and this includes Identity Provider API support.
