### ISSUE TITLE
Unchecked exceptions on api calls

### ISSUE THREAD

**Issue by johnoliver** [okta/okta-sdk-java#111]
Lots of methods that result in API calls will throw a ResourceException if they fail. There is no indication from the API which methods may throw this exception.

Also ResourceException refers to http://docs.okta.com/errors/ for its error codes that does not exist.

**Comment by bdemers** [comment]
@johnoliver thanks for the report.  We will get the doc link updated, it should be: https://developer.okta.com/reference/error_codes/index

(the previous was a holdover from the original Stormpath version)

Re: the `ResourceException` every method of the client can throw a resource exception. From [Oracle's docs](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html)

> Here's the bottom line guideline: If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.

That said, we can definitely add better doc around handling of a `ResourceException`

**Comment by EarthCitizen** [comment]
For verification, the only exception I should worry about dealing with from a client instance is `ResourceException`?

**Comment by bdemers** [comment]
Correct, can you give us an example of the exception that you are seeing?  (is it a server side validation issue or something else?)

**Comment by EarthCitizen** [comment]
Just resource exception.

**Comment by bdemers** [comment]
I mean the actual exception that you where were seeing?  Was it a connection error, a 404, 400, etc?

**Comment by EarthCitizen** [comment]
Unfortunately, at the time I was looking at that, I did not examine it that closely. But, with the updated information I have from you guys confirming that only `ResourceException` is thrown from the client, and confirmation that `status` is the HTTP status code, I am going to be using that property. Is there anything specific that you need me to look for and report back to you?

**Comment by bdemers** [comment]
Nope, I was just interested in why you were hitting the exception
