### ISSUE TITLE
GetFactorType() Not Working

### ISSUE THREAD

**Issue by nathanBauer** [okta/okta-sdk-java#125]
I am iterating through a list of Factors for a user and attempting to use <factor>.getFactorType() but am always getting the following error:

![18895a8a-48bd-45f7-b983-2fe53dac88b1](https://user-images.githubusercontent.com/19820715/32510018-cafb024e-c3b4-11e7-923b-b4722fe56d45.png)

Here are more screenshots to show this Factor should not be throwing the error.

![4b613339-14ad-402b-8e1a-c38f627e644f](https://user-images.githubusercontent.com/19820715/32510043-dc14fed6-c3b4-11e7-9940-b906b19d1481.png)
![849aa97f-c68c-4d75-9254-0aea2abc599a](https://user-images.githubusercontent.com/19820715/32510057-e6acae52-c3b4-11e7-8eb9-d5e9cfd17042.png)
![095d083f-49b8-49c1-8609-7413a90b8a6b](https://user-images.githubusercontent.com/19820715/32510060-eb442d0a-c3b4-11e7-9798-fdd2f5af3b33.png)

There seems to be an error in the SDK :)
Thank you so much!

Nathan

**Comment by bdemers** [comment]
@nathanBauer Thanks for the report! We will get another release out!

**Comment by bdemers** [comment]
Resolved in 0.8.1
@nathanBauer thanks again!
