### ISSUE TITLE
ResourceException Property Status Should Have Javadoc

### ISSUE THREAD

**Issue by EarthCitizen** [okta/okta-sdk-java#128]
The `status` property of `ResourceException` does not have any documentation saying what it is. I _*assume*_ this is the HTTP status code, but I prefer not to assume anything about undocumented APIs.

Meanwhile, until this documentation is added, can I get confirmation that this is indeed the HTTP status code?

**Comment by bdemers** [comment]
+1, We will get this in for the next release!

`status` is the http status
