### ISSUE TITLE
Factor object instantiation

### ISSUE THREAD

**Issue by gregkoganvmm** [okta/okta-sdk-java#134]
Hello,

We were having some issues creating SMS factors because there doesn't seem to be a builder or direct way to instantiate the `SMSFactor` object. We found the `Client.instantiate` method and that seems to work, but this is not mentioned anywhere in documentation or examples, so just wanted to confirm that this is the correct way to do this for SMSFactor and I am guessing other objects as well.

Thank you

**Comment by bdemers** [comment]
That is the right way.  We will get some doc and examples out too!

**Comment by gregkoganvmm** [comment]
Sounds good - thank you!
