### ISSUE TITLE
Support Apple as an IdentityProviderType

### ISSUE THREAD

**Issue by tajacks** [okta/okta-sdk-java#1529]
### Describe the feature request?

When working with the IDP API endpoints, IDPs of type 'Apple' are mapped to an `IdentityProvider` with the `IdentityProviderType` of `UNKNOWN_DEFAULT_API`. 

Identity provider types should instead be exhaustive for all well known IDPs that Okta supports and should include Apple in that list.

### New or Affected Resource(s)

/api/v1/idps

### Provide a documentation link

https://developer.okta.com/docs/reference/api/idps/#list-identity-providers

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

This looks like it is missing from the OASv3 spec. I'll update the spec soon.

**Comment by arvindkrishnakumar-okta** [comment]
Spec Update: https://github.com/atko-eng/okta-oas3/pull/1175

**Comment by tajacks** [comment]
What is the release cadence for capturing these changes in the SDK under a new version? I believe the linked pull request is likely private.

**Comment by arvindkrishnakumar-okta** [comment]
It should be available in 18.0.0 SDK release.
