### ISSUE TITLE
Default dependencies cause SLF4J warnings

### ISSUE THREAD

**Issue by nicholasjackson827** [okta/okta-sdk-java#154]
When using the basic SDK config:

	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-api</artifactId>
		<version>0.10.0</version>
	</dependency>
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-impl</artifactId>
		<version>0.10.0</version>
	</dependency>
	<dependency>
		<groupId>com.okta.sdk</groupId>
		<artifactId>okta-sdk-httpclient</artifactId>
		<version>0.10.0</version>
		<scope>runtime</scope>
	</dependency>

you get a SLF4J warning:

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

A simple workaround (as suggested by the documentation) is to add the `slf4j-nop.jar` to your classpath. Once I added

	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-nop</artifactId>
		<version>1.7.25</version>
	</dependency>

to my `pom.xml`, I didn't see the warning message anymore. 

**My suggestion:** Update the logging configuration, or add the above dependency to the project so this warning does not show by default.

**Comment by bdemers** [comment]
Hey @nicholasjackson827!

This is expected, and pretty common.  The idea is that a library does not force a specific logging implementation on the user.  You could use Logback or Log4j for example if you wanted.  Take a look at: https://www.slf4j.org/manual.html#libraries
