### ISSUE TITLE
Provide a way to get a User resource from a UserGetSingleton resource now returned by UserAPI.getUser(id, expand) in 18.0.0

### ISSUE THREAD

**Issue by carlsandland** [okta/okta-sdk-java#1549]
### Describe the feature request?

The previous getUser(id) call returned a User resource, I have a lot of integration code that does things with that result.

The new API in 18.0.0 getUser(id, expand) returns UserGetSingleton resource, which seems identical to User.

My current best workaround is to call listUsers() to the get the previous type, but that seems a little roundabout... I'd like a way to get a User from a UserGetSingleton resource but I can't think of anything. Some sort of mapping function would be appreciated from UserGetSingleton to User.

### New or Affected Resource(s)

UserGetSingleton
User

**Comment by arvindkrishnakumar-okta** [comment]
@carlsandland Thanks for posting!

Yes, our recent spec updates has introduced this new object `UserGetSingleton` that is the return type for `getUser(..)`. This object is exactly the same as `User` object (all the properties are identical). You can use these two objects interchangeably.

**Comment by carlsandland** [comment]
@arvindkrishnakumar-okta my pleasure :) just to confirm, are we suggesting I can safely do the following Java code:
```
return (User) api.getUser(id, expand);
```
The problem I have is that the 'User' type is all over my upper code layer (yes, that's probably not great on my side).

**Comment by arvindkrishnakumar-okta** [comment]
@carlsandland I hear you. A simple helper such as https://github.com/okta/okta-sdk-java/pull/1550 would help?

**Comment by carlsandland** [comment]
@arvindkrishnakumar-okta yeah that would work, I assumed I'd need to go down to the invoke lower level and work with JSON directly rather than Java types. It's an interesting problem: same JSON type with multiple Java representations. I'm not entirely sure the EntityHelper would suffice, as there are readonly properties? (such as activated and other dates). I think this approach here would give me the complete state.

**Comment by clementdenis** [comment]
A simple way to do the conversion is this:
```
UserGetSingleton userGetSingleton = ...;
User user = apiClient.getObjectMapper().convertValue(userGetSingleton, User.class);
```

**Comment by carlsandland** [comment]
@clementdenis thanks for that, seems perfect (map same JSON to multiple types). Happy for this issue to be closed. Will test this tomorrow but logically looks good.
