### ISSUE TITLE
Default configurations are not loaded from okta.properties resource file

### ISSUE THREAD

**Issue by tdemarchi** [okta/okta-sdk-java#1556]
### Describe the bug?

Since version 18.0.0, the default configurations are not loaded from the [okta.properties](https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/resources/com/okta/sdk/config/okta.properties) file provided by the library.

The error was introduced in this [commit](https://github.com/okta/okta-sdk-java/commit/e11a28d5559e4c1e011b7435d4e0ee9666dd0288), file `impl/src/main/java/com/okta/sdk/impl/config/DefaultPropertiesParser.java`, line 49, where it was added a `try` block to close the input stream, but this close happens before the stream can be read (which is done in the `parse()` method called right after). If you debug the code, you will notice that inside of the `parse()` method, the `scanner` will have an silenced error about the stream being closed.

### What is expected to happen?

When instantiating the `ApiClient` class, the default configurations should be loaded.

### What is the actual behavior?

No default configuration is loaded, and if we don't set the configuration, it will be off/zeroed - the in-memoery cache is disabled, and the timeouts are 0 (infinite), for instance.

### Reproduction Steps?

Just instantiate the `ApiClient`.

```java
new Clients.builder()
  .setOrgUrl(orgUrl)
  .setClientCredentials(TokenClientCredentials(clientToken))
  .build()
```

You will notice that this client does not have in-memory cache and the timeouts are zeroed.

### Java Version

openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode, sharing)

### SDK Version

18.0.0

**Comment by arvindkrishnakumar-okta** [comment]
Reverted and fixed this issue - https://github.com/okta/okta-sdk-java/pull/1558/commits/962f3646b5a5fbcc733e5ecff403d94f35c4ac0f

Fix will be available in next release 19.0.0
