### ISSUE TITLE
Unable to set "items" field for UserSchemaAttribute

### ISSUE THREAD

**Issue by literallyjustroy** [okta/okta-sdk-java#1564]
### Describe the bug?

Before v19.0.0 the `UserSchemaAttribute` class supported setting the `items` field. This field is required when utilizing array attributes.

### What is expected to happen?

The `items` field should be settable and allow for creating new string array attributes:
```java
customAttribute.setItems((new UserSchemaAttributeItems().type("string")));
```

### What is the actual behavior?

The `items` field is unsettable and trying to create a new String array attribute without the `items` field returns the following error:
```json
{
  "errorCode": "error",
  "errorSummary": "Items not present for array property: roles.",
  "errorLink": "error",
  "errorId": "oaeTQhxHGxnTVG_nS1CpZm1QQ",
  "errorCauses": []
}
```

### Reproduction Steps?

Attempt to create a new custom attribute for an existing IDP user mapping:

```java
final UserSchemaAttribute customAttribute = new UserSchemaAttribute();
customAttribute.setTitle("roles");
customAttribute.setType(UserSchemaAttributeType.ARRAY);
customAttribute.setRequired(false);
customAttribute.setExternalName("roles");
customAttribute.setItems((new UserSchemaAttributeItems().type("string")));

final UserSchema userSchema = new UserSchema();
final UserSchemaDefinitions userSchemaDefinitions = new UserSchemaDefinitions();
final UserSchemaPublic userSchemaPublic = new UserSchemaPublic();
userSchemaPublic.setProperties(Map.of("roles", customAttribute);

userSchemaDefinitions.setCustom(userSchemaPublic);
userSchema.setDefinitions(userSchemaDefinitions);

oktaSchemaApi.updateApplicationUserProfile(oktaIdpId, userSchema);
```

The need for this property can also be seen by attempting to add a custom attribute with the String Array type in the Classic Engine IDP Profile Editor and looking at the API call made by the UI:
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/13107c75-af1c-4b8f-9f23-71c8ab6a57be">
<img width="729" alt="image" src="https://github.com/user-attachments/assets/937f6c8d-ad71-4667-ac91-49a032b8aa11">

### Java Version

openjdk 17.0.6 2023-01-17 LTS

### SDK Version

19.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@literallyjustroy Thanks for posting! This is again a bug introduced by our latest Open API Spec change in 19.0.0

Will get it fixed.
