### ISSUE TITLE
Breaking change in user / group schema api

### ISSUE THREAD

**Issue by jarek-chmiel** [okta/okta-sdk-java#1568]
### Describe the bug?

Between version 18 and 19 'unique' property of GroupSchemaAttributes and UserSchemaAttributes changed from string to boolean. 
https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/model/UserSchemaAttribute.html#getUnique()

It is impossible to use sdk in version 19, even on preview environment. 

### What is expected to happen?

https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Schema/#tag/Schema/operation/getUserSchema 'unique' property value should be of type string and sdk should be able to handle 'UNIQUE_VALIDATED' value returned by API

### What is the actual behavior?

https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Schema/#tag/Schema/operation/getUserSchema 'unique' property value is of type boolean and sdk is not able to handle 'UNIQUE_VALIDATED' value returned by API

### Reproduction Steps?

Create a schema with one of the properties being 'unique' and fetch schema

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)

### SDK Version

19.0.1

**Comment by jarek-chmiel** [comment]
@arvindkrishnakumar-okta  thank you very much, do you know when it will be fixed and 19.0.2 released?

**Comment by arvindkrishnakumar-okta** [comment]
@jarek-chmiel Expect the next SDK version with fix to be released by end of next week.

**Comment by arvindkrishnakumar-okta** [comment]
Planning a release by end of this week. Please stay tuned.

**Comment by arvindkrishnakumar-okta** [comment]
Next version 20.0.0 is released.
