### ISSUE TITLE
Breaking changes between v16 and v19

### ISSUE THREAD

**Issue by chhauss-a** [okta/okta-sdk-java#1571]
### Describe the feature request?

I have noticed that in the last months you have released 3 new major versions (17, 18, 19).
We have updated to v16 earlier this year and now I wanted to upgrade to v19.

Anyway, there are so many breaking changes, like:
- no additionalProperties for user 
- activation, deactivation, reactivation, etc. on user
- multiple different user classes now returned from different functions (GroupMember, User, UserGetSingleton, ...)
- etc.

I can't really get the hang of all those changes and on how to adopt them. Therefor I wonder if you did or could provide some kind of "Upgrade Guide" for the few latest SDK upgrades.

I am also very interested on to why you have made those changes, as they seem to me (and I'm not too deeply into the topic) that making things rather more complicated.

Looking forward to hear from you!

### New or Affected Resource(s)

v17, v18, v19

**Comment by arvindkrishnakumar-okta** [comment]
@chhauss-a Thanks for posting!

These breaking changes are driven mostly by the underlying backend API changes that are defined in our OpenAPI spec. As a general practice, we try to avoid frequent releases containing breaking changes but the recent releases were unavoidable.

I'll get out the user friendly upgrade guide soon.

Thanks again for the feedback!

**Comment by chhauss-a** [comment]
Hey @arvindkrishnakumar-okta,

thanks for replying. Looking forward to the upgrade guide! I will postpone the update to when it comes out. Thanks!

**Comment by arvindkrishnakumar-okta** [comment]
Looks like there was a support case raised for this and this has been handled by them individually and a response has been sent.

**Comment by Marek26** [comment]
@arvindkrishnakumar-okta: We have not opened a case. Could you please forward the response of the support to us (or share in this issue) so we can also benefit from the solution?

**Comment by arvindkrishnakumar-okta** [comment]
I recommend you open a support case as the report of the breaking changes is a large file which isnt ideal to be uploaded here.
