### ISSUE TITLE
Change Recovery Question Requiring password

### ISSUE THREAD

**Issue by nsrirameig** [okta/okta-sdk-java#1573]
### Describe the bug?

I am trying to  set the recovery credential  using SDK similar  to PUT operation in the rest api.

Set recovery credential (configure recovery question):

Users > Credential Operations.

PUT {{url}}/api/v1/users/{{userId}}.

Current change recovery question  requires password,

### What is expected to happen?

Recovery  question  should be set successfully without password.

### What is the actual behavior?

Error 400  with requiring password.

### Reproduction Steps?

 userCredApi.changeRecoveryQuestion

### Additional Information?

N/A

### Java Version

17

### SDK Version

19.0.1

### OS version

Darwin 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:29 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6000 arm64

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting, will get this triaged.

**Comment by arvindkrishnakumar-okta** [comment]
Did you try this with POSTMAN and are you getting a similar response (HTTP 400 with password required?

**Comment by nsrirameig** [comment]
Arvind,

There is two calls  one with POST which requires password , and another is PUT which doesn't .  Yes its working with PUT from postman and I am looking for that PUT equivalent in the API

**Comment by arvindkrishnakumar-okta** [comment]
I think you're referring to https://developer.okta.com/docs/api/openapi/okta-management/management/tag/UserCred/#tag/UserCred/operation/changeRecoveryQuestion which is a `POST` and I dont think there's a `PUT` equivalent for this operation. Please re-check the API docs and let me know if you still have questions.

As a general reminder note, the issues section in this repo is reserved for bugs, feature requests only. For questions on API, please post in [Dev forum](https://devforum.okta.com/) or contact support team.

**Comment by nsrirameig** [comment]
Thanks this is the call I mentioning that is in the rest api but  not in the SDK

<img width="785" alt="Screenshot 2024-11-06 at 09 49 10" src="https://github.com/user-attachments/assets/8856775f-e045-4305-98f9-b487110e2677">

**Comment by arvindkrishnakumar-okta** [comment]
Where did you get the above screenshot from? Can you share the link to the API docs that has the above API?

**Comment by nsrirameig** [comment]
I have it  as postman collections , this is the help page with the information https://support.okta.com/help/s/article/how-to-bulk-set-password-recovery-question-for-users-using-postman?language=en_US

**Comment by arvindkrishnakumar-okta** [comment]
I don't know where you got the above request from POSTMAN collection from. Ideally, you should refer to the official API docs at https://www.postman.com/okta-eng/okta-public-api-collections/overview (public POSTMAN collection) and https://www.postman.com/okta-eng/okta-public-api-collections/overview (public API doc).

**Comment by nsrirameig** [comment]
I did download the collections from the official site few months ago , I am suspecting the "PUT" method might  have been removed . I am good with closing this one out , since PUT method does work via postman , even support team  recommended  using PUT to  update the security recovery questions.
