### ISSUE TITLE
18.x.x -> 19.x.x Migration steps are missing

### ISSUE THREAD

**Issue by dmiroshnikov** [okta/okta-sdk-java#1576]
In #1558, you dropped reactivate functionality from UserApi by updating api.yaml

v18.x docs:

- [https://developer.okta.com/okta-sdk-java/18.0.0/apidocs/com/okta/sdk/resource/api/UserApi.html#reactivateUser(java.lang.String,java.lang.Boolean)](https://developer.okta.com/okta-sdk-java/18.0.0/apidocs/com/okta/sdk/resource/api/UserApi.html#reactivateUser%28java.lang.String,java.lang.Boolean%29)

v19.x docs:
- https://developer.okta.com/okta-sdk-java/19.0.0/apidocs/com/okta/sdk/resource/api/UserApi.html

May you provide migration steps for users who relies on UserApi.reactivateUser functionality?

**Comment by dmiroshnikov** [comment]
@arvindkrishnakumar-okta 

May you tell why interface for UserApi was changed and what is the reason of dropping reactivateUser functionality?

**Comment by arvindkrishnakumar-okta** [comment]
@dmiroshnikov Thanks for posting.

I'll add the migration steps. As to why `UserApi.reactivateUser` went missing in 19.x.x, I acknowledge that this is a bug introduced when we updated the backend OpenAPI spec. Will get these addressed.
