### ISSUE TITLE
Question on Pagination.

### ISSUE THREAD

**Issue by SrihariGanadinni** [okta/okta-sdk-java#170]
@bdemers In the new version of the sdk the pagination is mentioned to be automatic.Please let me know if pagination can still be used like the previous okta sdk.

The previous version of okta sdk allowed client executing the sdk a greater flexibility to restart  a batch execution from the failure point in case of network failures.

**Comment by bdemers** [comment]
Not directly, but we do have automatic retry logic.  Were you programmatically retrying after a failure?

Can you give me an example of how you were iterating over all of your users? How many users did you have?  

I ask for two reasons, we could possibly suggest a different approach, and if we add this or similar feature.

All that said, you _could_ use the DataStore `client.getDatastore()` directly to make any request.

**Comment by SrihariGanadinni** [comment]
The use case is we have a batch which validates data across our systems.If we find discrepancies with data we make necessary changes.
Sometimes this batch might start running during our maintainence windows.If we see too many network call failures on our end due to our maintainence window.
we save the getUserPagedResultsWithUrl into file.When our systems are back up we use the saved pagination url to restart the process so that we do not have to reprocess the whole data.

With this new sdk I do not know if this is possible.

**Comment by bdemers** [comment]
@SrihariGanadinni Great info!

You _could_ still do this by using `client.getDataStore().getResource("your-href", UserList.class)`

You may also want to change your search filter to only return the results from the subset of users you are looking for.

Does this help?

**Comment by SrihariGanadinni** [comment]
I can try,but I do not know if this is going to help process over millions of records.

**Comment by bdemers** [comment]
@SrihariGanadinni I'll close this issue, if that doesn't help, please reopen!

**Comment by SrihariGanadinni** [comment]
I started to work on it ,seems like there is no difference ,unless I am missing something,can you provide me an example?
1. UserList users = client.listUsers(null, "status eq \"ACTIVE\"", null, null, null);
2. UserList users =  client.getDataStore().getResource("Org url with filter",UserList.class)

Are you suggesting that I execute the first step and then pull the getnexturl from the userlist and then use the second step to getdatastore to get the userlistdata?

**Comment by bdemers** [comment]
Sort of,
You could keep track of an index as you loop through and set the `after` query param if you are forced to retry.
https://developer.okta.com/docs/api/resources/users.html#request-parameters-2

**Comment by SrihariGanadinni** [comment]
I am trying out the solution that was provided it keeps giving com.okta.sdk.resource.ResourceException: HTTP 400, Okta E0000031 (Invalid search criteria.), 

_Works:_

DEFAULT_FILTER_CRITERIA = "status eq \"ACTIVE\"";
UserList users = client.listUsers(null, DEFAULT_FILTER_CRITERIA, null, null, null);

_Erroring out:_

DEFAULT_FILTER_CRITERIA = "status eq \"ACTIVE\"&limit=150";
UserList users = client.listUsers(null, DEFAULT_FILTER_CRITERIA, null, null, null);

But if I go to postman and execute the criteria like below it works,unless I am missing something.

_Works on Postman:_
?filter=status%20eq%20%22ACTIVE%22&limit=3&after={OktaaUserID}

**Comment by SrihariGanadinni** [comment]
Okay,now I understand the filter has been simplified to restrict to what is documented in docs page and anything additional is via  getdatastore. Probably documentation in examples would help! :)

**Comment by bdemers** [comment]
Agreed, this discussion is helpful to see some of the use cases that we should add some doc for
