### ISSUE TITLE
Support for 'Connected Accounts IDs (optional)'

### ISSUE THREAD

**Issue by corrjo** [okta/okta-sdk-java#171]
In the UI, its possible to update the 'Connected Accounts IDs (optional)' value for SAML applications, however it doesnt seem possible with the sdk.

**Comment by corrjo** [comment]
Tagging @bdemers, hoping for a little love on this.

**Comment by bdemers** [comment]
Trying to track that down now!

**Comment by bdemers** [comment]
@corrjo It doesn't look like that Application type is directly mapped into our objects.

You could make an API request and the path to that property should be: `your-app.settings.app.accountsIds`

You could also set that property by changing to a compile dependency on` okta-sdk-impl`, and traverse the object and call `setProperty("accountsIds")`

**Comment by laura-rodriguez** [comment]
This might be no longer relevant since many updates were introduced to our spec/SDK. Closing now but feel free to reopen if this is still an issue for you.
