### ISSUE TITLE
List of Users (Pagination)

### ISSUE THREAD

**Issue by matthewdfleming** [okta/okta-sdk-java#173]
I've looked about the api and figured out how to `listApplicationUsers()` as a stream. I'm planning on proxying the api from my back-end and then displaying the users on my front-end. In order to do this, I need to be able to paginate the responses that come back from the call. Is there a way to accomplish this via the java sdk?

**Comment by bdemers** [comment]
Sort of, take a look at this thread:
https://github.com/okta/okta-sdk-java/issues/170
I think it would be `client.getDataStore().getResource("/api/v1/users?_your_query_params_here_")`

Keep me posted we might be able to build a more convenient way into the SDK for this

**Comment by bdemers** [comment]
You can now use the `RequestBuilder` from `client.getDataStore().http()` to make arbitrary requests.

Let us know if this doesn't help!
