### ISSUE TITLE
Client SDK usage

### ISSUE THREAD

**Issue by paulodamaso** [okta/okta-sdk-java#189]
Hello!

A have a few questions about okta java SDK, and I couldn't find anything about it in Okta Client SDK:

- I am trying to retrieve user information from okta server. When using the API I make a call to `/userinfo` endpoint, passing a user token. How could I get this user information using client SDK? I couldn't discover how get user info passing a `bearer` token.
- How do I get tokens using client SDK ('oauth2/default/v1/token') endpoint (authorization_code, for example)?
- Is there a way to retrive LinkedObjects (https://developer.okta.com/docs/api/resources/linked-objects) using client SDK?

Thank you

**Comment by bdemers** [comment]
Hey @paulodamaso !

This project only covers the management API (not OAuth/OIDC).  For that you can use our Spring Boot integration, Spring Security, or another OAuth/OIDC library. https://github.com/okta/samples-java-spring

The LinkedObjects isn't supported we typically do not add new endpoints until after they are GA.  

Thanks for reaching out!
