### ISSUE TITLE
Ensure all OIDC application values are carried over in the spec

### ISSUE THREAD

**Issue by jmelberg-okta** [okta/okta-sdk-java#207]
Carried over from internal repo: [#132](https://github.com/okta/openapi/issues/132).
- `post_logout_redirect_uris` are missing from OIDC Application `settings.oauthClient`

**Comment by shalinmangar** [comment]
Is there a workaround for this? I need to set a custom logout uri for an OIDC application.

**Comment by bdemers** [comment]
Hey @shalinmangar!

You should be able to treat any of the resource objects like a map to set other properties.
For more complex objects you can do something like this too:
https://github.com/okta/okta-sdk-java#call-other-api-endpoints

**Comment by arvindkrishnakumar-okta** [comment]
Update: Latest Open API Spec v2.0.0 carries all the OIDC application values.
