### ISSUE TITLE
DefaultUserBuilder setProvider has no impact

### ISSUE THREAD

**Issue by PaulStat** [okta/okta-sdk-java#212]
It seems the default implementation of the UserBuilder interface has a method for setProvider(Boolean provider) which is then used to call the client with this flag.

However as the builder has no way to set the authentication provider, when the call to client create is made the provider flag is effectively redundant as the builder hasn't set the details in the body of the user.

**Comment by bdemers** [comment]
It looks like we need a `setCredentials()` object (or maybe a `setAuthenticationProvider()` that takes care of setting all three of those fields? 🤔

**Comment by PaulStat** [comment]
I'd go with setCredentials, could do with adding interface for hashed password imports as well.

**Comment by bdemers** [comment]
@PaulStat I went with `setCredentials()` to help support the general use cases you mentioned, password imports, etc.

But... I'd like to flatten it out, so please chime in on #226 if interested

**Comment by bdemers** [comment]
@PaulStat, (I wasn't happy with that PR)
Which payloads are you trying to send, we should be able to target this use case more specifically, I'm assuming something like:

```json
"credentials": {
    "provider": {
      "type": "FEDERATION",
      "name": "FEDERATION"
    }
  }
```

and:

```json
"credentials": {
    "password" : {
      "hash": {
        "algorithm": "BCRYPT",
        "workFactor": 10,
        "salt": "rwh3vH166HCH/NT9XV5FYu",
        "value": "qaMqvAPULkbiQzkTCWo5XDcvzpk8Tna"
      }
    }
  }
```

**Comment by bdemers** [comment]
(clicked the wrong button, again...)

**Comment by PaulStat** [comment]
That's exactly it except with sha-256 instead of bcrypt in my case

**Comment by PaulStat** [comment]
Second one imo
