### ISSUE TITLE
Error on fetching applicationlist using okta-java-sdk

### ISSUE THREAD

**Issue by dineshbade** [okta/okta-sdk-java#216]
I have been trying to fetch the application list but got error

> Could not write JSON: No enum constant com.okta.sdk.resource.application.ApplicationSignOnMode.SAML_1_1; nested exception is com.fasterxml.jackson.databind.JsonMappingException: No enum constant com.okta.sdk.resource.application.ApplicationSignOnMode.SAML_1_1

**Comment by bdemers** [comment]
@dineshbade
I’ll take a look tomorrow, but does this happen when you call the list apps method or when you call the get signing mode method?

**Comment by bdemers** [comment]
I was able to reproduce this by creating a SAML 1.1 template application, and then calling `Application.getSignOnMode()`.

We will get a fix in, but in the short term, for a work around you can do something like this, which casts the `Application` to a `PropertyRetriever` and then just gets the raw string property:

```java
client.listApplications().forEach(app -> ((PropertyRetriever)app).getString("signOnMode"));
```
