### ISSUE TITLE
Problem on assigning application to user

### ISSUE THREAD

**Issue by dineshbade** [okta/okta-sdk-java#220]
i have been working arround to assign application to user . I find method assignUserToApplication (AppUser user) but i got error `java.lang.IllegalArgumentException: Object of class [com.okta.application.service.impl.OktaUserManagementServiceImpl$1] must be an instance of class com.okta.sdk.impl.resource.AbstractResource `.

**Comment by bdemers** [comment]
Can you add the snippet of code you are using so we can help you out?

**Comment by dineshbade** [comment]
`        Application application = oktaClientBuilder.getOktaClient().getApplication(appId);
 application.assignUserToApplication(new AppUser() {
            @Override
            public Map<String, Object> getEmbedded() {

                    return user.getEmbedded();
            }

            @Override
            public Map<String, Object> getLinks() {
                return user.getLinks();
            }

            @Override
            public Date getCreated() {
                return user.getCreated();
            }

            @Override
            public AppUserCredentials getCredentials() {
                return null;
            }

            @Override
            public AppUser setCredentials(AppUserCredentials appUserCredentials) {
                return null;
            }

            @Override
            public String getExternalId() {
                return null;
            }

            @Override
            public String getId() {
                return user.getId();
            }

            @Override
            public AppUser setId(String s) {
                return null;
            }

            @Override
            public Date getLastSync() {
                return null;
            }

            @Override
            public Date getLastUpdated() {
                return null;
            }

            @Override
            public Date getPasswordChanged() {
                return null;
            }

            @Override
            public Map<String, Object> getProfile() {
                return user.getProfile();
            }

            @Override
            public AppUser setProfile(Map<String, Object> map) {
                return null;
            }

            @Override
            public String getScope() {
                return null;
            }

            @Override
            public AppUser setScope(String s) {
                return null;
            }

            @Override
            public String getStatus() {
                return user.getStatus().toString();
            }

            @Override
            public Date getStatusChanged() {
                return null;
            }

            @Override
            public String getSyncState() {
                return null;
            }

            @Override
            public AppUser update() {
                return null;
            }

            @Override
            public void delete() {

            }

            @Override
            public String getResourceHref() {
                return null;
            }

            @Override
            public void setResourceHref(String s) {

            }
        });
`

**Comment by bdemers** [comment]
@dineshbade to create a new resource instance you can use:
`client.instantiate(InterfaceType.class)`

For example: https://github.com/okta/okta-sdk-java#create-a-swa-application
Please reopen this if you still have questions!
