### ISSUE TITLE
Assigning role to a user

### ISSUE THREAD

**Issue by Vatavuk** [okta/okta-sdk-java#221]
I have to assign a role to a user and I'm using method `assignRole(Role role)` from `User` interface for that. The problem is that it seems that there is no way to instantiate new `Role` object. There is no `RoleBuilder` or some implementation other than `DefaultRole` which cannot be used without `InternalDataStore` information. Is there some way to create `Role` instance without having to provide `InternalDataStore` object?

**Comment by bdemers** [comment]
Hey @Vatavuk!

Use `client.instantiate(Role.class)` to create a new instance.

For example, creating a Factor is similar: https://github.com/okta/okta-sdk-java#enroll-a-user-in-a-new-factor

**Comment by Vatavuk** [comment]
@bdemers Thanks!

**Comment by sonu3706** [comment]
@Vatavuk Were you able to assign role to user after creating user account in okta ??

**Comment by Vatavuk** [comment]
@sonu3706 yes, had no problem with that.

**Comment by sonu3706** [comment]
@Vatavuk Can you help me with the steps as I am unable to find any proper documentation for the same.
As I am able to create a user with Temp password using okta SDK and then I need to assign role to the users.
I am using Spring boot 
Thanks in advance

**Comment by bdemers** [comment]
@sonu3706 lets keep this in #249
