### ISSUE TITLE
Creating a collection or iterating a UserList returns all items with limit. 

### ISSUE THREAD

**Issue by yasmani-isaac-mfp** [okta/okta-sdk-java#230]
for example if I want to return the list of User by doing something like this:

client.getDataStore().getResource(orgUrl+"/api/v1/users?limit=2", UserList.class).stream().collect(Collectors.toList());

instead of returning a list of users with size 2, it returns the entire list

It works correctly when adding a search query such as: 

client.getDataStore().getResource(orgUrl+"/api/v1/users?q=name&limit=2", UserList.class).stream().collect(Collectors.toList());

returns a list of 2.

**Comment by bdemers** [comment]
looks like you have an extra quote in that string,  let me know what it should be and i'll take a look.

Thanks for reporting @yasmani-isaac-mfp !

**Comment by yasmani-isaac-mfp** [comment]
> looks like you have an extra quote in that string, let me know what it should be and i'll take a look.
> 
> Thanks for reporting @yasmani-isaac-mfp !

I fixed it. As I mentioned that portion is working correctly. It is the first example that is not.

Thanks.

**Comment by yasmani-isaac-mfp** [comment]
The UserList object returns the correct number of items with 'limit' query parameter. The problem is when you invoke the stream and then collector methods, it returns the full list. Try this: 

client.getDataStore().getResource(orgUrl+"/api/v1/users?limit=2", UserList.class).stream().collect(Collectors.toList());

**Comment by bdemers** [comment]
Thanks, that helped!  The library is actually doing is actually _correct_
The `limit` query param specifics the page size, not the max number of items returned.  The `UserList` implementation automatically fetches the next page when iterating.

Are you trying to iterate over the pages manually? or just limit the number of results returned?

**Comment by yasmani-isaac-mfp** [comment]
> Thanks, that helped! The library is actually doing is actually _correct_
> The `limit` query param specifics the page size, not the max number of items returned. The `UserList` implementation automatically fetches the next page when iterating.
> 
> Are you trying to iterate over the pages manually? or just limit the number of results returned?

I want to limit the number of results returned. For example, I have 20 users total and I want to show two users per page, then I would call:

 client.getDataStore().getResource(orgUrl+"/api/v1/users?limit=2", UserList.class).stream().collect(Collectors.toList()); 

correct?

**Comment by yasmani-isaac-mfp** [comment]
> The UserList class follows headers and automatically will request the next page when iterating. In your example above you are iterating over the whole collection (which will request multiple pages).
> 
> The easiest option (assuming you didn't want to page the request manually) would be to add a limit in the stream, something like:
> 
> ```java
> client.getDataStore().getResource("/api/v1/users?limit=2", UserList.class).stream().limit(2).collect(Collectors.toList())
> ```
> 
> I think i see some confusion though, when using `q=name` you are changing the way the search is performed on the server side, this type of search does NOT support pagination
> https://developer.okta.com/docs/api/resources/users#find-users
> 
> Does that help?

Yes, that helps. 
Thank you very much!
