### ISSUE TITLE
missing nextLogin param on Create User

### ISSUE THREAD

**Issue by paulux84** [okta/okta-sdk-java#232]
In [create user api](https://developer.okta.com/docs/api/resources/users?_ga=2.140996850.1774291415.1542987312-837160947.1542987312#create-user) "nextLogin" parameters is missing

**Comment by bdemers** [comment]
Thanks @paulux84 for the report! We will get this in the queue!

**Comment by bdemers** [comment]
Fixed in 1.4.0

**Comment by paulux84** [comment]
Hi,
i've upgraded to 1.4.1 but i can't find the method...can you help me with an example?
Thanks

**Comment by bdemers** [comment]
It's one of the [`client.createUser()` methods](https://developer.okta.com/okta-sdk-java/1.4.1/apidocs/com/okta/sdk/client/Client.html#createUser(com.okta.sdk.resource.user.User,java.lang.Boolean,java.lang.Boolean,com.okta.sdk.resource.user.UserNextLogin)
)

**Comment by paulux84** [comment]
Strange, Is the First place where I've searched without success.
I re-search 😀

Il gio 28 feb 2019, 20:08 Brian Demers <notifications@github.com> ha
scritto:

**Comment by paulux84** [comment]
Hi again,
i've found the problem.
In my code i use the  'UserBuilder` class in this way:
```
UserBuilder builder = UserBuilder.instance()
                .setEmail("email@email.com")
                .setFirstName("name")
                .setLastName("surname")
                .setPassword(password.toCharArray())
                .setSecurityQuestion("Favorite security question?")
                .setSecurityQuestionAnswer("None of them!")
                .setActive(false);
       User user = builder.buildAndCreate(client);
       user.activate(true);        
```
The problem is that the only place where i have `nextLogin` method is on `client.createUser` and not in `UserBuilder`
So there are 2 possibility...adding it to the `Builder` or implement the method `build` on Builder it self so you can build the user and than call `client.createUser(..)`

**Comment by bdemers** [comment]
Ahh! yes we can add it there too

**Comment by bdemers** [comment]
@paulux84 have a look at #270
