### ISSUE TITLE
REST client unable to work behind the enterprise proxy

### ISSUE THREAD

**Issue by saschaD81** [okta/okta-sdk-java#237]
Bug to be reported: the following code will never set username and password for the authenticating proxy, making the REST client unable to work behind the enterprise proxy. As soon as there's a proxy port, the first "if" condition matches.

okta-sdk-impl-1.3.0.jar

com.okta.sdk.impl.config.ClientConfiguration.getProxy()

line 211:
Proxy proxy = null;
// use proxy overrides if they're set
if (getProxyPort() > 0 || getProxyHost() != null && (getProxyUsername() == null || getProxyPassword() == null)) {
proxy = new Proxy(getProxyHost(), getProxyPort());
} else if (getProxyUsername() != null && getProxyPassword() != null) {
proxy = new Proxy(getProxyHost(), getProxyPort(), getProxyUsername(), getProxyPassword());
}

**Comment by bdemers** [comment]
@saschaD81 Thanks for the report!

Until this fix get merged and released you should be able to use the standard Java proxy system properties.
