### ISSUE TITLE
ClientBuilder needs connection test

### ISSUE THREAD

**Issue by jamesdcarroll** [okta/okta-sdk-java#239]
Just starting out with SDK so built simple client per doc.  No matter what orgURL or token I pass, however, there's no indication of success or failure. `client` is always not null and its not until I try to make a call that I get 401 for bad token or  `java.net.UnknownHostException` for bad address.  Seems like that should be a way to determine if the client is "ready"; either by throwing those errors from `build()` (or a `boolean isReaday` function that does) or setting `client` to null.

**Comment by bdemers** [comment]
Hey @jamesdcarroll!

The client doesn't make any URL connections until you call a client method.  I do like the idea of an `isReady()` method or something like that.  That said these errors could also happen after the client is initialized (for example: if there was a network issue, or the API key was revoked)

Were you able to figure out what the issue was based on the descriptions in the exceptions/logs?

**Comment by jamesdcarroll** [comment]
Yea, the funny thing is I knew the error going in as I was testing how it handled badURL or badToken so I could write the error handling code.  But build() would throw anything so it was irking me that I couldn't really validate that what I had gotten back from build() was usable before I tried to make a call.

**Comment by bdemers** [comment]
We could do this a few ways 🤔 

```java
client.isReady()
```
```java
Clients.builder()
  .validateConnection()
  .build()
```

**Comment by jamesdcarroll** [comment]
If it were me, I would vote for 

```
Clients.builder()
  .build()
  
client.isValid();
```
That way I can write 
```
Clients.builder()
  .build()
  if(client == null{
    for (Error err: client.errors){
         log.fatal("Connenction could not be built:" + err.message;
         return nulll;
     }
   }
 if (!client.isValid){
  for (Error err: client.errors){
         log.fatal("Connenction could not be validated:" + err.message;
         return client;
    }
   }
```

**Comment by bdemers** [comment]
Trying to think about this a little more, in the case of an "invalid" client what would your application do? Throw an exception? Or go down another logic path?

**Comment by VitaliiTytarenko-okta** [comment]
The new method `isReady` was added to the DataStore.
see: https://github.com/okta/okta-sdk-java/blob/e02a77d891fffa7e44e33da44263654a765e28eb/api/src/main/java/com/okta/sdk/ds/DataStore.java#L124
