### ISSUE TITLE
Make YAML dependency optional

### ISSUE THREAD

**Issue by robertjd** [okta/okta-sdk-java#241]
Refactor the snake YAML dependency to be optional, in such a way that okta-auth-java will not have a hard dependency on that library.

**Comment by bdemers** [comment]
There are a couple of touch points that I can think of where we parse YAML files:

- Loading config from `~/.okta/okta.yaml` (don't parse this file if the YAML parser is not available)
- Default configuration `classpath:com/okta/authn/sdk/config/okta.yaml` (switch to a  json or properties format, or set the defaults programmatically)
- The class: com.okta.sdk.impl.ds.DiscriminatorConfig (not 100% sure on this one, switching to json might be a quick win, This code path might be executed when the auth-sdk is trying to figure out the factor type to marshal/unmarshal)

**Comment by bdemers** [comment]
Fixed by #243 and #445
