### ISSUE TITLE
Support Users Schemas API

### ISSUE THREAD

**Issue by adbdkb** [okta/okta-sdk-java#258]
Feature Request : I would like to be able to create a new attribute or update the properties of the existing attributes using Okta SDK.  [Ref : Okta forum question ](https://devforum.okta.com/t/is-there-a-way-to-change-the-attributes-for-a-user-programmatically-using-the-okta-sdk/4048/): 

The reason I am looking to do this in a programmatic way : 

I am a developer implementing Okta OIDC security for our application.   For that, we need to change the login id to change the Format Restriction property of the login attribute from email to None so that we can import ids that are not email format into Okta.  

I also want add a few custom attributes for every user in the application with different formats and other properties such as required or not etc.

I know both of these can be done using the UI ( Profile Directory ), but being a developer, I do not have access to make changes in the environments.  This means, I will have to give the details to the admins and they will have to manually perform those changes.  If the list of custom attributes is big, then this approach can lean to human error as it adds to the responsibility of the admins.

I also realise that to perform these tasks using the SDK, we will need the token which a developer should not have.

This is the first time the organisation is implementing Okta, so both the developers and the admins are learning the tool and its capabilities and nuances and also best practices.

So, my thinking is - the developer can create a simple java or spring-boot application for the tasks and give it to the administrators, they can either update the code with appropriate key value or maybe even have an environment variable which we would reference from the code and the admins could just run the application,  This can help reduce the burden on them as well as reduce the possibility of human error.

As this is not possible to do at this moment, I do not have a conceptual sample project.

Thanks
Aru

**Comment by bdemers** [comment]
https://developer.okta.com/docs/api/resources/schemas

**Comment by arvindkrishnakumar-okta** [comment]
This should be supported in latest iteration of the SDK.
