### ISSUE TITLE
Support multiple cache keys

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#265]
Some Okta resources can be retrieved via multiple identifiers.  For example Users can be retrieved via the `id` and the `login` (typically email address).

Our current cache impl caches based on the `self` link in the resource body, which will always uses the `id` version of the URL.  
A request to `/users/foo@example.com` would be cached, and a request to `/users/some-user-id` would trigger a cache hit, but additional requests to `/users/foo@example.com` would be a cache miss.

For objects that support multiple URLs we could cache each version of the URL (or alias the cache somehow).

**Comment by vekdeq** [comment]
Hi, 
How to make getUser call to get User on Login ID - which can be an email or something else in our case ? Practically, I want to check if User ID exists or not. Is there any API to check if User ID exists or not.

**Comment by bdemers** [comment]
Hey @vekdeq,

You would just call `getUser("...")` and catch a ResourceException (and check the `status` on the object)

If you still have questions, please open a separate issue
