### ISSUE TITLE
Extract static init section in HttpClientRequestExecutor

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#276]
These properties are hard to test (more so post Java 8), but these props should also be moved up into the config system of the client (or somehow passed into the ClientConfig object)

Possibly `okta.client.httpclient.*` ?

NOTE: I'd also like to pull the RequestExecutor/low level HTTP logic out of the SDK, so we should avoid direct coupling of SDK -> httpclient props

**Comment by sergiishamrai-okta** [comment]
PR: https://github.com/okta/okta-sdk-java/pull/519

**Comment by arvindkrishnakumar-okta** [comment]
Fixed.
