### ISSUE TITLE
Need Resource Owner Password Flow

### ISSUE THREAD

**Issue by dongmei-cao** [okta/okta-sdk-java#280]
I opened the [same issue](https://github.com/okta/okta-auth-java/issues/42) in okta/okta-auth-java repo. But per @nbarbettini, the auth sdk is not for OIDC client. Please include the [Resource Owner Password Flow REST API call](https://developer.okta.com/authentication-guide/implementing-authentication/password/#_2-using-the-resource-owner-password-flow) in this SDK. We have public REST API that requires an OAuth access_token. We use the Resource Owner Password Flow to generate the required OAuth access_token.

**Comment by bdemers** [comment]
Hey @dongmei-cao!

We have a few different java libs, this one doesn't support end user authentication. 
- okta-sdk-java - okta resource management (creating users, groups, etc)
- okta-jwt-verifier-java - Validate Okta's JWT access tokens (to be used in various java frameworks)
- okta-spring-boot - Spring Boot integration that makes configuring Spring Security easier to use with Okta
- okta-auth-java -  a wrapper around Okta's [Authentication](https://developer.okta.com/docs/api/resources/authn/) API (though we would recommend using an OAuth 2.0 flow instead)

In general I would recommend avoiding resource owner password flows (there is pile of explanations on the web supporting this). For testing purposes you can use the [OIDC Debugger](https://oidcdebugger.com/) to create tokens, similar to what is done in a few of our blog posts: https://developer.okta.com/blog/2018/12/18/secure-spring-rest-api#generate-tokens-in-your-spring-rest-api

That said, and before I jump to conclusions, can you tell us more about what you are trying to do, and we can point you in the right direction?  We have a ton of examples for Web based clients (but things get more interesting when the client is a Mobile or desktop app)

**Comment by dongmei-cao** [comment]
@bdemers  I understand all the reasons you gave here. We worked with the Okta profession service and figured out the current solution we have that requires the Resource Owner Flow to get an Oauth access_token to access our REST API. Those are public REST API that the end users will programmatically invoke them in their own programs. We also have our own login UI that uses one of the OAuth flows (not Resource Owner Password Flow). With all that said, my questions is that the API is obvious available for us to use. I would like to see one of the SDK to include it. I originally thought that it should be included in the okta-auth-java. But @nbarbettini gave his reasons of not including there. So, please include it in one of the SDK.

**Comment by nbarbettini** [comment]
Hey @dongmei-cao, thanks for your patience.

Is your API using the Resource Owner Password flow to talk to _another_ API, or do you need to provide the Resource Owner Password flow to the consumers of your API? I'm trying to better understand what your API needs to do.

You can email me at nate.barbettini@okta.com if you'd rather not share details publicly.
