### ISSUE TITLE
Extra API Call to okta if I called UserList.iterator() twice in a row.

### ISSUE THREAD

**Issue by xiao904** [okta/okta-sdk-java#281]
Assuming we get a userList below:
`UserList userList = client.listUsers(null, null, null, searchUserCriteria, null);`
When we first time to invoke `iterator()`, it returns a normal iterator containing all items in the list.
But if we call `iterator()`, `single()`, `stream()` or `for(User u: UserList)` again, it'll make another api call to okta.
e.g.
```
  Iterator<User> iterator = userList.iterator();
  if (!iterator.hasNext()) {
      return null;
  }
  return userList.single();
```
The above code makes two api calls to okta for `/api/v1/users`. It eventually doubles our traffic which makes us hit the api rate limits unexpectedly.

**Comment by bdemers** [comment]
I'll take a look, but can you explain why you are using an iterator and `single()` ? Or is that just an example.
Are you iterating over whole collection?  This collection will page automatically if the REST response contains more multiple pages.

**Comment by xiao904** [comment]
Because this list should only contain one item. I use iterator because I want to check if it's empty or not. If not empty, I use single() to retrieve that item.
It should not contain multiple pages. We store the user id from another database in userprofile. so every time we search for the user by that id and it should always return a single user in the List.
The bug we think is that you have a flag to determine whether to fetch the first page again, when you first time call `iterator()` the flag is false, after that each time you call iterator() again it's all true.
Check the method `iterator()` in class AbstractCollectionResource you will see what I mean.

**Comment by bdemers** [comment]
Thanks for the report @xiao904 !

The quick work around is to use `client.getUser("<userid|username>)` instead (you would need to handle a resource not found exception though.

**Comment by xiao904** [comment]
No, we cannot use getUser("userid") because that userid is the user id in **another database's ID** not okta id. We manage to work around it is just referencing the iterator we got for the first time then we reuse that iterator.

**Comment by bdemers** [comment]
@xiao904 can you give me an example of the search/filter you are using?

**Comment by xiao904** [comment]
e.g. GET /api/v1/users?search=profile.anetUserProfileId+eq+12345678

**Comment by bdemers** [comment]
@xiao904 gotcha! that helps, I understand what you are doing now, i'll dig in a bit!

**Comment by bdemers** [comment]
Thanks @xiao904! 
There a similar issue related to the `isEmpty()` method.  We will get this in to the next release.
