### ISSUE TITLE
Feature request: Add headers support in RequestBuilder

### ISSUE THREAD

**Issue by fy-gualtiero-testa** [okta/okta-sdk-java#297]
Current RequestBuilder allows us to invoke endpoints not directly supported by the client.

Unfortunately RequestBuilder does now allow to define per request headers.

Use case: invoke OAuth /userinfo:

```
curl -v -X POST \
-H "Authorization: Bearer ${access_token}" \
"https://{baseUrl}/userinfo"

```
(from https://developer.okta.com/docs/reference/api/oidc/#userinfo )

**Comment by bdemers** [comment]
Thanks @fy-gualtiero-testa !
This dovetails with something similar I was working on, so it's an easy add.

I do want to caution against using this SDK to access endpoints with a bearer token.  The SDK would likely add BOTH auth headers to the request.

That said, we will likely add OAuth support in the near future (which would fix that)
