### ISSUE TITLE
Create User followed by immediate authentication

### ISSUE THREAD

**Issue by andyclarke-okta** [okta/okta-sdk-java#303]

**Comment by andyclarke-okta** [comment]
Workflow creates an activated user with cleartext password via SDK. Immediately upon receiving the successful response create user API response, they authenticate that user. 
This scenario works 99% of the time, but occasionally the authn responds with 404 'user not found'. 
Subsequent authn attempts are successful. 
This behavior only happens with the Okta Java SDK, using straight Http calls is 100% successful.

**Comment by bdemers** [comment]
This isn't a problem with the Java SDK, it's just that it is easier to reproduce due to the speed of the requests.
