### ISSUE TITLE
error in swagger.yaml

### ISSUE THREAD

**Issue by umanoharSmarsh** [okta/okta-sdk-java#304]
There seems to be an error with this swagger.yaml - Structural error at paths./api/v1/users/{userId}/factors/{factorId}/lifecycle/activate.post.responses.200.schema
should NOT have additional properties
additionalProperty: type
Jump to line 2046

**Comment by bdemers** [comment]
@umanoharSmarsh Thanks for the report!
Which set of swagger/openapi tools are you using?

**Comment by umanoharSmarsh** [comment]
Tried it on swagger online editor
