### ISSUE TITLE
README contains error related to `requestTimeout`

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#307]
The README should be updated with recommendations for the `requestTimeout`
The default value of this property in the SDK is `0`, due to backward compatibility concerns. 

The SDK should cover the two types of typical clients:
1.) interactive (where the SDK is used in a web service), where the retry count/duration should be fairly low.
2.) batch processes (non-interactive) where the retry count/duration should be as high as possible to help work around 429's other network connectivity issues. (note: too high is also a problem as the request could be waiting too long, and thus take a long time to fail, if the connection issues are not recoverable)

**Comment by arvindkrishnakumar-okta** [comment]
This is fixed.
