### ISSUE TITLE
Support for partial updates on user profile

### ISSUE THREAD

**Issue by davidmortiz** [okta/okta-sdk-java#311]
Sorry if this is already in the SDK but for the life of me I couldn't find it.  It'd be nice if we had support for this endpoint (https://developer.okta.com/docs/reference/api/users/#update-profile) in the SDK so we could have PATCH-like semantics for profile updates.  We're trying to migrate an internal API to use OKTA as a backend and different endpoints and this would be a huge help.

Thanks!

**Comment by bdemers** [comment]
This is something we have been talking about adding.  That said, in the SDK the plan is to make it transparent when `update()` is called.  

For example, the pseudo code:
```java
User user = client.getUser("joe");
user.set...
user.set...
user.update();
```

Would look the same way if we started using PATCH (the update method would just use PATCH instead of PUT).

I'm guessing that isn't what you are asking about?

**Comment by davidmortiz** [comment]
Sort of, but not exactly.  We're trying to avoid situations where we have to do a read before writing. 

We're moving some backend APIs in our system to use OKTA and the problem is different APIs are used to update different parts of the profile.  i.e. we have one endpoint to change the username and one endpoint to update parts of the profile.

A test case would look something like this:
```java
User u = client.getUser("dave");
assertEquals("Dave", u.getFirstName());
assertEquals("Ortiz", u.getLastName());
assertEquals("dave@nullmailer.com", u.getEmail());

User update = new User();
update.setFirstName("David_Not_Dave");

// This shoud *only* update the firstName and the lastName fields
// ignore the really
client.updateUserPartial("dave", u);

User u = client.getUser("dave");
assertEquals("David_Not_Dave", u.getFirstName());
assertEquals("Ortiz", u.getLastName());
assertEquals("dave@nullmailer.com", u.getEmail());
```

**Comment by bdemers** [comment]
Ahh, I see, that helps.

At the moment we don't support this directly.  As a workaround you could use this technique:
https://github.com/okta/okta-sdk-java#call-other-api-endpoints

and do something like:

```java
User result = client.http()
    .setBody(client.instaniate(User.class)
                       .setFirstName("David_Not_Dave))
    .post("/api/v1/users/<some-id>", User.class);
```
(from memory, so forgive any typos).
This will create a request in the format expected by: https://developer.okta.com/docs/reference/api/users/#update-profile

Keep us posted!

**Comment by bdemers** [comment]
I just tried to reproduce this and couldn't.  I wrote a simple test (in groovy):

```groovy
    @Test
    void quickCacheTest() {

        Client client = Clients.builder().build()

        User myUser = UserBuilder.instance()
            .setEmail("Joe.Coder-"+ UUID.randomUUID() + "@example.com")
            .setFirstName("Joe")
            .setLastName("Code")
            .buildAndCreate(client)

        // User should be cached already, but mimic a typical GET request
        myUser = client.getUser(myUser.getId())
        
        // create a new user to use for the partial update
        User partialUser = client.instantiate(User.class)
        partialUser.getProfile().setFirstName("NotJoe")

        // now update the user with client.http()
        client.http()
            .setBody(partialUser)
            .post(myUser.getResourceHref(), User.class)

        // now call a GET should be a cache hit
        User result = client.getUser(myUser.getId())
        assertThat(result.getProfile().getFirstName(), is("NotJoe"))
    }
```

@davidmortiz any chance you can create a simple repro case?

NOTE: you can also enable logging for `com.okta.sdk.impl.ds.cache.DefaultResourceCacheStrategy` and it will show cache hits as well

Keep us posted!

**Comment by arvindkrishnakumar-okta** [comment]
Closing this old issue now, feel free to reopen if it needs attention/discussion still.
