### ISSUE TITLE
Pagination of users during list or search

### ISSUE THREAD

**Issue by mdisabatino** [okta/okta-sdk-java#318]
I have to implement a paged user search on OKTA.
I tried it in different ways but the result is always the same (always all users):
- client.getDataStore().getResource("/api/v1/users?limit=2", UserList.class)
- client.http().addQueryParameter("limit", "2").get("/api/v1/users", UserList.class);

I tried via curl and I'm able to paginate the result:
curl -v -X GET "https://dev-xxxxxxxx.okta.com/api/v1/users?limit=2" -H  "accept: application/json" -H  "Authorization: SSWS XXXXXXXXXXXXXXXXXXXXXXXXX"

Am I doing something wrong or is there a issue?

**Comment by bdemers** [comment]
Hey @mdisabatino,
Paging is handled automatically by the SDK, take a look at: https://github.com/okta/okta-sdk-java#paging

(if you are testing with cURL make sure you enable the verbose output, the next page URLs are in the headers)

Keep us posted!
