### ISSUE TITLE
Latest SDK pulled down in github unstable

### ISSUE THREAD

**Issue by niuhuskies91** [okta/okta-sdk-java#323]

**Comment by niuhuskies91** [comment]
I just downloaded the latest JDK (we are on 0.0.4). I am getting compiler errors on the okta-sdk-integration-tests. Is there a stable version in artifactory I can pull down?

**Comment by bdemers** [comment]
@niuhuskies91, I'm guessing you found it, but all our packages are up on Maven Central:
https://search.maven.org/search?q=okta

I'd encourage you to update to the latest SDK version though, see the [Release Status](https://github.com/okta/okta-sdk-java#release-status).

If you are trying to build `master` from source and you are running into issues, please open another issue and let us know!
