### ISSUE TITLE
PUSH factor is still retrievable by calling User.listFactors() when user has removed "Okta Verify" from okta website

### ISSUE THREAD

**Issue by herospYL** [okta/okta-sdk-java#326]
This is initially reported with Okta Help Center, the technical support engineer has suggested me report an issue here. The case is: https://support.okta.com/help/s/case/5001Y00001JMVabQAH/remove-okta-verify-mfa-in-okta-website-settings-does-not-remove-okta-verify-push-factor

Okta Version 2019.10.1 
Okta Verify App Version 4.2.1
okta-sdk-java Version 1.5.4

 **Steps to reproduce:** 
1. Prepare a user that has Okta Verify selected as MFA and the PUSH factor is also enrolled.
2. On Okta website, log in as the user and REMOVE the Okta Verify (see the image below). 
3. Make sure Okta Verify app stay the same, (DO NOT remove the entry used by the website above)

Now, User.listFactors() is no longer able to get the TOKEN_SOFTWARE_TOTP factor, but it is still able to get the PUSH factor. Furthermore, this PUSH factor is also able to issue a challenge, and user is able to receive that PUSH notification on their Okta Verify app and approve the verification.

**Expect:**
After removing the Okta Verify MFA from Okta website, both TOKEN_SOFTWARE_TOTP and PUSH factor is un-enrolled and not be able to be retrieved back from User.listFactors()

![image](https://user-images.githubusercontent.com/23085238/67701913-3238df80-f987-11e9-9b04-2107b70dcc66.png)

**Comment by herospYL** [comment]
Hi,

I'm trying to follow up with this issue. Please let me know if I need to provide anything else. 

Liang

**Comment by bdemers** [comment]
Hey @herospYL,
I'm actually trying to send this one back to support.

I do want to ask you a couple of follow up questions.

You mentioned that to reproduce the issue you created a user that has a PUSH notification factor. But you didn't mention you added a TOTP factor.  Can you confirm you added both those factors ?  From the image, you added it looks like the TOTP factor (Google Authenticator) was NOT configured

**Comment by herospYL** [comment]
Hi @bdemers 

The user is enrolled with FactorType.TOKEN_SOFTWARE_TOTP and FactorType.PUSH. However, the FactorType.TOKEN_SOFTWARE_TOTP is linked to Okta Verify app, not the Google Authenticator. When removing Okta Verify option, FactorType.TOKEN_SOFTWARE_TOTP is removed, but FactorType.PUSH is not.

Hope I made it clear.

**Comment by bdemers** [comment]
OK, almost there! Which calls did you make with the SDK and which calls did you use the Okta Admin Console?

**Comment by herospYL** [comment]
First of all, the image I attached above is not the Okta Admin Console, it is the user's setting page (with relative URL path /enduser/settings).

If you need to know, this is our MFA policy in the Okta Admin Console:
![image](https://user-images.githubusercontent.com/23085238/68154235-126c6300-ff15-11e9-8ed9-a5be976451bb.png)


Then, one user's MFA enrollment is done through logging into Okta website at the first time. Remove "Okta Verify" is done on the user's setting page (not by removing from the policy on the Okta Admin Console).

Listing factors is done with SDK, like this:
`FactorList factorList = oktaUser.listFactors();`

**Comment by bdemers** [comment]
Sorry, I miss-typed, I really meant what actions were done with the SDK and which were done through a UI.

Is the only action done with the SDK the `listFactors()` call (or other read operations)

**Comment by bdemers** [comment]
@herospYL gotcha! that is very helpful!

**Comment by bdemers** [comment]
Hey @herospYL 

Sorry to bounce you around, but send an email to `developers@okta.com`, include the link to this issue and we will get it routed to the correct place in support (I just talked to them).

Keep me posted!

**Comment by herospYL** [comment]
@bdemers Thank you for your help.

**Comment by herospYL** [comment]
@bdemers I think this issue has been fixed on our environment. However, I did not receive any email or message from the support engineer. This is based on our tests.

**Comment by bdemers** [comment]
@herospYL thanks for following up!!
