### ISSUE TITLE
Enroll Sms Factor to user- Clarification

### ISSUE THREAD

**Issue by nandhusriram** [okta/okta-sdk-java#327]
I have MFA turned on with SMS authentication ,  I did  follow the example provided in the wiki  to create an user and enroll the user to sms factor.   For some reason its not  doing the MFA with sms, sample code is here.

```java
User user = UserBuilder.instance()
                .setEmail("test@test.com")
                .setFirstName("Test")
                .setLastName("TestLN")
                .setMobilePhone("1111111111")
              
                .setActive(false)
                .buildAndCreate(oktaClient);

      
        SmsFactor smsFactor = oktaClient.instantiate(SmsFactor.class);
        Factor aDefault = user.addFactor(smsFactor, false, "default");
```

I am pretty sure I missing something  a step or something along those lines.

OKTA SDK - 1.5.4

Thanks

**Comment by bdemers** [comment]
Have you tried using `user.addFactor(smsFactor)` ?

**Comment by nandhusriram** [comment]
@bdemers I can try that ,I saw that method was deprecated, hence I tried the other one.

**Comment by arvindkrishnakumar-okta** [comment]
@nandhusriram Just wanted to update here that we just pushed out a major release (version 2.0.0) of this SDK.

With this major release, you will need to use `SmsUserFactor` instead of `SmsFactor`. Also, you will need to use `enrollFactor` instead of `addFactor`.

```java
User user = UserBuilder.instance()
                .setEmail("test@test.com")
                .setFirstName("Test")
                .setLastName("TestLN")
                .setPassword("somepassword".toCharArray())
                .setActive(true)
                .buildAndCreate(oktaClient);

SmsUserFactor smsUserFactor = oktaClient.instantiate(SmsUserFactor)
smsUserFactor.getProfile().setPhoneNumber(smsTestNumber)
user.enrollFactor(smsUserFactor)
```

Feel free to reopen this issue should you have any followup questions.
