### ISSUE TITLE
Implement caching for list/collection resources

### ISSUE THREAD

**Issue by toefel18** [okta/okta-sdk-java#328]
When I instantiate a Client and set a cache with TTL of 2 minutes. Every call still goes through, possibly affecting our rate limits. 

Client instantation:
```java
 return Clients.builder()
        .setOrgUrl(orgBaseUrl)
        .setClientCredentials(new TokenClientCredentials(oktaApiToken))
        .setCacheManager(
            Caches.newCacheManager()
                .withDefaultTimeToLive(2, TimeUnit.MINUTES)
                .withDefaultTimeToIdle(2, TimeUnit.MINUTES)
                .build())
        .build();
```

Code that calls the client:
```java
oktaClient.getApplication(cspApplicationId).listApplicationUsers()

// here I expect application users to be returned from a cache, that are automatically refreshed within 2 minutes. 
oktaClient.getApplication(cspApplicationId).listApplicationUsers()
```

However when I curl, I see that our rate limit has dropped, and therefore calls have been made.

Any tips?

**Comment by hollanderbart** [comment]
We are also experiencing this issue. Can someone look into this?

**Comment by bdemers** [comment]
Hey @toefel18 !

The SDK does NOT currently cache collections, so for you example the Application would be cached, but the user list would NOT be. 

This is something we have talked about changing, but it is more complex then caching individual items.

**Comment by toefel18** [comment]
@bdemers thanks. Until any updates follow I will implement caching myself if needed.

**Comment by bdemers** [comment]
@toefel18 keep us posted!
