### ISSUE TITLE
Clarification -- Factor Enrollment

### ISSUE THREAD

**Issue by nandhusriram** [okta/okta-sdk-java#332]
I have setup the MFA policy for the  group , I am trying  create a new user , add it to the group and enroll the user to a Factor .I am getting the following error.

Api validation failed: factorEnrollRequest - Factor not allowed for the user based on the Multifactor policy.

  User user = UserBuilder.instance()
                .setEmail(registrationUser.getEmail())
                .setFirstName(registrationUser.getFirstName())
                .setLastName(registrationUser.getLastName())
                .setMobilePhone(registrationUser.getMobilePhone())
                .setGroups(groupId)
                .buildAndCreate(oktaClient);

        SmsFactor smsFactor = oktaClient.instantiate(SmsFactor.class);
        smsFactor.getProfile().setPhoneNumber(registrationUser.getMobilePhone());
        user.addFactor(smsFactor, false,"default",null,true);

Am I missing anything with this ?

**Comment by kaarthiknva** [comment]
Did you get any response? Were you able to configure factor for the user?

**Comment by bdemers** [comment]
Sorry we missed this one.

My guess is you need to enable the factors in you admin console before you can assign them to a user:

Log into your Okta admin console select: Security -> Multifactor -> Factor Types

**Comment by arvindkrishnakumar-okta** [comment]
Closing this old issue now, feel free to reopen if more help/followup is needed.
