### ISSUE TITLE
OSGi Support

### ISSUE THREAD

**Issue by emartinez3** [okta/okta-sdk-java#333]
Hello, 

I am trying to implement this SDK with an OSGi application. I set up the pom.xml file as follows:
I added the dependencies listed. 
I also embedded the dependencies like this:
<Embed-Dependency>
                            okta-sdk-api,
                            okta-sdk-impl,
                            okta-authn-sdk-api,
                            okta-authn-sdk-impl,
                            okta-commons-lang,
                            okta-config-check,
                            okta-sdk-httpclient
                        </Embed-Dependency>
                        <Export-Package>
                            com.okta.sdk.*
                        </Export-Package>

The project compiles successfully but the following error is thrown at runtime:
org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IllegalStateException: Unable to find a 'com.okta.sdk.impl.http.RequestExecutorFactory' implementation on the classpath.  Please ensure you have added the okta-sdk-httpclient.jar file to your runtime classpath.
 
This error occurs when this line is executed:     
 Client client = Clients.builder()
        .setOrgUrl("https://org.okta.com")
        .setClientCredentials(new TokenClientCredentials("apikeystring"))
        .build(); 

I've use the SDK with a springboot app. The app compiles and runs correctly but same setup fails in the OSGi app.

Normally for libraries that are not OSGi compatible, embedding the dependencies works fine. Is there OSGi support for this SDK?

**Comment by bdemers** [comment]
We don't have OSGi support for these libraries.  I'd suggest creating a wrapper project.

That said, supporting JPMS should be relatively easy which might _help_. But I'm not sure it would actually solve the problem.
