### ISSUE TITLE
Resend Activation Email is not supported by client

### ISSUE THREAD

**Issue by muratovi** [okta/okta-sdk-java#334]
`Reactivate` endpoint is not supported by client: 
https://developer.okta.com/docs/reference/api/users/#reactivate-user

{url}/api/v1/users/{userId}/lifecycle/reactivate?sendEmail=true

**Comment by bdemers** [comment]
It's on the TODO list! thanks @muratovi!

**Comment by rjft** [comment]
Bumping to see if there has been any progress on this as it would be super useful!

**Comment by bdemers** [comment]
@rjft not yet, but you can make calls to any and point using this technique:
https://github.com/okta/okta-sdk-java#call-other-api-endpoints

Calling this endpoint should be very similar to that example, just don't call `setBody()`

**Comment by arvindkrishnakumar-okta** [comment]
@rjft Thanks for raising this. We just released a major version `2.0.0` of the SDK. 

With this upgrade, you should be able to use `reactivate` on `User` object.
