### ISSUE TITLE
UserBuilder in latest release (1.5.4) does not yet support setting password hashes.

### ISSUE THREAD

**Issue by johnhurst-redenergy** [okta/okta-sdk-java#338]
The code for UserBuilder#setBcryptPasswordHash() etc was added in June 2019.

But com:okta.sdk:okta-sdk-impl:1.5.4, released Aug 2019, does not seem to include those changes.

Is this intentional? Any plans for a new release soon?

Thanks.

**Comment by bdemers** [comment]
We will have a release out soon.

Have you tried out the latest snapshot version?

**Comment by johnhurst-redenergy** [comment]
Thanks for the response. I copy/pasted the DefaultUserBuilder code for my immediate requirement, but I'll check out the snapshot if I need more. 

I was a bit curious why the June code change was not in the August release, but I guess that was intentional.

Cheers.
