### ISSUE TITLE
TotpFactor creation 

### ISSUE THREAD

**Issue by dhirajsable** [okta/okta-sdk-java#349]
I am trying to create a new factor TotpFactor. I am using following code :- 

```java
TotpFactor totpFactor = oktaMfaClient.instantiate(TotpFactor.class);
            totpFactor.setFactorType(FactorType.TOKEN_SOFTWARE_TOTP);
            totpFactor.setProvider(FactorProvider.GOOGLE);
            oktaUser.addFactor(totpFactor);
```

After adding totpFactor to oktaUser, I am not getting values for oktaUser.getEmbedded(); it is null but if I use API through Postman then I am getting "_embedded":  with link to QR code.

Please let me know if missed any thing in java code.

**Comment by bdemers** [comment]
@dhirajsable 
Take a look at this example (it's in groovy, but it should be almost identical in Java)
https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/FactorsIT.groovy#L154-L158

**Comment by dhirajsable** [comment]
If you look at my code I did same thing
TotpFactor totpFactor = oktaMfaClient.instantiate(TotpFactor.class);
            totpFactor.setFactorType(FactorType.TOKEN_SOFTWARE_TOTP);
            totpFactor.setProvider(FactorProvider.GOOGLE);
            oktaUser.addFactor(totpFactor);

But oktaUser is missing value for oktaUser.getEmbedded() and its null. 

I did debug the code in Okta jar following methods has "_embedded" in body but I think wrapper is not working 

/**
    * Enroll Factor
    * Enrolls a user with a supported [factor](#list-factors-to-enroll)
    * @param body Factor (required)
    * @return Factor
    */
    @Override
    @javax.annotation.Generated(
          value    = "com.okta.swagger.codegen.OktaJavaClientImplCodegen",
          date     = "2019-08-02T11:58:53.988-04:00",
          comments = "POST - /api/v1/users/{userId}/factors")
    public Factor addFactor(Factor body) {

        String userId = getId();

        notNull(body, "'body' is required and cannot be null.");
        hasText(userId, "'userId' is required and cannot be null or empty.");
        QueryString queryArgs = new QueryString();


        String href = QueryString.buildHref("/api/v1/users/" + userId + "/factors", queryArgs);
        getDataStore().create(
            href,
            body,
            this,
            Factor.class
        );
        return body;

     }

but after returning the body oktaUser.getEmbedded(); is null so I can't get the QR code Image URL.

**Comment by bdemers** [comment]
@dhirajsable are you calling `oktaUser,getEmbedded()` or `totpFactor .getEmbedded()`?  It should be the later.

**Comment by dhirajsable** [comment]
I am calling oktaUser.getEmbedded() and I am getting this as a null.

**Comment by bdemers** [comment]
Looks like that is the issue ;) 
Use totpFactor.getEmbedded() instead

**Comment by dhirajsable** [comment]
But as per the documentation, I should get QR code link by using oktaUser.getEmbedded(). The API documentation doesn't have such details.

**Comment by bdemers** [comment]
@dhirajsable which documentation are you referring to?
