### ISSUE TITLE
Milliseconds timeout values are treated as seconds

### ISSUE THREAD

**Issue by Oduig** [okta/okta-sdk-java#356]
The documentation on Okta configuration states that timeout values are passed in milliseconds.
This is `ClientBuilder.java`:

```
    /**
     * Sets both the timeout until a connection is established and the socket timeout (i.e. a maximum period of inactivity
     * between two consecutive data packets).  A timeout value of zero is interpreted as an infinite timeout.
     *
     * @param timeout connection and socket timeout in milliseconds
     * @return the ClientBuilder instance for method chaining
     */
    ClientBuilder setConnectionTimeout(int timeout);
```

However, the implementation uses `HttpClientRequestExecutor` which multiplies the supposed value in milliseconds by 1000.

```
    int connectionTimeoutAsMilliseconds = connectionTimeout * 1000;
    RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(connectionTimeoutAsMilliseconds).setSocketTimeout(connectionTimeoutAsMilliseconds).build();
```

The same goes for the retry timeout, which is multiplied by 1000 in `RetryRequestExecutor`.

```
        if (clientConfiguration.getRetryMaxElapsed() >= 0) {
            maxElapsedMillis = clientConfiguration.getRetryMaxElapsed() * 1000;
        }
```

It's hard to say what the fix should be: adjusting documentation on `ClientBuilder` or fixing the multiplier in the implementations. Either way could break existing implementations or expectations, but if the desire is backwards compatibility, the best way forward would be updating documentation to reflect current behavior.

**Comment by bdemers** [comment]
Thanks @Oduig !

I just checked the OkHttp impl too, it is seconds.

We will update the docs.

In the future, we will likely move to `Duration`s to avoid this type of problem altogether.
i.e.

```java
ClientBuilder setConnectionTimeout(Duration timeout);
```

and used something like:

```java
clientBuilder.setConnectionTimeout(Duratiion.ofSeconds(10));
```
