### ISSUE TITLE
OpenAPI spec has incorrect type for log events

### ISSUE THREAD

**Issue by johanbrandhorst** [okta/okta-sdk-java#358]
Hi,

I'm raising this on the back of the same bug in the Go SDK: https://github.com/okta/okta-sdk-golang/issues/65. It appears the OpenAPI specs used to generated the clients have not been updated to support the current types of the LogEvent API response.

The offending lines: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L3699-L3708.

I'd be happy to contribute a fix for this of all it is is updating the api spec.

**Comment by robertjd** [comment]
Thanks @johanbrandhorst , see my note in the linked issue - we'll be getting this fixed soon.  Golang is in RC state with a new major version, Java will be following next.

**Comment by arvindkrishnakumar-okta** [comment]
@johanbrandhorst Thanks for raising this! 

We just released v2.0.0 of Java SDK which fixes this issue.
