### ISSUE TITLE
Load testing on Okta resend Api

### ISSUE THREAD

**Issue by dhirajsable** [okta/okta-sdk-java#363]
I have executed around 5000 requests for ResendCode api to okta and I have receive around 3800 SMS codes to my number. I have made all requests in a window of 20 seconds.

Is this expected response from Okta? My expectations was that okra will send 429 in response.

**Comment by bdemers** [comment]
Hi @dhirajsable, 
Rate limits depend on a lot of things we would probably need exact numbers you are seeing and some information about your Okta Org. 
I would suggest you reach out to Okta support: https://support.okta.com

This SDK does retry requests though, for more information see: https://github.com/okta/okta-sdk-java#connection-retry--rate-limiting

**Comment by dhirajsable** [comment]
Thank you for updates. Sure I will do that.
