### ISSUE TITLE
Should/How to use OktaResourceHrefResolver?

### ISSUE THREAD

**Issue by oferrigni** [okta/okta-sdk-java#367]
In a single jvm setup, I was hoping to use the OktaResourceHrefResolver as it suggests we could get some benefits caching requests for things like a group or a user.

This conclusion was based on documentation [here](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/cache/Caches.html).

However, I cannot figure out a way to configure the sdk to use that resolver. In fact, it appears it specifically disallowed as the default implementation directly allocates a new HalResourceHrefResolver [here](https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/java/com/okta/sdk/impl/ds/DefaultDataStore.java#L122).

At runtime, in a test where I had replaced the cacheStrategy [here](https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/java/com/okta/sdk/impl/ds/DefaultDataStore.java#L122) with a `new DefaultResourceCacheStrategy(new OktaResourceHrefResolver(), cacheResolver)`, I found every request had a cache miss due to the cache key used to store the cache value not including the base url. This leads me to believe I am missing something with regard to this class and its usage.

Any advice would be helpful.

All the best.

**Comment by bdemers** [comment]
Hey @oferrigni !

Just to fill in some gaps, this project only guarantees semver on the `api` module. And we recommend only compiling against that (and using the `impl` module as a runtime dependency).  As such some somethings are not easily exposed.

That said, lets get back to the problem you reported about cache misses, and work backwards from there.  What types of requests are you seeing cache misses on? 



https://github.com/okta/okta-sdk-java#caching

If you are building Spring apps, an need support for multiple nodes, this project can also use Spring Cache: https://github.com/okta/okta-spring-boot#inject-the-okta-java-sdk

**Comment by oferrigni** [comment]
@bdemers Holy smokes, that is one fast response time! Thank you for getting back to me so quickly!!!!

I'm hoping to cache User and Group objects (not their list compatriots). How does one configure the client sdk to use spring caching to cache user and group objects?

**Comment by bdemers** [comment]
@oferrigni sorry, for taking so long this time, can I have partial credit from before 🥺 

I thought we had documented this, but I guess we missed it.
If you use `com.okta.spring:okta-spring-sdk` (and a Spring Cache implementation) then Spring Cache will be used automatically by the SDK.

https://github.com/okta/okta-spring-boot#inject-the-okta-java-sdk

**Comment by bdemers** [comment]
I'm going to close this issue, but feel free to comment if you have other questions (and I'll reopen it)
