### ISSUE TITLE
Custom Profile Attributes/Variables are NOT present in UserProfile or GroupProfile

### ISSUE THREAD

**Issue by delkant** [okta/okta-sdk-java#375]
How can I get custom variables? I couldn't find any documentation on it and I have been debugging the SDK(1.5.4) but the custom attributes are not present anywhere.

This is what I have: 
<img width="998" alt="Screen Shot 2020-05-07 at 10 12 22" src="https://user-images.githubusercontent.com/1325846/81305789-bf52a480-904c-11ea-9f99-fdbb3da59a14.png">

<img width="835" alt="Screen Shot 2020-05-07 at 10 26 22" src="https://user-images.githubusercontent.com/1325846/81306386-69323100-904d-11ea-8210-571695316e31.png">

I just realized there is a new release 1.6.0. I will test that out now.

**Comment by bdemers** [comment]
Take a look at `user.getProfile().get(...)`
(there are a few utility methods like `getString` to make it easy to get the correct type)

**Comment by bdemers** [comment]
@delkant if you just curl/postman the user you are looking for do you see a value under the `profile` node?

**Comment by delkant** [comment]
No, I don't see any custom attributes or variables. Not custom att for group profiles either.

**Comment by delkant** [comment]
if I hit the /api/v1/apps/{ClientId}/groups I am able to see the custom variables listed as part of the App Profile. Closing this issue since it seems to be related to a bad configuration in my app. Thanks @bdemers
