### ISSUE TITLE
Okta proxy settings

### ISSUE THREAD

**Issue by peeyushsurolia** [okta/okta-sdk-java#378]
In one of our production environment, we are using okta-sdk version 0.0.4 where we need to configure application for proxy support.

We are using the standard JAVA proxy system properties i.e. https.proxyHost and https.proxyPort
but those are not working fine with spring boot application

I checked a documentation is updated in version 1.2.0 to handle proxy support , So can you please confirm that 0.0.4 version does not support proxy settings.

**Comment by bdemers** [comment]
IIRC 0.0.4 uses HttpClient, setting the `https.proxy*` properties should work (make sure you are setting them as system properties and NOT via a spring config file).

That said, this version is EOL, and I would recommend updating to the latest version.  NOTE the old library and the new library have different package structures so you should be able to use both on the same classpath while migrating from the old to the new.

**Comment by peeyushsurolia** [comment]
Thanks @bdemers , I am currently using Grails 3.X version which is built on top of spring boot, and supplied https.proxy* properties as system properties but didn't worked though latest versions are working fine with below properties

 -Dokta.client.proxy.port=<PORT>,
 -Dokta.client.proxy.host=<HOST>
