### ISSUE TITLE
Factor object missing lastUpdated field

### ISSUE THREAD

**Issue by kevintian** [okta/okta-sdk-java#419]
Hi! I noticed while going through the Factors API that the Factor object included in this SDK seemed to be missing some of the fields specified in the API properties (https://developer.okta.com/docs/reference/api/factors/#factor-properties). I'm interested in using the `lastUpdated` timestamp for my application. Is there any way to access these fields that I'm missing, or do I have to make my own requests in order to get these additional values?

Thanks!

**Comment by arvindkrishnakumar-okta** [comment]
@kevintian Thanks for question! 

You could do a `resource.get("lastUpdated")` on your Factor resource.

**Comment by kevintian** [comment]
Thanks Arvind!
