### ISSUE TITLE
Okta ymal token to env variables

### ISSUE THREAD

**Issue by RanmalN** [okta/okta-sdk-java#428]
I am using okta.ymal to set up okta but i need to make the token of the said YAML to env variable is there a way to do so.

I tried converting it to application properties it did not work

okta.client.connectionTimeout: 30 # seconds
okta.client.orgUrl: "Domain"
okta.client.proxy.port: null
okta.client.proxy.host: null
okta.client.proxy.username: null
okta.client.proxy.password: null
okta.client.token: "Token"
okta.client.requestTimeout: 0 # seconds
okta.client.rateLimit.maxRetries: 4
okta.client.userAgent: "MDMContactManager/1.0"

PS i create the client like below 
 client = Clients.builder().build();

**Comment by bdemers** [comment]
@RanmalN we have a note about this in the README: https://github.com/okta/okta-sdk-java#environment-variables

basically just `toUpper` and replace the `.` with `_`

**NOTE:** `okta.client.userAgent` isn't a valid option though

**Comment by arvindkrishnakumar-okta** [comment]
@RanmalN hope the above comments helped. Feel free to reopen this issue if you have any further questions/followups.
