### ISSUE TITLE
Question: How to specify UserType while creating new user?

### ISSUE THREAD

**Issue by venuduggireddy** [okta/okta-sdk-java#431]
How to specify UserType while creating new user? I do not see an option to assign UserType in UserBuilder similar to addGroup while creating user? Is there any option available within the SDK?

**Comment by arvindkrishnakumar-okta** [comment]
@venuduggireddy Thanks for raising this question!

The `UserBuilder` presently does not have a setter for `UserType`. As a quick solution, you could call `setUserType` method on the created `User` object. 

I will add a PR to include the missing property to the builder.
