### ISSUE TITLE
Add note in README about how to use this SDK with Spring

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#437]

**Comment by SpuTTer** [comment]
Can you get some notes on being able to support spring profiles, either by profile options in Okta.yml or being able to use the properties directly in Application.yml so that Spring profiles are supported.

**Comment by bdemers** [comment]
Hey @SpuTTer, are you looking for anything specific?
https://github.com/okta/okta-spring-boot#inject-the-okta-java-sdk

All of the okta properties should work from anyy Spring configuration source (env var, properties files, yaml, Spring Cloud config extra). All of those mechanisms should allow for Spring profiles too.

However, if you are using a `~/.okta/okta.yaml` this would NOT respect Spring profile configurations. 

Let me know if that helps!

**Comment by SpuTTer** [comment]
Interesting, I had moved the properties from Okta.yml to my Application.yml and it didnt pick it up. It was an easy workaround to just construct the builder params manually using the spring property reference. Would be curious if the standard Okta pathing in application.yaml is indeed working for everyone else, such as:

`okta:
  client:
    connectionTimeout: 30 # seconds
    orgUrl: "https://{yourOktaDomain}" # i.e. https://dev-123456.okta.com
    proxy:
      port: null
      host: null
      username: null
      password: null
    token: yourApiToken
    requestTimeout: 0 # seconds
    rateLimit:
      maxRetries: 4`

**Comment by bdemers** [comment]
This also depends on how you are loading the client.  The Spring properties only work for the client bean that is available from the Spring Boot Starter.  Spring properties are NOT used if you construct a client manually (via `Clients.builder()` for example).

Hopefully, this helps :)
(this is good feedback for us too, as can spend more time clarifying these types of things in our docs)

**Comment by SpuTTer** [comment]
Auh!!

Yes, I was using the builder. So I could have just injected a client and it
would have picked it up? That would be a good refactor, I'll check it out.
Thank you!!

**Comment by bdemers** [comment]
Keep us posted!
