### ISSUE TITLE
Primary authentication with trusted application via Management API

### ISSUE THREAD

**Issue by razvandz** [okta/okta-sdk-java#456]
Hello,

Our team is trying to implement the primary authentication with trusted application flow, as described here in the API docs: https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-trusted-application. 

We tried to use the Java Auth SDK (https://github.com/okta/okta-auth-java) to implement it, but it looks like this SDK does not support authentication via trusted application - the DefaultAuthenticationClientBuilder sets the client credentials resolver as a DisabledClientCredentialsResolver and does not allow setting the authorization mode - compare it to the ClientBuilder from the Management SDK: https://github.com/okta/okta-sdk-java, which does. For security reasons, we would like to avoid using the admin API token, and use the scoped OAuth 2.0 tokens (AuthorizationMode.PRIVATE_KEY).

The question that i wanted to ask is, **since the management sdk supports trusted flow application, is there any way to easily customize the calls inside it in order to achieve a call to the auth api? Or is there any other way to achieve authentication via the management api instead of the auth sdk ?**(which does not support the trusted app flow - we already have an issue created on the auth side here https://github.com/okta/okta-auth-java/issues/77).

Thanks,
Razvan

**Comment by bdemers** [comment]
There are no plans to handle end-user authentication (and the corresponding state machine) with this library.
Let's keep the discussion over on okta/okta-auth-java#77
