### ISSUE TITLE
Ensure request/response are gziped

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#460]
Enable gzipping of requests responses.

Need to set the appropriate headers: `Content-Encoding` and `Accept-Encoding`.
if the response headers contain a gzip (or similar) header, then wrap the response in a GZipOutputStream. (possibly something like a `GzipCompressorInputStream`)

**NOTE:** The client doesn't need to support every type of compression type, just `gzip` is fine

**Comment by VitaliiTytarenko-okta** [comment]
This functionality is already implemented here:
`Accept-Encoding` for requests: https://github.com/okta/okta-commons-java/blob/bd136b6e7d492b47171fec6e83725dd0b160932e/http/httpclient/src/main/java/com/okta/commons/http/httpclient/HttpClientRequestFactory.java#L138
Unzip response body if `Content-Encoding` is present: https://github.com/okta/okta-commons-java/blob/bd136b6e7d492b47171fec6e83725dd0b160932e/http/httpclient/src/main/java/com/okta/commons/http/httpclient/HttpClientRequestExecutor.java#L240
