### ISSUE TITLE
Listing Custom Authorization Server Policy Rules Causes 404 Error

### ISSUE THREAD

**Issue by danaronoff** [okta/okta-sdk-java#466]
Hello.

I am trying to manage an Okta tenant via Java SDK. I am able to create an authorization server and an associated policy for it by applying the policy directly to the authorization server:

```
		AuthorizationServer as = oktaClient.getAuthorizationServer("aus...");
		Policy policy = oktaClient.instantiate(Policy.class);
		policy
			.setType(PolicyType.OAUTH_AUTHORIZATION_POLICY)
			.setStatus(StatusEnum.ACTIVE)
			.setName("Test Policy")
			.setDescription("Test Policy");
		
		//Does Not Work
		//policy = oktaClient.createPolicy(policy);
		
		//Works
		as.createPolicy(policy);
		as.update();
```

Creating a Policy object outside of an Authorization server context does not work (looks like the only policies supported are Sign On and Password Policies).

The issue I am reporting is that when I try to list the policy rules for an Authorization Server policy, I get a 404 error even though the policy I am retrieving is coming via an Authorization Server context:
```
		AuthorizationServer as = oktaClient.getAuthorizationServer("aus...");
		as.listPolicies().forEach(pol -> {
			//Throws a 404 Error
			log.info("Policies: "+pol.listPolicyRules());
		});
```
I am not sure if anything can be done on the SDK side for this or it is a built in API limitation. I will attempt to manage policy rules via an ExtensibleResource for now.

**Comment by arvindkrishnakumar-okta** [comment]
@danaronoff Thanks for your question!

Policy operations must always be done on Authorization Server context (See https://developer.okta.com/docs/reference/api/authorization-servers/#policy-operations) and the behavior you see is expected.  

Reg the 404 error, can you tell me how you are associating policy rule(s) to the created policy?

**Comment by danaronoff** [comment]
Hi @arvindkrishnakumar-okta 

To create the 404 error, I create a policy rule in the User Interface and proceed to call the listPolicyRules() method as outlined above. I believe the SDK is trying to retreive the rule here: https://developer.okta.com/docs/reference/api/policy/#get-policy-rules, but failing because it is an Authorization Server policy.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks @danaronoff . This looks like an issue with the SDK and we will work on getting it fixed.
