### ISSUE TITLE
Client lifecycle and thread-safety documentation

### ISSUE THREAD

**Issue by konrad-garus** [okta/okta-sdk-java#476]
I think some important piece of documentation is missing.

What is the recommended Client lifecycle? Is it OK to create it ahead of time and keep it open for the entire lifetime of my application? Does it need to be closed explicitly?

Is the Client thread-safe? Looking at the Spring module it seems like that is the assumption there, but I cannot find it documented anywhere.

**Comment by bdemers** [comment]
We can add a note to the README/Javadocs, but the short answer is yes.  You can (and should) use the same instance of the `Client`.
This is especially important for things like caching and connection pooling.

**Comment by konrad-garus** [comment]
Great, thanks for the answer. I do think the docs should be updated too.

**Comment by arvindkrishnakumar-okta** [comment]
documentation has been updated.
