### ISSUE TITLE
Support user based access tokens

### ISSUE THREAD

**Issue by Prashanth-Ambalavanan** [okta/okta-sdk-java#477]
Team,

Client builder application only supports client credentials accessToken using private key for OAuth for Okta. Can we bootstrap user accessToken obtained using  auth code flow/spa.

Client client = Clients.builder()

**Comment by bdemers** [comment]
Currently no, 
But something like #339 would allow for this.

**Comment by bdemers** [comment]
@Prashanth-Ambalavanan this is something i'd like to see though, do you have a specific use case in mind (that might help us prioritize something like this)

**Comment by prashanthambalavanan-okta** [comment]
@bdemers - Customer has a front end app that gets user access token with specific Okta scopes. Since they do not have a gateway they are planning to leverage Okta to handle the scope validation. It would be a quick win if the SDK can support to bootstrap user accessToken.

**Comment by bdemers** [comment]
Fixed by: #339
