### ISSUE TITLE
Include X-Forwarded-For Header in Push Factor Verification Request

### ISSUE THREAD

**Issue by kevintian** [okta/okta-sdk-java#478]
I'd like to be able to pass the client's IP address to the verification request for a push factor so that the location displayed on the push notification is correct. If possible, it'd also be nice to be able to include the user's device (user-agent) as well.

Is there a way to do this using the API?

**Comment by arvindkrishnakumar-okta** [comment]
I don't think this is possible with the Java SDK. I'll double check if this is supported on the Okta core APIs though.

**Comment by bdemers** [comment]
@kevintian Take a look at: https://github.com/okta/okta-sdk-java#call-other-api-endpoints
You can use the typed Factor classes (you don't need to use the generic `ExtensibleResource`)

Does that help?

**Comment by kevintian** [comment]
Hi @bdemers, Thanks for your response! I think that suggestion fits my use case. Really appreciate the help!
