### ISSUE TITLE
Custom SAML 2.0 Application, mismatch fields between Okta API reference and okta-sdk-java API doc

### ISSUE THREAD

**Issue by chloey863** [okta/okta-sdk-java#487]
In creating a custom SAML 2.0 Application via okta-sdk-java and Okta API reference, there might be a mismatch/missing field:
1. "allowMultipleAcsEndpoints" is a mandatory field according to the [Okta API reference](https://developer.okta.com/docs/reference/api/apps/#add-custom-saml-application), but in the [SamlApplication Interface](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/application/SamlApplication.html), I couldn't find a setter/getter for this field.

**Comment by chloey863** [comment]
> In creating a custom SAML 2.0 Application via okta-sdk-java and Okta API reference, there might be a mismatch/missing field:
> 
> 1. "allowMultipleAcsEndpoints" is a mandatory field according to the [Okta API reference](https://developer.okta.com/docs/reference/api/apps/#add-custom-saml-application), but in the [SamlApplication Interface](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/application/SamlApplication.html), I couldn't find a setter/getter for this field.

**Comment by arvindkrishnakumar-okta** [comment]
@chloey863 Thanks for raising this! sounds like we're missing this from the openapi spec. I can chat with the team and get back to you on this.

**Comment by arvindkrishnakumar-okta** [comment]
@chloey863 Thanks for raising this. This property will be included in the next major release (v3) of the SDK which is presently a WIP. 

cc: @sergiishamrai-okta
