### ISSUE TITLE
WebAuthN Factor Enrollment returns Invalid Factor error

### ISSUE THREAD

**Issue by kevintian** [okta/okta-sdk-java#496]
I recently upgraded to the v2.0.0 release because I wanted to use the new included Webauthn functionality, but am running into some issues. When I try to enroll a Webauthn factor normally like so:

```java
final WebAuthnUserFactor webAuthnFactor = client.instantiate(WebAuthnUserFactor.class);
final UserFactor factorResponse = user.enrollFactor(webAuthnFactor);
```
I get an an Okta API error `E0000001: Api validation failed: factorEnrollRequest`. The error summary provided is `Invalid Factor`.

I also tried calling the endpoint manually using the generic syntax, but run into an issue because it's unable to serialize "FIDO" as a `FactorProvider` (it seems that FIDO was removed from the FactorProvider enum in the v2.0.0 release?)
```java
final ExtensibleResource factor = client.instantiate(ExtensibleResource.class);
factor.put("factorType", "webauthn");
factor.put("provider", "FIDO");

final UserFactor factorResponse =
    client.http()
        .setBody(factor)
        .post(String.format("/api/v1/users/%s/factors", user.getId()), UserFactor.class);
```

Error:
`java.lang.IllegalArgumentException: No enum constant com.okta.sdk.resource.user.factor.FactorProvider.FIDO`

**I suspect that both issues are caused by the fact that "FIDO" is no longer included in the `FactorProvider` enum** since manually hitting the /factors endpoint in Postman with 

```javascript
{
    factorType: "webauthn"
    provider: "OKTA"/"GOOGLE"/any other provider that is not "FIDO"
}
```

returns the same `E0000001: Api validation failed: factorEnrollRequest, Invalid Factor` error message.

**Comment by arvindkrishnakumar-okta** [comment]
@kevintian like you mentioned, we have removed `FIDO` from the `FactorProvider` list since `v2.0.0`. So, the error message you posted makes sense. I would check with the team on the background of removing it and post updates here.

**Comment by kevintian** [comment]
@arvindkrishnakumar-okta Thanks for the follow-up! If i'm understanding it correctly, v2.0.0 also introduced WebAuthn factor enrollment, correct? I'm a bit confused on how `FIDO` could be removed from the `FactorProvider` list without breaking WebAuthn functionality. As far as I can tell, Okta's Factors API is still expecting a provider type of `FIDO` for Webauthn enrollment requests.

**Comment by arvindkrishnakumar-okta** [comment]
@kevintian Here is the list of supported factors: https://developer.okta.com/docs/reference/api/factors/#factor-type 
and here is the list of supported providers: https://developer.okta.com/docs/reference/api/factors/#provider-type

I do not see `FIDO` to be supported provider type,

**Comment by kevintian** [comment]
@arvindkrishnakumar-okta I didn't see the Webauthn factor type as an available factor via the SDK prior to v2.0.0 - looking at the old docs for v1.6.0 (https://developer.okta.com/okta-sdk-java/) there is no WebAuthn class included here. 

Also, FIDO is specified as the required provider type in the webauthn enrollment request here: https://developer.okta.com/docs/reference/api/factors/#enroll-webauthn-factor

I can also confirm via Postman that the /factors endpoint is still expecting "FIDO" as a provider when trying to enroll in the webauthn factor type

**Comment by arvindkrishnakumar-okta** [comment]
@kevintian Thanks for checking! It appears that the documentation at https://developer.okta.com/docs/reference/api/factors/#provider-type needs to be updated. Also, we need to update our OpenAPI spec and regenerate the Java SDK models to include support for `FIDO` factor type. Thanks for uncovering this bug.

**Comment by arvindkrishnakumar-okta** [comment]
Fix merged to master branch.
