### ISSUE TITLE
User reactivation after provisioning using the java sdk

### ISSUE THREAD

**Issue by razvandz** [okta/okta-sdk-java#510]
Hey guys,

Is there any way to reactivate a deprovisioned user using the sdk? it seems like the methods "activate" and "reactivate" only work on different statuses except deprovisioned.

Thanks,
Razvan

**Comment by arvindkrishnakumar-okta** [comment]
@razvandz Thanks for your question. `reactivate` API works only on users with `PROVISIONED` status (ref https://developer.okta.com/docs/reference/api/users/#reactivate-user).

**Comment by razvandz** [comment]
so is there any way to get someone from a DEPROVISIONED status to a PROVISIONED one? Or is that only doable via okta UI?

**Comment by arvindkrishnakumar-okta** [comment]
There is no conceivable direct programmatic way of transitioning a user from `DEPROVISIONED` to `PROVISIONED` state (state diagram - https://developer.okta.com/docs/reference/api/users/#user-status). UI can be used to achieve the same with admin role.

**Comment by arvindkrishnakumar-okta** [comment]
Closing this, feel free to reopen if there are any followups.
