### ISSUE TITLE
Client is not able to interact with XML response based APIs (eg SAML meta data API)

### ISSUE THREAD

**Issue by ankitrajsingh** [okta/okta-sdk-java#516]
https://github.com/okta/okta-sdk-java/blob/8ef2ac4aaafb189fe37196f4bd2d3c44179e22f1/impl/src/main/java/com/okta/sdk/impl/ds/DefaultDataStore.java#L480

My requirement is to fetch app's SAML metadata ([API Ref](https://developer.okta.com/docs/reference/api/apps/#preview-saml-metadata-for-application)), while hitting the API through client along with correct Accept header ("application/xml"), the client forcibly overrides it to "application/json" and the request result in BAD REQUEST error code from the API mentioning that the response format can't be "application/json", it should be "application/xml" instead.

Please let me know how can the client be enabled/configured to interact with XML based okta apis.

**Comment by sergiishamrai-okta** [comment]
Thanks for the request, @ankitrajsingh 

Can you elaborate on what specifically you are trying to do?

**Comment by ankitrajsingh** [comment]
I am trying to link orgs via Org2Org app, for that I need to transfer SAML credentials of Org2Org App in Spoke(say Okta OrgA) to the corresponding IDP of the Hub (say Okta OrgB).

The said API provides the SAML credentials demanded by the IDP i.e entityId, X509Cert and SSO links.

**Comment by sergiishamrai-okta** [comment]
Thanks for the report @ankitrajsingh.
This is definitely a bug and we're going to put it on our roadmap.  Follow this issue for updates.

**Comment by arvindkrishnakumar-okta** [comment]
Internal ref: OKTA-361894

**Comment by ankitrajsingh** [comment]
Hi @sergiishamrai-okta , as a temporary work around to this I am looking to define our own client for this specific api. Anyway we can carry token handover from the Okta client to our own custom client ? Any method/mechanism which Okta client exposes for the same would be great.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Not sure I understand what you mean by "token handover". Can you elaborate on what you need?

**Comment by ankitrajsingh** [comment]
@arvindkrishnakumar-okta , I am talking about Oauth tokens which gets generated via client id and private key. Okta client internally takes care of generating the auth token with this information.

But as the Okta Client can't hit the SAML api due header issue, let's say i define my own HttpClient(eg. RestTemplate).
Now this client needs the auth token passed in headers while hitting SAML api.

I plan to keep token lifecycle with Okta client itself, thereby issuing token to my own http client from the Okta client.

Pseudo Code of what I am trying to achieve:

```
OktaClient oktaClient = new OktaClient(client_id, private_key);
CustomHttpClient customClient = new CustomHttpClient();
customClient.setAuthTokenHeader(oktaClient.getToken()).hit(SAML_API)
```

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Thanks for the info. The Token retrieval and lifecycle is managed by Okta client internally like you correctly noted. The token retrieval part is not exposed to the caller by design, so you cannot directly get the OAuth2 access token from the client. Nevertheless, you could do something like https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/java/com/okta/sdk/impl/oauth2/AccessTokenRetrieverServiceImpl.java#L85-L106 and get the access token to use in your custom client.

**Comment by ankitrajsingh** [comment]
@arvindkrishnakumar-okta , Have already gone through this class. Based on my understanding of it, this class generates OAuth2TokenClient(subclass of BaseClient) and OktaClient is based on much capable DefaultClient(another subclass of BaseClient), so this class won't help us keep a central OktaClient.

Going through this class, we will have to generate both types of Okta Clients.

Anyway to get the same done via DefaultClient?

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh exposing access token retrieval method directly from DefaultClient is a separate item that can be considered (as feature request) in future. For the scope of the original issue that was mentioned here (`Accept` header issue with Okta client), we will push a fix soon.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh On thinking more about the ask here, SAML meta data is public and you don't actually need to use this Java SDK to read the SAML meta data. Also, SAML meta data access does not need any private key or client authentication details. You can simply fetch the metadata using an unauthenticated client. I recommend this approach. Please tell me more about your use case, if this is not what you are looking for.

**Comment by ankitrajsingh** [comment]
Yeah I got that part now, tried without token it worked. But this link is generated by Okta, and how come Okta isn't supporting it through SDK? In that case every developer have to create multiple http clients. Any reason to remove the bug tag for the urls which is Okta specific and needs to supported by okta client itself?

**Comment by bdemers** [comment]
@ankitrajsingh the SAML metadata URL is typically used as input to configure a SAML client,  (and not consumed directly).

I'm also hesitant to add XML support, for API endpoints that are NOT supported by the SDK because it introduces extra maintenance (e.g. XML parsing security issues).  We would also need to parse the object and return it as a typed object (even if a glorified map).

All that said, If you have an alternative use case that makes use of the SAML metadata within the Okta Management SDK please let us know, it could be something we add support for in the future.

**Comment by ankitrajsingh** [comment]
Hi @bdemers , Org2Org app's SAML metadata (which is issuerId, SSO url & X509 certs)  is consumed by the Okta's corresponding IDP in the counterpart Org which is being linked by Org2Org. While setting up IDP, we upload this data to IDP keystore using Okta SDK, followed by IDP creation which is again done via SDK. This whole flow involves Okta SDK and SAML being not supported by Okta Client is hampering it.

**Comment by bdemers** [comment]
Thanks @ankitrajsingh that is very helpful, I'll ask around and see if there is another option to get this info.

**Comment by bdemers** [comment]
@ankitrajsingh I think your best bet in the short term is just parse the URL directly:

```java
Map result = new ObjectMapper(). readValue(new URI("your-absolute-metadata-url", Map.class));
```

I didn't test this, but I'm guessing something like this is going to be a decent workaround.
Please keep us posted!

**Comment by ankitrajsingh** [comment]
Will check this out @bdemers . 

But would like to highlight my findings with the SAML metadata url being public as mentioned by @arvindkrishnakumar-okta .

Actually, the metadata url we receive back in app payload response after we create Org2Org app via API is not public and requires token. However, while creating app through UI, the SAML metadata url being referenced there is public and while they have the same data, they are having different paths.

Sample SAML urls for the same app:

Via UI: [https://dev-7254968.okta.com/app/exk4oj75eKFtJXcCP5d6/sso/saml/metadata](https://dev-7254968.okta.com/app/exk4oj75eKFtJXcCP5d6/sso/saml/metadata)

Via API: [https://dev-7254968.okta.com/api/v1/apps/0oa4oj75fRQsdnmVy5d6/sso/saml/metadata](https://dev-7254968.okta.com/api/v1/apps/0oa4oj75fRQsdnmVy5d6/sso/saml/metadata)

So while going via API, there is no way we can get the data without token.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Your findings above seem right. I will talk to internal teams here to see if we can get the SAML metadata publicly available via APIs without needing a token. Stay tuned.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Though there is no way presently to retrieve the public SAML metadata URL (url that requires no token), you can still construct the URL yourself with the `id` returned in the [Org2Org response](https://developer.okta.com/docs/reference/api/apps/#response-example-3). So, your public URL will look like: https://dev-xxxxxx.okta.com/api/v1/apps/{appId}/sso/saml/metadata where `{appId}` is the `id` field contained in Org2Org response.

**Comment by ankitrajsingh** [comment]
No we can't construct public url from the one which is returned in Org2Org response. Public url don't take app Id. It takes entityId.

Correct examples of SAML urls are as follows explaining that no correlation exist between two:

Via UI (public): /app/exk4oj75eKFtJXcCP5d6/sso/saml/metadata (1st url)
                                      [-----entityId ------]

Via AP (protected): /api/v1/apps/0oa4oj75fRQsdnmVy5d6/sso/saml/metadata (2nd url)
                                        [------appId-------]

**Comment by arvindkrishnakumar-okta** [comment]
Sorry for the typo in my earlier post.

The public URL you need to construct should take the form: /app/{entityId}/sso/saml/metadata 

And yes, you will not see the entityId in Org2Org response. Unfortunately, the public and private metadata endpoints are designed that way presently and you will need to supply the entityId to be able to hit the unauthenticated public endpoint.

**Comment by ankitrajsingh** [comment]
As per my understanding, Org2Org app does its own SSO setup for SAML internally as this app is specific to Okta Orgs (meant to work only within Okta to Okta ecosystem) and we don't configure or have the way to configure SAML related setup(SSO entity) externally.  

In a nutshell, requirement is to support Org2Org link via SDK and the SAML api being not supported by SDK is a blocker for the same.

We already connected with support team, and they have a PR ready as per my knowledge linked with the issue. Request you to please resolve this.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Do you have a customer support case number that you can provide?

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Here's a quick workaround you can do obtain the access token from the SDK so you can use it to hit the SAML endpoint with any http client of your choice (to answer your initial qn [here](https://github.com/okta/okta-sdk-java/issues/516#issuecomment-764297121))

```
DefaultClientBuilder defaultClientBuilder = new DefaultClientBuilder();
defaultClientBuilder.setBaseUrlResolver(new BaseUrlResolver() {
    @Override
    public String getBaseUrl() {
        return "https://dev-298876.okta.com";
    }
});

AccessTokenRetrieverService accessTokenRetrieverService = new AccessTokenRetrieverServiceImpl(defaultClientBuilder.getClientConfiguration());
try {
    OAuth2AccessToken oAuth2AccessToken = accessTokenRetrieverService.getOAuth2AccessToken();

    println("Access Token: " + oAuth2AccessToken.getAccessToken());
    println("Token Type: " + oAuth2AccessToken.getTokenType());
    println("Scope: " + oAuth2AccessToken.getScope());
    println("Issued At: " + oAuth2AccessToken.getIssuedAt());
    println("Expires In: " + oAuth2AccessToken.getExpiresIn());

} catch (IOException e) {
    e.printStackTrace();
} catch (InvalidKeyException e) {
    e.printStackTrace();
}
```

Note that to achieve this, you should change the `okta-sdk-impl` dependency from `runtime` to the default `compile`.

**Comment by ankitrajsingh** [comment]
This class generates a tokenClient of its own internally ("OAuth2TokenClient") and thereby our code will have two Okta clients running. Not sure what trouble it may cause. its also better if token management is done by a central client and not distributed. Can u suggest any approach which will help us do so?

**Comment by arvindkrishnakumar-okta** [comment]
`OAuth2TokenClient` is an extension of `BaseClient` used by the SDK internally. There should be no problems from a caller's perspective on how the SDK internally uses the `OAuth2TokenClient` to retrieve the token.

**Comment by ankitrajsingh** [comment]
We already discussed about this client: https://github.com/okta/okta-sdk-java/issues/516#issuecomment-764393943. The need is to maintain central Okta client. Going by this workaround we will have two Okta clients + 1 custom http client, just to hit one XML based API, which is surely not maintainable for long.

**Comment by VitaliiTytarenko-okta** [comment]
@ankitrajsingh 
The necessary changes have been made.
To get raw SAML metadata, do:
```
InputStream rawSamlMetadata = client.http()
                .addHeaderParameter("Accept", "application/xml")
                .getRaw("/api/v1/apps/${clientId}/sso/saml/metadata");
```
It will be introduced in the next release: **3.1.0-SNAPSHOT** _(will be available soon)_.
Feel free to reopen this thread if you have any questions/doubts/suggestions.

**Comment by arvindkrishnakumar-okta** [comment]
3.1.0 has just been released.
