### ISSUE TITLE
Client is unable to interact via client_secret_jwt authentication

### ISSUE THREAD

**Issue by raunakkr** [okta/okta-sdk-java#518]
We are using Okta SDK V3.0.1 [https://github.com/okta/okta-sdk-java/releases](https://github.com/okta/okta-sdk-java/releases) for Java. we have a use case to interact with okta service applications based on client_secret_jwt authentication which doesn't seem to work.

Please let me know how can we make this work.

**Comment by sergiishamrai-okta** [comment]
Thank your for your question, @ankitrajsingh

Have you tried to follow [this](https://developer.okta.com/docs/guides/build-self-signed-jwt/java/jwt-with-shared-key/) guideline?

**Comment by raunakkr** [comment]
@sergiishamrai-okta Above guideline is to build client assertions signed by client_secret. That is expected to be a part of SDK itself. Even if we create this assertion manually, there is no setter on okta clientBuilder i can find to pass this assertion.

**Comment by bdemers** [comment]
@raunakkr I think this issue is related to #477
Where you have an access token from an existing application and you want to use that in with the SDK?
(please correct me if I'm wrong)

**Comment by praveenatluri-okta** [comment]
@bdemers 
This is related to signing the JWT using the shared Key (client_secret_jwt) authentication method. please check the following [link](https://developer.okta.com/docs/guides/build-self-signed-jwt/java/jwt-with-shared-key/).

**Comment by arvindkrishnakumar-okta** [comment]
Internal ref: OKTA-367692

**Comment by arvindkrishnakumar-okta** [comment]
This works as designed, we only support `private_key_jwt` for OAuth service apps in the SDK. Please refer documentation at https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/create-publicprivate-keypair/.
