### ISSUE TITLE
Exposing access token retrieval method directly from DefaultClient

### ISSUE THREAD

**Issue by ankitrajsingh** [okta/okta-sdk-java#520]
@ankitrajsingh exposing access token retrieval method directly from DefaultClient is a separate item that can be considered outside the scope of this issue. For the scope of the original issue mentioned here (`Accept` header issue with client while accessing XML based APIs), we will push a fix soon.  cc: @VitaliiTytarenko-okta

_Originally posted by @arvindkrishnakumar-okta in https://github.com/okta/okta-sdk-java/issues/516#issuecomment-764399358_

**Comment by ankitrajsingh** [comment]
Hi @arvindkrishnakumar-okta , let me know if this can be supported with existing implementation of SDK

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Thanks. Note that by managing the token retrieval and lifecycle internally, the SDK simplifies things for you. If you wish the SDK to return you the access token directly, you are losing out on the "auto refresh on token expiry" capability that the SDK offers. What this means is, you will have to hit the token api again manually to refresh your access token when it expires. The goal of OAuth implementation in the SDK is to manage this complexity on behalf of the user. So, offering a hook/way to return the access token defeats the whole purpose.

**Comment by ankitrajsingh** [comment]
Yeah, so that is what i meant by keeping token lifecycle with Okta Client itself. My requirement is to just issue a temp token to our own client which it will fetch time and again if needed for any consequent request from okta client. So we are in no way planning to do token management on our own. To be clear, It's just that we want to extend the okta client's functionality to support other apis which are not already supported through okta client.

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh The primary purpose of Okta Client is to help users invoke Okta APIs with a supplied client configuration. The issue #516 you raised earlier seems valid and needs to be fixed. The ask in this issue to have the client return a "temp token" for further use does not seem to be a use case for which the SDK is designed for, IMHO.
