### ISSUE TITLE
Creating oidc_client application using private_key_jwt authentication method

### ISSUE THREAD

**Issue by mahimavuppuluri** [okta/okta-sdk-java#523]
We are trying to create an OIDC application with authentication method: private_key_jwt
1. Is this a valid authentication method for OIDC application?
2. We are creating this via OKTA SDK. Noticed that for tokenEndPointAuthMethod, this is the enum: OAuthEndpointAuthenticationMethod. This enum has: none, client_secret_post, client_secret_basic, client_secret_jwt, but not what we are looking for. Can this be added?
3. We are also creating service client app with the same authentication method. If we do not have private_key_jwt as a part of OAuthEndpointAuthenticationMethod enum, we wont be able to use the application builders and interfaces.

**Comment by sergiishamrai-okta** [comment]
Thank you for the question! Can you help me understand more about application you working on? 

The `private_key_jwt` client authentication method is the only supported method for OAuth service apps. 

More info about OpenID Connect authentication standard is [here](https://developer.okta.com/docs/concepts/oauth-openid/#openid-connect)

**Comment by mahimavuppuluri** [comment]
Hi @sergiishamrai-okta Im trying to create an app using OIdCApplicationBuilder. Here I'm trying to set authentication method to private_key_jwt. setTokenEndpointAuthMethod takes an enum of type: OAuthEndpointAuthenticationMethod. Here I do not see a value for private_key_jwt. How can we set this value while creating an application through the OIdCApplicationBuilder?

**Comment by arvindkrishnakumar-okta** [comment]
@mahimavuppuluri Thanks for reporting this. This looks like a bug as we're missing the required field value in our spec. We'll get that fixed.

**Comment by praveenatluri-okta** [comment]
@arvindkrishnakumar-okta  Is there an internal Jira for this issue?

**Comment by arvindkrishnakumar-okta** [comment]
@praveenatluri-okta OKTA-367757
