### ISSUE TITLE
Creating oidc_client application using SAML 2.0 Assertion grant type

### ISSUE THREAD

**Issue by mahimavuppuluri** [okta/okta-sdk-java#524]
I'm trying to create an app using OIdCApplicationBuilder. Here I'm trying to set grant type to SAML 2.0 Assertion. setGrantTypes takes a list of enum of type: OAuthGrantType. Here I do not see a value for SAML 2.0 Assertion. How can we set this value while creating an application through the OIdCApplicationBuilder?

**Comment by sergiishamrai-okta** [comment]
Thank you for the question, @mahimavuppuluri. You'll get an assistance shortly.

**Comment by arvindkrishnakumar-okta** [comment]
@mahimavuppuluri You cannot create a `SAML 2.0` application using the `OIDCApplicationBuilder` presently. You could do something like https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/ApplicationsIT.groovy#L174 to create your SAML app.

**Comment by hiteshbargujar** [comment]
@arvindkrishnakumar-okta please see my notes below on this issue, it is not about creating a SAML App but providing a GRANT_TYPE of SAML to an OIDC APP. Please closely follow the below points.
--------------------------------------------------------------
We are trying to create an OIDC App using API '/ap1/v1/apps'
1. Which we are able to do via Postman.
2. Part of the request is a field 'grant_types' [look below], where we want to use two values
“grant_types”: [
          “authorization_code”,
         “urn:ietf:params:oauth:grant-type:saml2-bearer”
        ]


3. Now we want to create the OIDC app programmatically while using OKTA SDK. To achieve the same we are using api/src/main/java/com/okta/sdk/resource/application/OIdCApplicationBuilder.java
	3.1 it has a method called OIdCApplicationBuilder setGrantTypes(List<OAuthGrantType> grantTypes);
	3.2 the method argument here is list of OAuthGrantType Enum
	3.3 This enum only has values
		AUTHORIZATION_CODE("authorization_code"),
		IMPLICIT("implicit"),
		PASSWORD("password"),
		REFRESH_TOKEN("refresh_token"),
		CLIENT_CREDENTIALS("client_credentials");
	3.4 As you can see programmatically we cannot add “urn:ietf:params:oauth:grant-type:saml2-bearer” as the Enum is missing this.

**Comment by arvindkrishnakumar-okta** [comment]
@hiteshbargujar Thanks for the above details. While we work on a solution to support this, as a short workaround refer https://github.com/okta/okta-sdk-java#call-other-api-endpoints and you should be able to
do something like below to achieve what you want:

`resource.put("grant_types", List.of("authorization_code", "urn:ietf:params:oauth:grant-type:saml2-bearer")`

Keep me posted!

**Comment by dcottel** [comment]
@arvindkrishnakumar-okta Do we have a date for the Pull to be completed?  Need to provide back to the client.  Thanks!
