### ISSUE TITLE
Method threw 'java.lang.StringIndexOutOfBoundsException' exception

### ISSUE THREAD

**Issue by ankitrajsingh** [okta/okta-sdk-java#542]
https://github.com/okta/okta-sdk-java/blob/90436758263d2c597319838af77cb848b2ae6f11/impl/src/main/java/com/okta/sdk/impl/ds/DefaultResourceFactory.java#L156

This breaks if index is -1 (index out of bound excpetion) i.e. if the interface class is at root level inside the base-package, eg:

SUPPORTED_PACKAGES: com.xyz.model.extensibleresource
CLASS ALONG WITH PACKAGE: com.xyz.model.extensibleresource.SubLink

This works if i place the SubLink under a dummy folder inside base package:

SUPPORTED_PACKAGES: com.xyz.model.extensibleresource
CLASS ALONG WITH PACKAGE: com.xyz.model.extensibleresource.dummy.SubLink

There should be a check of index != -1 for further computation

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Thanks for posting!

Can you elaborate a bit more on what you're trying to achieve here?

**Comment by ankitrajsingh** [comment]
I am trying to use my own interface for request/response parsing which extends from ExtensibleResource using defaultClient. Those interfaces have been defined at our project's given path and If I add this path to Okta's supported packages for scanning, while parsing the response, the method called above internally within SDK throws exception for interfaces present directly within the base path.

```
@AutoService(ResourceFactoryConfig.class)
public class OktaResourceFactoryConfig implements ResourceFactoryConfig {

    @Override
    public Set<String> getSupportedPackages() {
        return Collections.singleton("com.xyz.model.extensibleresource");
    }

}
```

```
package com.xyz.model.extensibleresource;

import com.okta.sdk.resource.ExtensibleResource;

public interface SubLink extends ExtensibleResource {

    public String getHref();

    public String getType();

}
```

`client.http().get(someresourceurl, SubLink.class)`

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for the details. What would be the fully qualified name of the implementation class of `SubLink`?

**Comment by ankitrajsingh** [comment]
Its `com.xyz.model.extensibleresource.impl.DefaultSubLink`

But I had to include dummy package as i mentioned because of -1 error, so with this its following the below qualified name: `com.xyz.model.extensibleresource.impl.dummy.DefaultSubLink`

**Comment by arvindkrishnakumar-okta** [comment]
@ankitrajsingh Will https://github.com/okta/okta-sdk-java/pull/545/commits/0a3bb180069b27d5cde81deb0be3c0d9eccf4a35 help?

**Comment by ankitrajsingh** [comment]
Yes, will work fine

**Comment by arvindkrishnakumar-okta** [comment]
Fix merged.
