### ISSUE TITLE
Password should not be stored in `String`

### ISSUE THREAD

**Issue by Ronnie76er** [okta/okta-sdk-java#55]
As discussed many places (here's a great StackOverflow question about it: http://stackoverflow.com/questions/8881291/why-is-char-preferred-over-string-for-passwords/8889285#8889285), password fields in Java should not be stored in `String`, as they are immutable.  

The `Password` object should also have a clear method to destroy the string or the object after use, or should be built into the SDK to be destroyed as soon as possible.

I may also suggest to call the object something like `PlaintextPassword`, so developers feel sufficiently paranoid about using it. 😃

**Comment by jmelberg-okta** [comment]
@Ronnie76er: Great suggestion. I have created a ticket with our team to update the SDK.

If you are interested in pushing this change yourself, please visit [developer.okta.com/cla](http://developer.okta.com/cla) for more information.

Thanks!

**Comment by bdemers** [comment]
Fixed in d5aeda6cf6c7a6eed2c919f03a6d6e93ab077e4e
