### ISSUE TITLE
listUser API with search parameter returns invalid users

### ISSUE THREAD

**Issue by venkateshkatti-okta** [okta/okta-sdk-java#556]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - bug report
  

### Background info

Describe your issue or request here (if necessary).
We are trying to leverage listUser SDK API with search parameter to retrieve users having a value in a specific attribute. We are observing that users with null (or no value) in this attribute is also getting returned.

Reference: https://developer.okta.com/docs/reference/api-overview/#operators

### Expected behavior

Only users having a value in that attribute should be returned based on the operators being leveraged.

### What went wrong?

We are observing that users with null (or no value) in this attribute is also getting returned. 

### Steps to reproduce

Usage:
client.listUsers(null, null, null, "profile.attribute1 pr", null) //Present Operator returns users with null attribute1 value.

### SDK Version
Tried with 3.0.0 and 3.0.3

**Comment by arvindkrishnakumar-okta** [comment]
@venkateshkatti-okta Thanks for reporting this! I'll dig into this and get back to you.

**Comment by arvindkrishnakumar-okta** [comment]
Search parameter should be the 3rd argument to `listUsers(..)`.

Correct Usage should be like:

`client.listUsers(null, null, 'profile.email pr', null, null)`

**Comment by venkateshkatti-okta** [comment]
Tried swapping the search parameter place, but still observe the same issue -users being returned with null attr value. Pasting the snippet here:
client.listUsers(null, null, "profile.attr1 pr",null , null).stream()
        .forEach(user -> {
 
        		if (user.getProfile().getString("attr1") == null) {
                    System.out.println(user.getProfile().getEmail());
                }
        		
        	
        	
        });

**Comment by arvindkrishnakumar-okta** [comment]
Have you tried accessing the API via a curl command like below?

```
curl -X GET "https://{yourOktaDomain}/api/v1/users?search=profile.attr1%20pr" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: SSWS {api_token}"
```

**Comment by arvindkrishnakumar-okta** [comment]
@venkateshkatti-okta Tried to reproduce this issue in dev/test org but it works fine. 

I see support team has created JIRA OKTA-379011 that hints the reported issue might be local/specific to this customer's profile import/setup.

**Comment by arvindkrishnakumar-okta** [comment]
This does not look like an SDK issue. Closing it therefore. I see the customer specific issue is being handled in the above JIRA separately by PS team.
