### ISSUE TITLE
Get all assigned group to application with searching

### ISSUE THREAD

**Issue by andriiunitq** [okta/okta-sdk-java#563]
I want to get all groups assigned to some application with filtering/search, below I've described next approaches which I tried:

- **Get assigned group for application**
 _/api/v1/apps/{app_id}/groups?expand=group&limit=10&search=profile.description eq "test"_

I've added the **?expand=group** param to be able to see the group-related info, however, the **search** param won't be applied because the search isn't working with _embedded object.
https://developer.okta.com/docs/reference/api/groups/

- **List Groups**
_/api/v1/groups?expand=app&limit=4&search=profile.description eq "test"_

I'm able to search and filter groups, however when I try to add the **?expand=app** attribute I don't receive any additional information (i.e. **_embedded** object), I think it's some kind of issue because I've added this param according to documentation. 
https://developer.okta.com/docs/reference/api/groups/
So, in this case, I am not able to get application information...

### I'm submitting a
  - [ ] bug report

### Expected behavior
According to that, I am wondering how I can all groups assigned to some application with filtering or searching?

**Comment by arvindkrishnakumar-okta** [comment]
@andriiunitq Thanks for posting!

Do you mean it does not work as expected with a simple `curl` or with the `SDK` or both?

**Comment by andriiunitq** [comment]
@arvindkrishnakumar-okta It doesn't work with curl and SDK, also I've tried to use the same requests via Postman and still not succeed.
So, I suppose maybe it's an issue with Okta API itself or of course wrong using from my side:)

**Comment by arvindkrishnakumar-okta** [comment]
I'll look at potential ways to achieve this and keep you posted in a bit.

**Comment by andriiunitq** [comment]
@arvindkrishnakumar-okta 

thank you, I've added the question to the okta forum, but no response yet.
https://devforum.okta.com/t/get-all-assigned-group-to-application-with-searching/13458

**Comment by arvindkrishnakumar-okta** [comment]
@andriiunitq Thanks, I've asked our internal API teams and it looks like a bug. I've created an internal ticket for the concerned team.

**Comment by arvindkrishnakumar-okta** [comment]
@andriiunitq On a closer look, I see that the search will NOT work with `_embedded` object and this is working as expected and is reflected in the documentation:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/61501885/113439299-2680f200-939f-11eb-96e5-052d2db92081.png">
