### ISSUE TITLE
Enable option to supply kid as part of ClientBuilder interface

### ISSUE THREAD

**Issue by gssureshthapa** [okta/okta-sdk-java#576]
### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

Enable option to support Key ID (kid) as part of ClientBuilder interface. 

### SDK Version
4.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@gssureshthapa Thanks! We'll get that added in `ClientBuilder`.

**Comment by oanam** [comment]
Hi,
My team is also very interested in this feature. Any idea when we can expect to see this in the SDK?
Regards,
Oana

**Comment by VitaliiTytarenko-okta** [comment]
Hi, @oanam!
I'm working on this feature now. Hope it will available in the next release.
Thanks for using Okta!
