### ISSUE TITLE
DefaultOAuth2Client is missing properties

### ISSUE THREAD

**Issue by oanam** [okta/okta-sdk-java#579]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
Auto-generated class [DefaultOAuth2Client](https://developer.okta.com/okta-sdk-java/development/apidocs/com/okta/sdk/impl/resource/application/DefaultOAuth2Client.html) does not include all the properties documented in the API:
https://developer.okta.com/docs/reference/api/oauth-clients/#client-application-properties

Just to name a few: 
- jwks,
- token_endpoint_auth_method,
- application_type,
- grant_types,
- response_types,
and many more are missing from the Java object.

### Expected behavior
[DefaultOAuth2Client](https://developer.okta.com/okta-sdk-java/development/apidocs/com/okta/sdk/impl/resource/application/DefaultOAuth2Client.html) should include all the properties documented in the API.

### What went wrong?

SDK does not offer a class that can be used with https://developer.okta.com/docs/reference/api/oauth-clients API.

### Steps to reproduce

N/A

### SDK Version
4.0.0

**Comment by shuowu** [comment]
@oanam Thanks for reporting the issue! 

Internal Ref: OKTA-391223

**Comment by sergiishamrai-okta** [comment]
@oanam Thanks for your question!

The class that you asking about is a response-type for [List Client Resources for a User](https://developer.okta.com/docs/reference/api/users/#list-client-resources-for-a-user).

It's not implementing [Application](https://okta.github.io/okta-sdk-java/development/apidocs/com/okta/sdk/resource/application/Application.html) interface so it could not be used as an application client.

Can you help me understand what kind of task you trying to solve?

**Comment by oanam** [comment]
Hi,

We're trying to call these APIs in our application:
https://developer.okta.com/docs/reference/api/oauth-clients/

More specifically:

- GET by id: https://developer.okta.com/docs/reference/api/oauth-clients/#get-an-oauth-client
- PUT: https://developer.okta.com/docs/reference/api/oauth-clients/#update-a-client-application

I was unable to find any matching classes in the SDK.

**Comment by sergiishamrai-okta** [comment]
Thanks for the details @oanam.
Please follow this issue for updates.

**Comment by sergiishamrai-okta** [comment]
Hello @oanam,
I've investigated your question and have some updates for you.
 
Clients managed through the Dynamic Client Registration API are modeled as Applications in Okta and appear in the Applications section of the Admin Console.
Changes made through the API appear in the UI and vice versa. Tokens issued by these clients follow the rules for access tokens and ID tokens.
Apps created on the Apps endpoint (/api/v1/apps) default to `consent_method=TRUSTED`, while those created with Dynamic Client Registration (/oauth2/v1/clients) default to `consent_method=REQUIRED`.

SDK fully covers the Apps endpoint (/api/v1/apps).
With that said you can use `OIDCApplicationBuilder` to create the OAuth2 application.

Here is code sample:

```
Application application = OIDCApplicationBuilder.instance()
    .setName("oidc_client")
    .setLabel("test_app")
    .addRedirectUris("http://www.google.com")
    .setResponseTypes(Arrays.asList(OAuthResponseType.TOKEN, OAuthResponseType.CODE))
    .setGrantTypes(Arrays.asList(OAuthGrantType.IMPLICIT, OAuthGrantType.AUTHORIZATION_CODE))
    .setApplicationType(OpenIdConnectApplicationType.NATIVE)
    .setClientId("dummy_id")
    .setClientSecret("dummy_secret_shgfhsgdhfgwg")
    .setAutoKeyRotation(true)
    .setTokenEndpointAuthMethod(OAuthEndpointAuthenticationMethod.NONE)
    .setIOS(true)
    .setWeb(false)
    .setConsentMethod(OpenIdConnectApplicationConsentMethod.REQUIRED)
    .setLoginRedirectUrl("http://www.myApp.com")
    .setErrorRedirectUrl("http://www.myApp.com/errror")
    .setSelfService(false)
    .buildAndCreate(client);

OpenIdConnectApplicationSettingsClient oAuthClient =
                ((OpenIdConnectApplicationSettings)application.getSettings()).getOAuthClient();
oAuthClient.getApplicationType();
oAuthClient.getGrantTypes();
oAuthClient.getResponseTypes();
oAuthClient.getJwks();

```

**Comment by sergiishamrai-okta** [comment]
@oanam hope the above comments helped.
Feel free to reopen this issue if you have any further questions.

**Comment by oanam** [comment]
Thank you, @sergiishamrai-okta ! 
Our team has already implemented the calls to the Dynamic Client Registration APIs without using the SDK, but we'll consider your recommended approach as a future refactoring.
