### ISSUE TITLE
get methods which accept userId do not url-encode it when sending request

### ISSUE THREAD

**Issue by hcoa** [okta/okta-sdk-java#580]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

Trying to get existing user by email using `client.getUser`.

### Expected behavior

`client.getUser` should successfully return a user object for existing user

### What went wrong?

For some emails such `username#@domain.com` (with hash symbol "#"). `client.getUser` returns "user not found" error (when the user exists in okta directory)

Error:
`"errorSummary": "Not found: Resource not found: username (User)",` (usually this error shows the full email and not only truncated part)

### Steps to reproduce

1. Register a user with email that contains "#" symbol (special character is supported by Okta - https://help.okta.com/en/prod/Content/Topics/Directory/Reference_Directories.htm)
2. initiate okta client with valid credentials
3. invoke `client.getUser` and get "Not found" error

### SDK Version
3.0.1 (same behaviour in 4.0.0)

Though it's also related to Okta server-side request processing it is still possible to fix it in the library using `URLEncoder` to encode.

**Comment by sergiishamrai-okta** [comment]
@hcoa  Thanks for reporting the issue!

Internal Ref: [OKTA-391589](https://oktainc.atlassian.net/browse/OKTA-391589)

**Comment by VitaliiTytarenko-okta** [comment]
@hcoa 
The bug has been fixed.
