### ISSUE TITLE
Methods using filter throw Invalid Search Criteria

### ISSUE THREAD

**Issue by mimkorn** [okta/okta-sdk-java#587]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I am trying to use the method 
`client.listApplications(null, "user.id+eq+someid", null, null)`

### Expected behavior

get returned applications

### What went wrong?

I always get 
`com.okta.sdk.resource.ResourceException: HTTP 400, Okta E0000031 (Invalid search criteria.),`

### Steps to reproduce

I used bare https://github.com/okta/samples-java-spring/tree/master/okta-hosted-login and added okta java sdk to the project and created this mapping:

```java
        @RequestMapping("/somewhere")
        public RedirectView redirectSomewhere(OAuth2AuthenticationToken authentication) {
            Client client = Clients.builder()
                    .setOrgUrl("https://ourdomain.oktapreview.com")
                    .setClientCredentials(new TokenClientCredentials("our token")) 
                    .build();
ApplicationList applications = client.listApplications(null, "user.id eq hardcodeduserid", null, null);
....
}
```

I tried also 
- "user.id+eq+hardcodeduserid"
- ("", "user.id eq hardcodeduserid", "", false)
and some other options, always get the same error

### SDK Version
4.0.0

**Comment by sergiishamrai-okta** [comment]
Hello @mimkorn,
Thanks for your question!

Can you try to wrap with quotes your `user.id` param in the filter string?
Something like:

`ApplicationList applications = client.listApplications(null, "user.id eq \"hardcodeduserid\"", null, null);`

More info you could grab [here](https://developer.okta.com/docs/reference/api/apps/#list-applications)

**Comment by mimkorn** [comment]
It worked. Thanks. The Java SDK doesn't point to this implicitly, it's slightly awkward API, but it's understandable, there's some limits with generated SDKs.

Thanks for the pointer, I'll know better to look for more examples in the REST API docs.
