### ISSUE TITLE
Obtaining the list groups assigned to the application doesn't work with the "expand = group" attribute

### ISSUE THREAD

**Issue by andriiunitq** [okta/okta-sdk-java#592]
### I'm submitting a
  - [ ] bug report

### Background info

I want to load all groups assigned to an application, for this purpose I used the next code:

`oktaClient.getApplication(oktaAppId)
        .listGroupAssignments("", GROUP)
        .stream()
        .map({{converting part}})
        .collect(Collectors.toList());`

By default the limit of this kind of operation is 20, so during the first request will be loaded 20 groups from the application, however, the problem is that if I have more than 20 groups assigned to my application, the "?expand=group" params won't be applied for next requests.

The further requests won't return the "_embeddable" object for groups, which is required for my business logic.

### Expected behavior

My expectation, that if pagination is hidden and implemented under the hood, all further requests will use the same request params as the initial request (the 1st request)

### Steps to reproduce

1. Create around ~30 groups
2. Assigned them to some application
3. try to use the below code to obtain the list of groups

`oktaClient.getApplication(oktaAppId)
        .listGroupAssignments("", GROUP)
        .stream()
        .map({{converting part}})
        .collect(Collectors.toList());`

### SDK Version
3.1.0

**Comment by laura-rodriguez** [comment]
Hi @andriiunitq,

Thanks for reporting this issue! Our Java devs will review it soon and post updates here.

Internal Ref: https://oktainc.atlassian.net/browse/OKTA-397604

**Comment by VitaliiTytarenko-okta** [comment]
The bug has been fixed.
