### ISSUE TITLE
Create user without sending email

### ISSUE THREAD

**Issue by klaushauschild1984** [okta/okta-sdk-java#594]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

When I create a user via Java client I am not able to pass `sendEmail=false` to the endpoint to prevent Okta from sending an activation mail.

### Expected behavior

Would be nice to have this functionality integrated into Java client as the API already offers this. I really like to utilize the client but in some use cases I need to prevent such emails and I do not like the idea to have an alternate implementation just to achieve this tiny detail.

### SDK Version
4.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@klaushauschild1984 Thanks for posting!

There are two options for you:

1) 
```
        // 1. Create a user
        User user = UserBuilder.instance()
                .setEmail(email)
                .setFirstName(firstName)
                .setLastName(lastName)
                .setPassword(password.toCharArray())
                .setActive(false)
                .buildAndCreate(client)

        // 2. Activate the user and do not send activation email (set it to true if you want to send activation email).
        user.activate(false)
```

2) Call API endpoint https://developer.okta.com/docs/reference/api/users/#activate-user using the technique described at https://github.com/okta/okta-sdk-java#call-other-api-endpoints.

Let me know if that helps!

**Comment by klaushauschild1984** [comment]
Thanks for the response.

Ok. This feature is not missing but I was not able to find it. And I needed some tries to understand the importance of providing `setActive(false)` or leaving this statement out.
