### ISSUE TITLE
Writing Unit testing for sdk functions

### ISSUE THREAD

**Issue by sanjayshrestha1** [okta/okta-sdk-java#617]
I wanted to perform Unit Test the function which ultimately calls the sdk of okta so how can I mock the response for those sdk methods.
If there is any link that I could refer that would be great and any response is appreciated.

**Comment by sergiishamrai-okta** [comment]
Hello @sanjayshrestha1 ,
Thanks for using OKTA SDK.

One of the samples with the mocked responses for example:
[LogsTest](https://github.com/okta/okta-sdk-java/blob/master/impl/src/test/groovy/com/okta/sdk/impl/resource/log/LogsTest.groovy)

**Comment by sanjayshrestha1** [comment]
Hi @sergiishamrai-okta, I am trying to run the okta-sdk-java in my machine but there is no class file named DefaultClient imported which is extended from MockClient class.

**Comment by sergiishamrai-okta** [comment]
Hi @sanjayshrestha1, 
Can you share your pom.xml dependencies?
I assume you didn't import all required dependencies.
The prerequisites for Java SDK usage is [here](https://github.com/okta/okta-sdk-java#prerequisites)

**Comment by sanjayshrestha1** [comment]
The pom file contains the com.okta.sdk as defined in the prerequisites. I have also tried to replicate the code in java for unit test but instead of getting the mocked data from json file as mentioned in https://github.com/okta/okta-sdk-java/blob/master/impl/src/test/groovy/com/okta/sdk/impl/resource/log/LogsTest.groovy this link it is getting from the users from the specified client configured via baseurl and apikey. I just want to have the mock object from json file instead of from the api calling using client information.

**Comment by P1ll3P4ll3** [comment]
It seems that the support here links to files contained in modules not available with the default prerequisite dependencies for the Okta Java SDK.

We have the same problem and question on how to get the Okta API Calls isolated, e.g. via Mockito, returning User or UserList objects. To be able to create those objects directly, a client is needed.
