### ISSUE TITLE
Error when calling SocialAuthToken.getTokenType

### ISSUE THREAD

**Issue by ansman** [okta/okta-sdk-java#634]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

I'm trying to get a social auth token for a user. While reading processing the token I get an exception when calling `SocialAuthToken.getTokenType`. The error is:
```
No enum constant com.okta.sdk.resource.identity.provider.SocialAuthToken.TokenTypeEnum.SDK_UNKNOWN
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.okta.sdk.impl.resource.EnumConverter.fromValue(EnumConverter.java:56)
	at com.okta.sdk.impl.resource.AbstractPropertyRetriever.getEnumProperty(AbstractPropertyRetriever.java:290)
	at com.okta.sdk.impl.resource.AbstractPropertyRetriever.getEnumProperty(AbstractPropertyRetriever.java:276)
	at com.okta.sdk.impl.resource.identity.provider.DefaultSocialAuthToken.getTokenType(DefaultSocialAuthToken.java:122)
```

I tried calling the endpoint from a terminal manually and this is what it returns:
```json
[
    {
        "expiresAt": "2021-09-20T20:26:55.000Z",
        "id": "<redacted>",
        "scopes": [
            "email",
            "openid",
            "profile",
            "https://graph.microsoft.com/User.Read"
        ],
        "token": "<redacted>",
        "tokenAuthScheme": "Bearer",
        "tokenType": "urn:ietf:params:oauth:token-type:access_token"
    }
]
```

It looks like this is a clear parsing error here as the SDK expects the value to be `ACCESS` or `REFRESH`.

### Expected behavior

I expect to get an instance of `SocialAuthToken.TokenTypeEnum` back.

### What went wrong?

I get an exception.

### Steps to reproduce

My code looks like this:
```kotlin
client.getIdentityProvider("...")
  .listSocialAuthTokens("...")
  .single()
  .getTokenType()
```

### SDK Version
5.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@ansman Thanks for posting!

Can you share the code snippet or the API request body that you are using? 

The SDK expects the values `ACCESS` | `REFRESH` per the spec defined [here](https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L12657-L12660).

**Comment by ansman** [comment]
The code snippet is under "Steps to reproduce" in the issue and there is no request body since it's a GET request.

The enum constants seem incorrectly defined. The [API documentation at Okta](https://developer.okta.com/docs/reference/api/idps/#identity-provider-social-authentication-token-object) point you towards  the [OAuth2 Spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-token-exchange-07#section-3) which lists the types as:
* `urn:ietf:params:oauth:token-type:access_token`
* `urn:ietf:params:oauth:token-type:refresh_token`
Which is exactly what the actual API is returning.

**Comment by arvindkrishnakumar-okta** [comment]
Looks like we need to update the spec with the correct constants for enum https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L12658-L12660.

**Comment by arvindkrishnakumar-okta** [comment]
Internal Ref: OKTA-429925

**Comment by ansman** [comment]
I'm happy to open a PR if you'd like. But I'm wondering if it should even be an enum since the format is is open ended (from the oauth spec):
> Other URIs to indicate other token types MAY be used.

**Comment by arvindkrishnakumar-okta** [comment]
Fixed in https://github.com/okta/okta-management-openapi-spec/pull/78, SDK will be updated to this spec revision soon.
