### ISSUE TITLE
There is no example and apparently no support for verifying factors that require a challenge

### ISSUE THREAD

**Issue by Artur-** [okta/okta-sdk-java#643]
### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

The API docs at https://developer.okta.com/docs/reference/api/factors/#verify-a-push-factor-challenge contains the endpoint to poll if a factor challenge has completed, e.g. when using Okta Verify. 

### Expected behavior

You can do something like
```
VerifyUserFactorResponse response = factor.verify();
while (response.pollForResult().getFactorResult() == FacorResult.WAITING) {
   Thread.sleep(100);
}
```

### What went wrong?

There seems to be no API for polling for the result. Instead you need to do something like
```
String pollLink = (String) ((Map) response.getLinks().get("poll")).get("href");
DataStore dataStore = client.getDataStore();
VerifyUserFactorResponse pollResult = dataStore.getResource(pollLink, VerifyUserFactorResponse.class);
```
which is not very obvious.

### SDK Version
5.0.0

**Comment by VitaliiTytarenko-okta** [comment]
Thank you @Artur- for the reporting. I put it on our roadmap and we will resolve it by priority. We will let you know.
Internal ref: [OKTA-430336](https://oktainc.atlassian.net/browse/OKTA-430336)

**Comment by arvindkrishnakumar-okta** [comment]
Unfortunately, we do not offer a way to poll for user factor verification and the user has to parse the response to get the polling href and implement a way to do this. Though this (parsing response for polling href) is not obvious, this is how the backend API is structured presently.
