### ISSUE TITLE
GroupRule update makes POST and not PUT

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#645]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I'm building an API gateway using the Java Okta sdk and I encountered an issue when trying to update a group rule in Okta.

### Expected behavior

On using the `.update()` function the Group Rule should update with new Expression and/or Conditions.

### What went wrong?

 Create and Delete functions work fine but on using the `.update()` function I'm getting the following error : 

`HTTP 400, Okta E0000001 (Api validation failed: name - name: Policy rule name already in use), ErrorId oaentIhY5BpT0C426Trbg4ltA`

The API seems to make a POST call to create and not a PUT to update.

### Steps to reproduce

Here is my code used to update the GroupRule object from a JSON payload (which comes from a GET /groups/rules).

```
            JSONObject object = toUpdate.getJSONObject(i);
            String name = object.getString("name");
            String expressionValue = object.getJSONObject("conditions").getJSONObject("expression").getString("value");
            String expressionType = object.getJSONObject("conditions").getJSONObject("expression").getString("type");
            JSONObject groupIdToGroupNameMap = object.getJSONObject("_embedded").getJSONObject("groupIdToGroupNameMap");

            HashMap<String, String> newGroupsId = findNewGroupsId(groupIdToGroupNameMap);
            if (expressionValue.contains("Group") && !expressionValue.contains("GroupName")) {
                //replace expressionValue IDs
                expressionValue = transformExpressionValue(expressionValue, newGroupsId);
            }

            List<String> assignUserToGroups = transformAssignUserToGroups(
                    jsonArrayToList(object.getJSONObject("actions").getJSONObject("assignUserToGroups").getJSONArray("groupIds"))
                    , newGroupsId);

            GroupRuleList groupRules = okta.listGroupRules(name, "");
            String finalExpressionValue = expressionValue;
            groupRules.stream().forEach(groupRule -> {

                GroupRuleExpression groupRuleExpression = groupRule.getConditions().getExpression();
                groupRuleExpression.setValue(finalExpressionValue);
                groupRuleExpression.setType(expressionType);
                GroupRuleConditions groupRuleConditions = groupRule.getConditions();

                GroupRuleGroupAssignment groupRuleGroupAssignment = groupRule.getActions().getAssignUserToGroups();
                groupRuleGroupAssignment.setGroupIds(assignUserToGroups);
                GroupRuleAction groupRuleAction = groupRule.getActions();

                groupRule.setName(name);
                groupRule.setConditions(groupRuleConditions.setExpression(groupRuleExpression));
                groupRule.setActions(groupRuleAction.setAssignUserToGroups(groupRuleGroupAssignment));

                groupRule.update();
```

**Comment by VitaliiTytarenko-okta** [comment]
Thank you @Artur- for the reporting.
We use the **POST** method only for creating new entities, **PUT** - for updates, according to the HTTP conventions.
Your exception message says that you are trying to update a GroupRule with a name that already exists. SDK won't let you do it.

Could you try next:
- create a new organization or remove all GroupRules in your current organization 
- create 2 groups with **different** names
- try to update the name of one of them to the same name as the second --> _and you will see your error_
- now update the name of one of GroupRule to something unique --> _should be successful and the rule should be updated_

Check your code again please and let us know.

**Comment by VitaliiTytarenko-okta** [comment]
[OpenApi PUT method on update](https://github.com/okta/okta-management-openapi-spec/blob/master/dist/spec.yaml#L2765)

**Comment by jeremieLyvoc** [comment]
Ok I didn't make any change to my code and now with the same payload it works. 

I kind of lost but yes that's my bad here.

**Comment by VitaliiTytarenko-okta** [comment]
No worries! Glad to help.
