### ISSUE TITLE
Issue while updating OIDC app

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#657]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I am trying to update an OIDC app inside Okta using the SDK.

I have already created a post on the devforum but nothing so far : https://devforum.okta.com/t/see-json-object-sent-by-okta-sdk-java-on-update/16439

### Expected behavior

I'm creating an OIDC app then editing the returned object to add (with `.put()`) information such as settings or credentials objects. But when doing `.update()` i'm getting the error : `HTTP 400, Okta E0000003 (The request body was not well-formed.)`

```
                        Application oidcApp = OIDCApplicationBuilder.instance()
                                .setName(name)
                                .setLabel(label)
                                .setGrantTypes(grantTypes)
                                .setResponseTypes(responseTypes)
                                .setApplicationType(applicationType)
                                .setTokenEndpointAuthMethod(authenticationMethod)
                                .setRedirectUris(redirectUris)
                                .buildAndCreate(okta);

                        oidcApp.put("status", status);
                        oidcApp.put("accessibility", accessibility);
                        oidcApp.put("visibility", visibility);
                        oidcApp.put("licensing", licensing);
                        oidcApp.put("features", features);
                        oidcApp.put("signOnMode", signOnMode);

                        oidcApp.put("credentials", credentials);
                        oidcApp.put("settings", settings);

                        Gson gson = new Gson();
                        String json = gson.toJson(oidcApp);
                        System.out.println(json);

                        oidcApp.update();
```

But if i transform my `oidcApp` object into a JSON String and send this to Okta with PUT /apps/{appId}, it works as planned. So I'm thinking that the oidcApp is wrong or the .update() function, but as there is no way to see what's sent to Okta I don't know.

### SDK Version

5.0.0

**Comment by VitaliiTytarenko-okta** [comment]
Hi @jeremieLyvoc,
I'm here to help.
I will investigate this issue and get back to you with details shortly.

**Comment by VitaliiTytarenko-okta** [comment]
Can't reproduce it.
Your payload works well. App updates successfully. No exceptions.
There are few restrictions: **do not update** _application ID_, _"client_id"_ and _"application_type"_.
Check the `credentials.userNameTemplate.template` value very carefully. It is very likely that your "not well-formed" error might have been caused by an invalid template.
If you still see this error then check the other parameters.
If after that you still have questions feel free to reopen this thread and attach a detailed example with all parameters and steps or reproduce.
