### ISSUE TITLE
Support client credentials flow with shared secret

### ISSUE THREAD

**Issue by garantir-km** [okta/okta-sdk-java#669]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [x ] bug report
  - [ ] feature request

### Background info
I am attempting to construct a Client using the client credentials flow but I am getting an invalid token error. I retried copying the token and I still get an error. I am assuming that the code I am using does the client credentials flow for me behind the scenes.

Describe your issue or request here (if necessary).

### Expected behavior

Authentication should have succeeded and returned a valid Client.

### What went wrong?

Received the following error: com.okta.sdk.resource.ResourceException: HTTP 401, Okta E0000011 (Invalid token provided), ErrorId oaewncSg1yBRvyNXCb-mDG9NA

### Steps to reproduce

```
  private static Client getClient(String url, String clientID, String secret) {
		return Clients.builder()
			    .setOrgUrl(url)
			    .setClientId(clientID)
			    .setScopes(new HashSet<>(Arrays.asList("okta.users.read", "okta.groups.read")))
			    .setClientCredentials(new TokenClientCredentials(secret))
			    .build();
	}
```

### SDK Version
6.0.0

**Comment by sergiishamrai-okta** [comment]
Hi @garantir-km,
Thanks for your question. I'll check this and back to you soon.

**Comment by arvindkrishnakumar-okta** [comment]
Internal Ref: OKTA-446500

**Comment by garantir-km** [comment]
I modified the code as shown below but still am running into issues. It looks as though the code only supports the client credentials flow using a private key, but not using a shared secret. Does that sound correct?

```
private static Client getClient(String url, String clientID, String secret) {
	ClientConfiguration config = new ClientConfiguration();
	config.setApiToken(secret);
	config.setClientId(clientID);
	config.setBaseUrl(url);
	config.setBaseUrlResolver(new BaseUrlResolver() {

		@Override
		public String getBaseUrl() {
			return url;
		}
		
	});
	Set<String> scopes = new HashSet<>();
	scopes.add("okta.users.read");
	scopes.add("okta.groups.read");
	config.setScopes(scopes);
	
	AccessTokenRetrieverServiceImpl  accessTokenRetriever = new AccessTokenRetrieverServiceImpl(config);
	
	return Clients.builder()
			.setOrgUrl(url)
			.setClientId(clientID)
			.setScopes(new HashSet<>(Arrays.asList("okta.users.read", "okta.groups.read")))
			.setClientCredentials(new OAuth2ClientCredentials(accessTokenRetriever))
			.build();
}
```

This errors out with a NPE as it tries to read a private key to sign a JWT with.

Exception in thread "main" java.lang.NullPointerException
	at com.okta.sdk.impl.util.ConfigUtil.hasPrivateKeyContentWrapper(ConfigUtil.java:32)
	at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getPemReader(AccessTokenRetrieverServiceImpl.java:181)
	at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.createSignedJWT(AccessTokenRetrieverServiceImpl.java:139)
	at com.okta.sdk.impl.oauth2.AccessTokenRetrieverServiceImpl.getOAuth2AccessToken(AccessTokenRetrieverServiceImpl.java:91)
	at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.eagerFetchOAuth2AccessToken(OAuth2ClientCredentials.java:44)
	at com.okta.sdk.impl.oauth2.OAuth2ClientCredentials.<init>(OAuth2ClientCredentials.java:37)

**Comment by garantir-km** [comment]
Understood. Is there any plan to support client credentials flow with shared secret anytime soon? We have a customer that wants to use Okta's Universal Directory but support for this is required in order to move forward.

**Comment by arvindkrishnakumar-okta** [comment]
This is something I do not have an answer and I'll need to check with internal team.

**Comment by arvindkrishnakumar-okta** [comment]
Will be closing this issue as there are no plans to support this feature.
