### ISSUE TITLE
Project is set to use Java 1.5

### ISSUE THREAD

**Issue by nicdoye** [okta/okta-sdk-java#68]
Changing `okta-aws-cli.iml` to have `LANGUAGE_LEVEL="JDK_1_8"` and `compiler.xml`  as follows will allow it to build and run against `aws-java-sdk-1.11.128.jar`. I've not tested it thoroughly, yet.

```    
    <bytecodeTargetLevel>
      <module name="okta-aws-cli" source="1.8" />
      <module name="okta-aws-cli" target="1.8" />
    </bytecodeTargetLevel>
```

**Comment by bdemers** [comment]
I'm working on the next version of the SDK, it will be targeting 1.8

**Comment by bdemers** [comment]
Current version uses 1.8
