### ISSUE TITLE
Maven package cannot update from 5.x.x to 6.x.x

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#688]
### Describe the bug?

Hi,

I'm trying to update from 5.x.x to last version, but I tried first to upgrade to 6.x.x.

When updating the 3 dependencies to this version I cannot build/compile anymore inside IntelliJ, I'm getting the following error : 
`java: package com.okta.sdk.client does not exist`

As you can see on the following screenshot, it does exist when going to the external librairies : 
![image](https://user-images.githubusercontent.com/75320820/148393672-a0e29c26-e4e1-49cb-bbdb-5cf52abc11b9.png)

I've tried all following commands without success and also clear cache of the IDE : 

`
mvn install
mvn compile
mvn dependency:purge-local-repository
mvn idea:idea
`

I cannot see why this is blocking here

### What is expected to happen?

Project should compile

### What is the actual behavior?

Project cannot build

### Reproduction Steps?

Here is my pom.xml 

`

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.lyvoc</groupId>
    <artifactId>interne-backup-awslambda</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <aws-lambda-java-core.version>1.2.1</aws-lambda-java-core.version>
        <aws-lambda-java-events.version>3.10.0</aws-lambda-java-events.version>
        <okta.version>6.0.0</okta.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>${aws-lambda-java-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>${aws-lambda-java-events.version}</version>
        </dependency>

        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-api</artifactId>
            <version>${okta.version}</version>
        </dependency>

        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-impl</artifactId>
            <version>${okta.version}</version>
        </dependency>

        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-httpclient</artifactId>
            <version>${okta.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.8</version>
        </dependency>

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20210307</version>
        </dependency>

        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.17.1</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.3</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            
        </plugins>
    </build>
</project>

`

### Java Version

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### SDK Version

6.0.0

### OS version

BuildNumber  Caption                       OSArchitecture  Version
22000        Microsoft Windows 11 Famille  64-bit          10.0.22000

**Comment by bdemers** [comment]
Does the project compile on the command line outside of IntelliJ?

I ❤️ IntelliJ, but at some point in the past I noticed the auto-updating of Maven projects didn't work reliably for me, so I'm now in the habit of "reimporting/refreshing" the Maven project.

For this report, let's remove the IntelliJ/IDE from the equation and just focus on the Maven build.

Keep us posted!

**Comment by jeremieLyvoc** [comment]
`mvn package` commands works so it seems indeed that the error comes from IntelliJ itself...

**Comment by bdemers** [comment]
Thanks for following up @jeremieLyvoc!

I'd suggest following up with JetBrains, feel free to link the issue back here if you do!

**Comment by jeremieLyvoc** [comment]
Sure thing, thanks !
