### ISSUE TITLE
Invalid certification path - Use own keystore

### ISSUE THREAD

**Issue by P1ll3P4ll3** [okta/okta-sdk-java#694]
### Describe the bug?

We are getting an exception about an invalid certification path trying to connect to our Okta URL via the Okta Java SDK.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

How is it possible to set a TrustManager/SSLContext at the Client or ClientBuilder with own CA certificates?

### What is expected to happen?

Possibility to set an own Keystore or TrustManager.

### What is the actual behavior?

No method found to set the Keystore or TrustManager.

### Reproduction Steps?

Nothing to reproduce.

### Java Version

1.8

### SDK Version

1.8

### OS version

Linux

**Comment by bdemers** [comment]
Thanks for reaching out @P1ll3P4ll3!

Can you include the full stacktrace and the output from `java -version`

Are you using an older version of Java 1.8 that doesn't have updated root certificates?

**Comment by P1ll3P4ll3** [comment]
It is just about that an option/method is missing on how to set a custom SSLContext with own TrustManagers/Keystores. I could not find anything like that. It is possible to add these CA´s to the local keystore of the JDK, then it works, but in the environment we are using it this is not an option and not possible. We have to use our own CA keystore.

2022 02 09 13:40:06#+00#ERROR#com.okta.sdk.impl.ds.DefaultDataStore##erdopsadmin#https-jsse-nio-8041-exec-9#na#l3zfearu4v#erddev#web#l3zfearu4v#na#na#na#na#DataStore is not ready com.okta.commons.http.HttpException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.okta.commons.http.httpclient.HttpClientRequestExecutor.executeRequest(HttpClientRequestExecutor.java:185)
	at com.okta.commons.http.RetryRequestExecutor.doExecuteRequest(RetryRequestExecutor.java:147)
	at com.okta.commons.http.RetryRequestExecutor.executeRequest(RetryRequestExecutor.java:120)
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:469)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$2(DefaultDataStore.java:213)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:225)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:181)
	at com.okta.sdk.impl.client.DefaultClient.listApplications(DefaultClient.java:236)
	at com.okta.sdk.impl.ds.DefaultDataStore.isReady(DefaultDataStore.java:615)
	at com.okta.sdk.impl.client.BaseClient.isReady(BaseClient.java:136)
...

**Comment by P1ll3P4ll3** [comment]
This is not about adding a certificate to the keystore or using the standard keystore. It must be possible to set an own keystore via SSLContext because in the cloud environment we are not able/allowed to add other certificates to the keystore. The application is executed in a cloud environment. We have no permission to the keystore used there.
So as already said this is not about the local development or the local JDK with its keystore (we can add the CA certificate there and it works).

**Comment by bdemers** [comment]
We do not expose the SSL Context directly, but one option is to set the keystore programmatically, with a system property:
(at runtime you can call `System.setProperty("javax.net.ssl.keyStore")`
https://docs.oracle.com/javadb/10.8.3.0/adminguide/cadminsslclient.html

**Comment by P1ll3P4ll3** [comment]
This is as well not an option. We must be able to set our own keystore/TrustManager. Otherwise we cannot use the API. It should be possible to somehow inject another TrustManager or KeyStore.

**Comment by bdemers** [comment]
You can implement your own [`RequestExecutor`](https://github.com/okta/okta-commons-java/blob/master/http/http-api/src/main/java/com/okta/commons/http/RequestExecutor.java) 

Take a look at our HttpClient implementation: https://github.com/okta/okta-commons-java/tree/master/http/httpclient/src/main/java/com/okta/commons/http/httpclient
Or the OK HTTP one: https://github.com/okta/okta-commons-java/tree/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp

**Comment by P1ll3P4ll3** [comment]
Thank you for your proposal and sorry for the late reply. This doesn´t help either. 

I just had a look at those two classes you mentioned above. In our case we would have to rebuild all the classes of the Okta implementation of HttpClientRequestExecutor or OkHttpRequestExecutor to be able to get access to the client builder and to set the SslContextFactory. This means copy & paste all the classes inside those packages (some of them are declared package private) just to be able to set the SslSocketFactory with an own SslContext to be able to use our own TrustManager / KeyStore.
We would also have to reference on of the lower okta modules directly in our pom like which is not recommended:
`<dependency>
			<groupId>com.okta.commons</groupId>
    		<artifactId>okta-http-httpclient</artifactId>
    		<version>1.3.0</version>
		</dependency>`

Is all this effort wanted and even worth of just injecting an own TrustManager/KeyStore? Even the effort it took me to clone the Okta GIT repos and analyze the coding.

It should be easily possible to set an own TrustManager or SslSocketFactory like this (found this in one of the classes):
`TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance();
    	TrustManagerFactory.getDefaultAlgorithm());
    	trustManagerFactory.init((KeyStore) null);
    	TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
    	
    	if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) 
    	{
    		throw new IllegalStateException("Unexpected default trust managers:"
    				+ Arrays.toString(trustManagers));
    	}
    	X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
    		
    	SSLContext sslContext = SSLContext.getInstance("TLS");
    	sslContext.init(null, new TrustManager[] { trustManager }, null);
    	SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
    	
    	OkHttpClient client = new OkHttpClient.Builder()
			.sslSocketFactory(sslSocketFactory, trustManager)
			.build();`

This is an important feature missing here.

Is there any easy way on how to get this done in the current implementation?

**Comment by bdemers** [comment]
Another potential workaround is to use the `OkHttpRequestExecutorFactory` directly, similar to what you described above.
https://github.com/okta/okta-commons-java/blob/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp/OkHttpRequestExecutorFactory.java#L47

Something like:

```java
Clients.bulider()
    .setRequestExecutorFactory(new OkHttpRequestExecutorFactory(yourOkHttpClient))
    .build();
```

https://github.com/okta/okta-sdk-java/blob/master/api/src/main/java/com/okta/sdk/client/ClientBuilder.java#L443


I do want to caution you in general, it sounds like the root cause of this problem is running on an older JVM. And you may be stuck on an older JVM that is no longer receiving security updates. 
> You cannot build secure applications on top of insecure systems.

**Comment by P1ll3P4ll3** [comment]
The JVM is not outdated. We are running in an environment where we are not able to set the certificates or update the default keystore.
In general: There are a lot of other use cases that require the use of an own keystore e.g. with custom/internal CA certificates only.

I just checked your last proposal. This is not an option as well because we would have to create our own OkHttpClient. The original OkHttpClient is implemented in groovy. So how can we access the implementation or the interface of OkHttpClient in our Java environment by just using the Okta Java SDK? What exactly is needed for an own implementation of OkHttpClient?

One possible way would be to extend the class OkHttpClient or use it directly and pass SslSocketFactory with our own keystore to it. As long as the class OkHttpClient is not accessible by using the Okta SDK, this is not an option as well.

We would have to use below artifact directly:
```
<groupId>com.okta.commons</groupId>
    		<artifactId>okta-http-httpclient</artifactId>
    		<version>1.3.0</version>
```

I think our requirement is clear. This is a missing feature,

**Comment by JayNewstrom** [comment]
@P1ll3P4ll3 using `OkHttpClient` is here: https://github.com/okta/okta-commons-java/blob/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp/OkHttpRequestExecutor.java (note this is in java)

Feel free to copy into your project, and modify to your needs.

You can see how to add `SslSocketFactory` here: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/ssl-socket-factory/

You'd just add a call to this on line 80 of the copied `OkHttpRequestExecutor`. `clientBuilder.sslSocketFactory(..., ...);`

The HTTP system in the SDK is pluggable for this exact use case! I hope this is clear that we do support your request!

**Comment by JayNewstrom** [comment]
Actually, you don't even need to copy our source into your project. It's just a matter of creating the OkHttpClient and passing it to the Okta builder like Brian mentioned.
Here's the complete code you need, other than the `TrustManager` and `SSLSocketFactory`, which you've already posted above.

```java
OkHttpClient okHttpClient = OkHttpClient.Builder()
    .sslSocketFactory(..., ...)
    .build();
Clients.bulider()
    .setRequestExecutorFactory(new OkHttpRequestExecutorFactory(okHttpClient))
    .build();
```
