### ISSUE TITLE
getApplication("ID") does not work when application is disabled

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#696]
### Describe the bug?

Hi,

I have encountered an issue using the `getApplication()` function to get an app data but getting it by its ID doesn't seems to work when the application is disabled (INACTIVE).

 `Application app = okta.getApplication(appId);` --> This throws a HTTP 404, Okta E0000007 error.

The application does exist and match the ID searched, I double checked with API using Postman and also I used the `listApplications()` function and as you can see on the screenshot the ID I'm looking for exists (0oa3luer53M7NQgoE0x7) 

![image](https://user-images.githubusercontent.com/75320820/153438912-c35aa9d4-f3df-4016-9b4b-e719cf171b76.png)

### What is expected to happen?

Application is supposed to be found

### What is the actual behavior?

HTTP 404, Okta E0000007 error

### Reproduction Steps?

Test `getApplication("ID)` function

### Java Version

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### SDK Version

8.0.0

### OS version

BuildNumber  Caption                       OSArchitecture  Version
22000        Microsoft Windows 11 Famille  64-bit          10.0.22000

**Comment by arvindkrishnakumar-okta** [comment]
@jeremieLyvoc Thanks for raising this! We will investigate this further.
