### ISSUE TITLE
UserFactor does not give the flexibility to get a user's sms and phone number on record

### ISSUE THREAD

**Issue by jjeanj1** [okta/okta-sdk-java#709]
### Describe the feature request?

I'm trying to get the SMS or Email factor value for a user and I'm not able to find a method to pull the profile which contains the registered phone number.

User oktauser = client.getUser(username);
UserFactorList` factors = oktauser.listFactors();

//Listing MFA Factors available for the user
	for (UserFactor f : factors) {
	  System.out.println("SMS Factor Phone: " + f);
       }

only the following methods are available:
https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/factor/UserFactor.html
			
				

### New or Affected Resource(s)

None

### Provide a documentation link

https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/factor/UserFactor.html

**Comment by arvindkrishnakumar-okta** [comment]
@jjeanj1 Thanks for posting!

Not sure if I understand what you desire to do here. Are you trying to pull the user profile information from the `UserFactor` object? Did you already read the documentation for `Factors` API [here](https://developer.okta.com/docs/reference/api/factors/#factor-operations) and trying to point out that some method is missing in the SDK? Please clarify!

**Comment by jjeanj1** [comment]
> @jjeanj1 Thanks for posting!
> 
> `CallUserFactor` and `SmsUserFactor` are subclasses of `UserFactor` and you should be able to pull the profile info from it using `getProfile()` method. This profile object will contain the phone number that you're looking for:
> 
> ```
> if (userFactor instanceof CallUserFactor) {
>     CallUserFactor callUserFactor = (CallUserFactor) userFactor;
>     System.out.println("Phone No: " + callUserFactor.getProfile().getPhoneNumber());
> }
> 
> if (userFactor instanceof SmsUserFactor) {
>     SmsUserFactor smsUserFactor = (SmsUserFactor) userFactor
>     System.out.println("Phone No: " + smsUserFactor.getProfile().getPhoneNumber());
> }
> ```
> 
> Please refer to https://developer.okta.com/docs/reference/api/factors/#get-started-with-the-factors-api for the entire set of possible operations on Factors API.
> 
> Let me know if that helps.

**Comment by jjeanj1** [comment]
This

**Comment by jjeanj1** [comment]
Thanks for the input. This is working now as per your recommendation. Are there any plans to make this less ambiguous?

**Comment by arvindkrishnakumar-okta** [comment]
@jjeanj1 can you detail more on what you think is ambiguous here?

**Comment by jjeanj1** [comment]
> User oktauser = client.getUser(username); UserFactorList` factors = oktauser.listFactors();
> 
> //Listing MFA Factors available for the user for (UserFactor f : factors) { System.out.println("SMS Factor Phone: " + f); }

I was expecting that I would be able to get the phone number by doing:

User oktauser = client.getUser(username);
UserFactorList` factors = oktauser.listFactors();

//Listing MFA Factors available for the user
for (UserFactor f : factors) {
System.out.println("SMS Factor Phone: " + f.getProfile().getPhoneNumber()); //expected
}

The same way I'm able to get the FactorType
for (UserFactor f : factors) {
System.out.println("Factor Type: " + f.getFactorType()); 
}

**Comment by jjeanj1** [comment]
Solution provided by @arvindkrishnakumar-okta is working.
