### ISSUE TITLE
Client.listUsers() doesn't include deactivated users by default.

### ISSUE THREAD

**Issue by er1c** [okta/okta-sdk-java#718]
### Describe the bug?

https://developer.okta.com/okta-sdk-java/development/apidocs/com/okta/sdk/client/Client.html#listUsers--

This is either a documentation issue, or a bug, but I was expecting a full list of users to sync against, regardless of the activation status.

### What is expected to happen?

List all users

### What is the actual behavior?

Lists only activated or staged users.

### Reproduction Steps?

Should be straight forward, simply deactivate a user and call client.listUsers(), the size will be minus one.

### Java Version

openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

### SDK Version

8.1.0

**Comment by laura-rodriguez** [comment]
Thanks for reporting this issue @er1c ! Someone from our team will review it soon.

**Comment by bdemers** [comment]
@er1c I found the relevant doc on the API itself: https://developer.okta.com/docs/reference/api/users/#list-all-users
By default, it lists all non `DEPROVISIONED` users.

Listing all users can be achieved by setting `search` to `status pr`.

This note should be added to the relevant javadoc (and API spec) for the `listUsers()` method

**Comment by arvindkrishnakumar-okta** [comment]
@er1c I believe this can be closed, please reopen if you need further followup.

**Comment by er1c** [comment]
@arvindkrishnakumar-okta perhaps rename this to a documentation enhancement?

**Comment by arvindkrishnakumar-okta** [comment]
Internal Ref: OKTA-484471
