### ISSUE TITLE
Can't update user profile if status is set to DEPROVISIONED

### ISSUE THREAD

**Issue by er1c** [okta/okta-sdk-java#721]
### Describe the bug?

Reference: https://gist.github.com/er1c/cc8af49bcb67bd57af8565b6c5ff5345

### What is expected to happen?

I would expect to be able and keep even de-activated users in sync.

### What is the actual behavior?

```
[error] com.okta.sdk.resource.ResourceException: HTTP 404, Okta E0000007 (Not found: Resource not found: 00u3cw9vpy6nBOz771d7 (User)), ErrorId oaeAuWNFw1kQY-4nnEavuxb-A
[error] 	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:488)
```

### Reproduction Steps?

See description

### Additional Information?

This happens on  both `oktaUser.deactivate(false)` and `oktaUser.update()` if the user status is set to DEPROVISIONED.  I suspect this is an issue in the REST API

### Java Version

openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu11.54+23-CA (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+23-CA (build 11.0.14+9-LTS, mixed mode)

### SDK Version

8.1.0

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for your post!

Can you list the sequence of API calls you’re making?

**Comment by arvindkrishnakumar-okta** [comment]
I believe the update of user profile can only be done if the user is in provisioned state. I would double check/verify this with the backend API teams soon. In any case, I need to understand why you get a 404/Resource Not Found error. Can you list down the sequence of API steps for me to reproduce this?

**Comment by er1c** [comment]
@arvindkrishnakumar-okta it's in the gist

**Comment by arvindkrishnakumar-okta** [comment]
Update: The 404/Resource Not Found error you get while trying to update user profile of a deactivated user (API status "Deprovisioned") is expected and by design.

**Comment by er1c** [comment]
I wouldn't call this "by design" but maybe "bad design"?  Equally bad experience in the Okta UX:

![image](https://user-images.githubusercontent.com/64685/166494314-fab53982-bd9c-4924-9c3b-6915c6383218.png)

**Comment by arvindkrishnakumar-okta** [comment]
@er1c Thanks for the report on the UX. 

Request you to reach out to support@okta.com with this feedback.
