### ISSUE TITLE
OAuth2 Docs on pem JWK => PEM

### ISSUE THREAD

**Issue by er1c** [okta/okta-sdk-java#735]
### Describe the feature request?

For the docs section it took me longer than it should have to figure out the generation of the `.pem` file this could probably be pretty easy to better explain getting the oauth2 JWK/npm program and generating the .pem file.  Or at least make a more explicit note about following the explicit directions at https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/#generate-the-jwk-using-the-api and the converter tool

### New or Affected Resource(s)

README.md

### Provide a documentation link

https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/#generate-the-jwk-using-the-api

**Comment by arvindkrishnakumar-okta** [comment]
@er1c Thanks for the feedback!

We will get the README updated.
