### ISSUE TITLE
Add ability to set x-forwarded-for header without using .http() "other requests" method

### ISSUE THREAD

**Issue by patrick-m-m** [okta/okta-sdk-java#739]
### Describe the feature request?

We have a java service that is acting as middleware between our web & mobile clients and the Okta APIs for user data. We are interested in setting the x-forwarded-for header for several API calls that use SSWS authentication through the Java SDK. Example operations our user complete through this middleware API are: viewing profile data; changing password and/or email; adding, removing and verifying Auth Factors. Okta team member bdemers replied to a [dev forum inquiry](https://devforum.okta.com/t/okta-java-sdk-set-request-header-retrieve-response-header/16668/4) about this capability and provided this sample code:

```
User user = client.http()
    .setBody(yourUserObject)
    .addHeaderParameter("x-forwarded-for", "ip-address")
    .post("/api/v1/users/<user-id>", User.class);
```

Using the `.http()` helper in this way removes a lot of the convenience of having an SDK at all. bdemers also suggested I make a feature request to add custom header handling for regular resource requests. So here I am :-)

It would be much cleaner to be able to set headers on SDK resource handlers as they are designed. Something like this:

```
      Map<String, String> headers = new HashMap<>();
      headers.put("x-forwarded-for", ipAddress);

      User oktaUser = oktaClient.getUser(userId, headers);

      oktaUser.getProfile().setDisplayName(updateMemberProfileInput.getUsername());
      oktaUser.update(headers);
```

Even better would be a set-and-forget mechanism that handles the header population away from the point of operations. I'm thinking of something like the [Spring Framework ClientHttpRequestInterceptor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/ClientHttpRequestInterceptor.html) pattern, where the header configuration is initialized once for the client instance and calls to individual client methods don't need to repeatedly retrieve and set the IP Address header. I'm not sure what an equivalent pattern would be in the http client library underlying the okta-java-sdk (okhttp?), but hopefully the Spring example makes some sense.

Please let me know if I wasn't clear enough about anything. Thanks for reading!

### New or Affected Resource(s)

As this is for a header and not a specific resource, I think the "New or Affected Resource(s)" is/are either "All" or "None". Perhaps it would be useful to say the [ClientBuilder](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/client/ClientBuilder.html) is the affected resource?

### Provide a documentation link

https://developer.okta.com/docs/reference/core-okta-api/#ip-address has the information about how Okta APIs handle "x-forwarded-for" headers.

**Comment by arvindkrishnakumar-okta** [comment]
@patrick-m-m Thanks for the post!

We will address this in our upcoming work plan.

**Comment by arvindkrishnakumar-okta** [comment]
@patrick-m-m Apologies for the long delay. Things have changed a lot since my last comment. 

With the latest SDK version `11.0.0`, you can populate your custom HTTP header while you initialize the `ApiClient` object.

```
ApiClient client = Clients.builder().build();
client.addDefaultHeader("x-forwarded-for", "ip-address");

UserApi userApi = new UserApi(client);
userApi.listUsers(..);

UserApi userApi = new UserApi(client);
userApi.listUsers(..);

GroupApi groupApi = new GroupApi(client);
groupApi.listGroups(..);
```

The custom header added to the client gets applied across all resource APIs. 

Let me know if you have any questions.

**Comment by arvindkrishnakumar-okta** [comment]
This ticket will be closed due to inactivity, feel free to reopen if necessary.
