### ISSUE TITLE
ClientBuilder - order of setters matters

### ISSUE THREAD

**Issue by er1c** [okta/okta-sdk-java#740]
### Describe the bug?

This works:

``` 
  val builder = Clients.builder()
    .setOrgUrl(config.tokenEndpoint.baseURI.toString) // e.g. https://evenfinancialapp.oktapreview.com
    .setAuthorizationMode(AuthorizationMode.PRIVATE_KEY)
    .setClientId(privateKeyCreds.clientId)
    .setPrivateKey(privateKeyCreds.privateKey)
    .setScopes(java.util.Set.of(config.scopes:_*))
```

This doesn't:

``` 
  val builder = Clients.builder()
    .setOrgUrl(config.tokenEndpoint.baseURI.toString) // e.g. https://evenfinancialapp.oktapreview.com
    .setScopes(java.util.Set.of(config.scopes:_*))
    .setAuthorizationMode(AuthorizationMode.PRIVATE_KEY)
    .setClientId(privateKeyCreds.clientId)
    .setPrivateKey(privateKeyCreds.privateKey)
```

The "scopes" gets set to an empty set in the former.

### What is expected to happen?

It should work regardless of order.

### What is the actual behavior?

It is order-sensitive.

### Reproduction Steps?

See above

### Java Version

openjdk version "11.0.15" 2022-04-19 LTS

### SDK Version

latest

**Comment by er1c** [comment]
https://github.com/okta/okta-sdk-java/blob/447440a81691e74157610ceeeffadd010d75f91b/impl/src/main/java/com/okta/sdk/impl/client/DefaultClientBuilder.java#L430 This is where the authorization mode is required to be set, before the scopes setter will "work"

**Comment by er1c** [comment]
@JayNewstrom yeah same bad guard pattern for other setters, so just fixed them all.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks much for the PR @er1c 👍🏽
