### ISSUE TITLE
Implement a way to invoke `PATCH` REST API call

### ISSUE THREAD

**Issue by UgoReyne** [okta/okta-sdk-java#742]
### Describe the feature request?

The need is to make a custom patch api request.
Is it possible ?

Thank you

### New or Affected Resource(s)

The Custom Admin Roles ressources, like:
Adding more Members to a Binding
PATCH
/api/v1/iam/resource-sets/${resourceSetId}/bindings/${roleIdOrLabel}/members

**Comment by arvindkrishnakumar-okta** [comment]
@UgoReyne Thanks for posting!

AFAIK, Okta does not expose any public API like the one you mentioned above. 

Please let me know if I am missing something.

**Comment by UgoReyne** [comment]
Thank you for your reply !
It is the API to add members to a binding (https://developer.okta.com/docs/reference/api/roles/#add-more-members-to-a-binding), an API patch method used here. Do you have any idea on how I can make this call ?

**Comment by arvindkrishnakumar-okta** [comment]
Update: It should be possible to invoke `PATCH` similar to other HTTP methods like it is described in https://github.com/okta/okta-sdk-java#call-other-api-endpoints. 

Closing this issue, but feel free to comment if you have any questions.
