### ISSUE TITLE
Support for `limit` query parameter with the `listApplications` API

### ISSUE THREAD

**Issue by bsekar** [okta/okta-sdk-java#743]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [X] feature request

### Background info

Consider an org with 2000 apps. When calling `client.listApplications` without the ability to set `limit`, the API defaults to 20. So, the `listApplications` would require 100 HTTP calls when it can be done using only 10. The API supports a max of 200 for the limit

### Expected behavior

Ability to use the `limit` query parameter when doing `listApplications`. This seems to be supported in most other Okta client SDKs, including swift, golang, dotnet etc. Would be nice to have it supported in Java too.

### Steps to reproduce

Invoke `client.listApplications`

### SDK Version
`8.2.1`

**Comment by arvindkrishnakumar-okta** [comment]
@bsekar Thanks for posting! This will be addressed in the upcoming release.

**Comment by jefftaylor-okta** [comment]
Hello @bsekar! Thanks for the inquiry. We are looking to beta this feature in early August. This will be included with some other enhancements we have been working on.

**Comment by arvindkrishnakumar-okta** [comment]
Update: We now have support for `limit` query param in the latest version of the Java Management SDK (10.0.0).

Please follow these [steps](https://github.com/okta/okta-sdk-java/blob/master/MIGRATING.md#migrating-from-8xx-to-10xx) to take advantage of the latest features. 

Please let me know if you have any issues. Thanks!
