### ISSUE TITLE
Support for configuring Application Provisioning Integration

### ISSUE THREAD

**Issue by dspasojevic** [okta/okta-sdk-java#746]
### Describe the feature request?

Allows the SDK to be used to configuration the SCIM integration to be used for application provisioning. 

### New or Affected Resource(s)

Application

### Provide a documentation link

https://help.okta.com/en-us/Content/Topics/Apps/Apps_App_Integration_Wizard_SCIM.htm
https://developer.okta.com/docs/reference/scim/

### Additional Information?

This is particularly for the management of SCIM provisioning integration withing a SWA / SAML application rather than the management of an "Integration App".

**Comment by laura-rodriguez** [comment]
Hi @dspasojevic, 

Thanks for reporting this. Our team will review it soon and prioritize accordingly.

Internal Ref: OKTA-519228

**Comment by arvindkrishnakumar-okta** [comment]
We do not plan to add SCIM support to the Java Mgmt SDK. The scope of the mgmt SDK is to support Okta management APIs only.

**Comment by arvindkrishnakumar-okta** [comment]
@dspasojevic Thanks for posting! At this point, we do not intend to support this. However, you could use this SDK to invoke the SCIM API endpoints (see https://github.com/okta/okta-sdk-java#call-other-api-endpoints).

Let me know if you have any questions.
