### ISSUE TITLE
Redis Spring Cache usage in SDK

### ISSUE THREAD

**Issue by bcoquard** [okta/okta-sdk-java#754]
### Describe the feature request?

Hello,

In the documentation you can find this : 
> If your application is deployed on multiple JVMs (e.g. a distributed/clustered web app), you might not want to use the builders here and instead implement the [CacheManager](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/cache/CacheManager.html) API directly to use your distributed/clustered cache technology of choice.

How are we supposed to do that when using Spring Boot AND Redis ?
My point is that I run 3 differents Java apps, running on containers which can scale.
I want those containers to share a same Redis Cache.

To do that I am guessing that I need to "extends" the DefaultCache implemented by Okta and override the methods : get / put / remove.

For exemple : 
```
@Autowired
private RedisCacheManager cacheManager;

@Bean
protected Client oktaClient() {
return Clients.builder()
                ...
                .setCacheManager(new CacheManager() {
                    @Override
                    public <K, V> Cache<K, V> getCache(String name) {
                        return new RedisSpringCache(name, cacheManager);
                    }
                })
                ...
                .build();
}
```

```
public class RedisSpringCache<K, V> extends DefaultCache<K, V> {
    private org.springframework.cache.Cache springCache;

    public RedisSpringCache(String name, RedisCacheManager redisCacheManager) {
        super(name);
        springCache = redisCacheManager.getCache(name);
    }

    @Override
    public V get(K key) {
        return (V) springCache.get(key).get();
    }

    @Override
    public V put(K key, V value) {
        springCache.put(key, value);
        return value;
    }

    @Override
    public V remove(K key) {
        V value = (V) springCache.get(key).get();
        springCache.evict(key);
        return value;
    }
}

```

Is there a simpler way to use the Redis Cache managed by Spring ?

For exemple : 
```
@Autowired
private RedisCacheManager cacheManager;

@Bean
protected Client oktaClient() {
return CustomClients.builder()
                ...
                .setCacheManager(cacheManager)
                ...
                .build();
}
```

Any idea is welcomed, I am trying to find the best and easiest solution to maintain.

Thank you.

### New or Affected Resource(s)

com.okta.sdk.cache.CacheManager;
com.okta.sdk.client.Clients;

### Provide a documentation link

Java Doc Sdk Cache :
* https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/cache/Caches.html

### Additional Information?

No

**Comment by bdemers** [comment]
Hello @bcoquard

For Spring Boot support, see: https://github.com/okta/okta-sdk-java#inject-the-okta-java-sdk-in-spring

You won't need to configure anything manually, just set the config properties and then inject the `Client`.
Spring Cache will be used automatically (as long as an implementation is on your classpath).

It looks like we should add a note in our READMEs though, we can keep this issue open to track that.

**Comment by oussamalahlou** [comment]
Hello @bdemers,

In the same context, I realized that the okta spring cache uses a default cache strategy.

Do you have any idea on how to implement a custom cache strategy?

Thanks in advance.

**Comment by bdemers** [comment]
@oussamalahlou is there something specific you are trying to do?

**Comment by oussamalahlou** [comment]
@bdemers 

I am trying to use Springboot and Redis for caching Rest calls to okta API.

I did some tests and realized that it relies on hrefs from backend responses for caching calls to okta API which is not comfortable for my needs.

I would like to know if there is a way to change the default cache strategy to create a custom strategy?

Thanks.

**Comment by bdemers** [comment]
@oussamalahlou can you tell me a little more about what your strategy would be? Maybe I can point you in the right direction?

**Comment by oussamalahlou** [comment]
@bdemers ,

Using the DefaultResourceCacheStrategy class, I see that the cache strategy is based on the response hrefs of the okta backend apis which is not comfortable for my project, how can we create our custom strategy?

Also, for example, when I call the following okta web service: /api/v1/users/{userId} knowing that userId = login,
i find in the key cache the userId passed as a query parameter is replaced by the user's okta id, is it normal?

Another remark, I see that the collections of the small sizes have not been put in the cache, like for example: the groups of the users, according to you, how can we fix that?

Thanks.

**Comment by bdemers** [comment]
Ahh, I think I see what you are getting at.
Users are a special case where you can look them up by login/email or by id.
There is a related issue for this: #265
IIRC the plan was to add two cache keys for those objects (one based on the id, and the other based on the login/email)
Possibly having the login/email based cached be some sort of object that points to the canonical id-based entry.

There is also another issue for collection caching #328 
There are lots of edge cases that make it hard to come up with a generic solution.
* Some collections return objects that do not contain all of their properties (IIRC)
* Cache invalidation - Any time an object that might be contained in a collection is mutated, each of those cached collections would need to be updated, or the whole collection invalidated.
* Results of a collection search/filter will change on average faster than an individual cached item
* Collections should be VERY large, for example, you could stream through a million user objects, but that may be too much content for your cache

Of these two, the multiple cache keys issue is something that could be resolved, however swapping out the cache simple isn't something that is exposed in the SDKs API.  But it is something that could be resolved with a pull request 😄 

For collection caching, I'd probably suggest doing something at the application level, as you could be more focused in your strategy.  It's possible you could just wrap a couple of the SDKs methods and annotate them with `org.springframework.cache.annotation.Cacheable`

I understand that doesn't scale for general solutions, but if you are just a couple of specific API calls, it might be an easy win.

Does that help?

**Comment by oussamalahlou** [comment]
It's clear, thank you @bdemers
