### ISSUE TITLE
No way to set the `limit` on `getLogs` 

### ISSUE THREAD

**Issue by sgadde25** [okta/okta-sdk-java#756]
### Describe the bug?

It looks like there is no way to set the limit on the method getLogs in the Java SDK. By default the limit is set to 100. To avoid making multiple calls, we need the ability to set the limit to 1000. This is available in the APIs but not SDK.
SDK link: https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/log/class-use/LogEventList.html

### What is expected to happen?

Need param or option to set the limit on the method getLogs.

### What is the actual behavior?

Won't be able to set limit on the method getLogs on the Java SDK and it is 100 by default.

### Reproduction Steps?

Make a get call using Client.getLogs(Date since, Date until, String filter, String q, String sortOrder) for any given date and see the events it is fetching on each iteration in the Okta backend.

### Java Version

jdk1.8.0_211

### SDK Version

4.0.0

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for reporting this. 

We will get this fixed in upcoming release. Stay tuned!

**Comment by arvindkrishnakumar-okta** [comment]
Update: We now have support for this in the latest version of the Java Management SDK (10.0.0).

Please follow these [steps](https://github.com/okta/okta-sdk-java/blob/master/MIGRATING.md#migrating-from-8xx-to-10xx) to take advantage of the latest features. Please let me know if you have any issues. Thanks!
