### ISSUE TITLE
UserBuilder can't create custom attributes SDK 10.0.0

### ISSUE THREAD

**Issue by StevenMaMei** [okta/okta-sdk-java#783]
### Describe the bug?

In the SDK 8.x.x you could use .setProfileProperties(...) to insert custom attributes created as part of the profile. However, with this SDK there is no way to specify custom attributes/properties using UserBuilder. If you want to specify these custom properties, then you should create directly the CreateUserRequest

### What is expected to happen?

I expect to have a way to specify custom attributes

### What is the actual behavior?

There is no way to specify custom attributes when creating a user using the UserBuilder

### Reproduction Steps?

Use SDK 10.0.0

### Java Version

N.A

### SDK Version

10.0.0

**Comment by arvindkrishnakumar-okta** [comment]
Note: This is related to #788

**Comment by arvindkrishnakumar-okta** [comment]
https://github.com/okta/okta-sdk-java/pull/817 should address this.
