### ISSUE TITLE
Unable to create a PasswordPolicy with SDK version 10.0.0

### ISSUE THREAD

**Issue by regina-venable-wex** [okta/okta-sdk-java#784]
### Describe the bug?

When using the PasswordPolicyBuilder to create a new PasswordPolicy, it fails with the message: "PolicyType should be 'PASSWORD', please use PolicyBuilder for other policy types".

The DefaultPasswordPolicyBuilder class has a bug on line 244 where it compares a PolicyType object to a String "PASSWORD" with an equals(). This will always return false - and throw the exception.

`        if (policyType.equals("PASSWORD"))
            policy.setType(policyType);
        else
            throw new IllegalArgumentException("PolicyType should be 'PASSWORD', please use PolicyBuilder for other policy types.");
`

Compare the above logic to the same kind of if statement in the DefaultOktaSignOnPolicyBuilder class (line 75).

`       if (PolicyType.OKTA_SIGN_ON.equals(policyType))
            policy.setType(policyType);
        else
            throw new IllegalArgumentException("PolicyType should be 'OKTA_SIGN_ON', please use PolicyBuilder for other policy types.");
`

### What is expected to happen?

The PasswordPolicyBuilder.buildAndCreate() method should not throw an exception when the  PolicyType passed in (or set by DefaultPasswordPolicyBuilder constructor) is indeed equal to PolicyType.PASSWORD.

### What is the actual behavior?

The PasswordPolicyBuilder.buildAndCreate() method throws an IllegalArgumentException  when the  PolicyType passed in (or set by DefaultPasswordPolicyBuilder constructor) is indeed equal to PolicyType.PASSWORD.

### Reproduction Steps?

My test case:

`
;

    @Test
    void createOktaPasswordPolicy() {
        assertNotNull(oktaApiClient);
        PolicyApi oktaPolicyApi = new PolicyApi(oktaApiClient);
        assertNotNull(oktaPolicyApi);

        PasswordPolicyRecoveryFactorSettings recoveryFactorSettings = new PasswordPolicyRecoveryFactorSettings();
        recoveryFactorSettings.setStatus(LifecycleStatus.ACTIVE);

        Policy createTempPasswordPolicy = PasswordPolicyBuilder.instance()
                .setName(PASS_POLICY_NAME)
                .setDescription(SHARED_DESC)
                .setAuthProvider(PasswordPolicyAuthenticationProviderType.OKTA)
                .setMinLowerCase(1) //Integer but only allow 1. 1 for True and 0 for off/false?
                .setMinUpperCase(1)
                .setMinNumbers(1)
                .setExcludeUserNameInPassword(true) //username --which is the email address.
                .setExcludePasswordDictionary(true) //??? Restrict use of common passwords in beta?
                .setPasswordHistoryCount(6)
                .setPasswordMaxAgeDays(365)
                .setPasswordExpireWarnDays(15)
                .setPasswordMaxAttempts(3)
                .setPasswordAutoUnlockMinutes(15)
                .setShowLockoutFailures(false)
                .setPasswordPolicyRecoveryEmailStatus(recoveryFactorSettings)
                .setPasswordRecoveryOktaSMS(recoveryFactorSettings)
                .setPasswordRecoveryTokenLifeMinutes(60) //lowest is 60
                .setPriority(1) //Make this the main policy. Defaults to 1.
                .buildAndCreate(oktaPolicyApi);

        assertEquals(PASS_POLICY_NAME, createTempPasswordPolicy.getName(), "Good looking policy was created");

        //Create a Rule
        PolicyRule policyRule = new PasswordPolicyRule();
        policyRule.setName(PASS_POLICY_RULE_NAME);
        policyRule = oktaPolicyApi.createPolicyRule(createTempPasswordPolicy.getId(), policyRule);

        List<PolicyRule> policyRules = oktaPolicyApi.listPolicyRules(createTempPasswordPolicy.getId());
        assertNotNull(policyRules, "Password policy rule list is null");
        assertEquals(1, policyRules.size(), "Should only be 1 password policy rule");
        assertNotNull(policyRules.get(0), "Policy rule not found");
        assertEquals(policyRules.get(0).getName(), policyRule.getName());

        // Delete Policy
        oktaPolicyApi.deletePolicy(createTempPasswordPolicy.getId());
        Policy beGone = oktaPolicyApi.getPolicy(createTempPasswordPolicy.getId(), null);
        assertNull(beGone, "Policy was not deleted");
    }
`

### Java Version

❯ java --version
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Homebrew (build 11.0.16.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.16.1+0, mixed mode)

### SDK Version

10.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@regina-venable-wex Thanks for posting! 

PR https://github.com/okta/okta-sdk-java/pull/785 contains the fix, will get this merged.
