### ISSUE TITLE
Not able to set customized properties on user

### ISSUE THREAD

**Issue by dongmei-cao** [okta/okta-sdk-java#788]
### Describe the bug?

We're trying to migrate from 8.2.2 to 10.0.0. Noticed that there is no way to set the custom properties on the user profile, just like what you commented here https://github.com/okta/okta-sdk-java/blob/cb0a648f39f2f7a7c72912d5c19bac0c44102f1e/examples/quickstart/src/main/java/quickstart/Quickstart.java#L84

What is the fix for the putProfileProperty() in version 10.0.0?

### What is expected to happen?

Have a way to set the custom properties on user profile via SDK

### What is the actual behavior?

The putProfileProperty() method is missing on user creation. 

### Reproduction Steps?

You can use your own quickstart example here 

https://github.com/okta/okta-sdk-java/blob/cb0a648f39f2f7a7c72912d5c19bac0c44102f1e/examples/quickstart/src/main/java/quickstart/Quickstart.java#L84

### Java Version

java 11

### SDK Version

okta-sdk-java 10.0.0

**Comment by dongmei-cao** [comment]
Any updates on this bug? We need this feature to move to SDK 10

**Comment by arvindkrishnakumar-okta** [comment]
@dongmei-cao Thanks for posting and sorry for the delay.

You should still be able to set custom profile properties on a User during _update_ (not _create_ - agreed that it should be made available during user creation as well, but in theory you have a workaround presently. We will update the SDK shortly to provide the ability to add custom profile attributes during user creation). 

See https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/UsersIT.groovy#L634-L646

**Comment by arvindkrishnakumar-okta** [comment]
https://github.com/okta/okta-sdk-java/pull/817 should address this.
