### ISSUE TITLE
Compatibility with Spring 6

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-java#794]
### Describe the feature request?

It's currently not possible to run the SDK in a Spring 6 / Spring Boot 3 application, due to incompatible code and HTTP client dependencies.

I've fixed the issue in my own branch ([PR here](https://github.com/clementdenis/okta-sdk-java/pull/1)), but I won't submit it as you probably want to retain Spring 5 compatibility somehow, which isn't the case here.
Also, it might be better to wait for a new version of the OpenAPI generator that supports Spring 6 (it should be fixed by [there](https://github.com/OpenAPITools/openapi-generator/issues/14276)), to avoid customizing the handlebars templates as I did.

### New or Affected Resource(s)

All

**Comment by arvindkrishnakumar-okta** [comment]
We've moved away from Spring Boot (2.x) and Spring 5 dependencies from SDK release 11.0.0. 

In this effort, we've replaced Spring Rest Template with Apache HttpClient5. 

Therefore, compatibility with Spring should no longer be an issue.  

Let me know if that helps!

**Comment by clementdenis** [comment]
Hi @arvindkrishnakumar-okta ,

It's definitely a good move to depend on a lower-level API than Spring for the generated client.
The other good news is that the auto-pagination is gone (related to #863).
But the list*WithPaginationInfo methods are also gone, which means **we can't paginate at all with this version** ...
Should I open a new ticket for this?

Also, the main exception type ResourceException was changed to ApiException, which is a checked exception => is there a good reason for that? This is a major disruption to existing code base, especially when using lambda extensively (which I do). It's something that should be at least mentioned in the migration guide.

PS: couldn't you release alpha / beta version of the client to fix this kind of major issues before releasing the first "GA" version? I'll be willing to test this early versions.

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks for your feedback!

We definitely considered a alpha/beta version initially but later decided to go with a GA version per internal product guidelines. 

I'll work on getting more details into the migration guide/changelog to be as helpful as possible. 

Meanwhile, please try out the SDK and I'd be happy to hear more feedback.

**Comment by clementdenis** [comment]
As mentioned before, I've tried it, but definitely can't use it until pagination is back ...

**Comment by arvindkrishnakumar-okta** [comment]
Will mark this issue resolved, pagination will be addressed in https://github.com/okta/okta-sdk-java/issues/884
