### ISSUE TITLE
SDK 10.0.0 returns the http status code for com.okta.sdk.error.getCode() instead of the Okta errorCode as with prior SDK versions

### ISSUE THREAD

**Issue by emanor-okta** [okta/okta-sdk-java#797]
### Describe the bug?

As of 10.0.0 com.okta.sdk.error.getCode() is now returning the http status code (ie 404) instead of the Okta specific errorCode (ie "errorCode": "E0000007")

With 8.x.x and prior versions com.okta.sdk.error.getCode() returned the Okta specific errorCode.

### What is expected to happen?

com.okta.sdk.error.getCode() returns the Okta errorCode ("errorCode": "E0000007")

### What is the actual behavior?

com.okta.sdk.error.getCode() returns the http status (404/etc)

### Reproduction Steps?

```
        UserApi userApi = new UserApi(client);
        try {
            User user = userApi.getUser("postman99@mail.com");
        } catch (Exception e) {
            System.out.println("getLocalizedMessage: " + e.getLocalizedMessage());
            System.out.println(e.getClass().getName());
            System.out.println("getCode(): " + ((com.okta.sdk.error.ResourceException)e).getCode());
            System.out.println("getStatus(): " + (((ResourceException) e).getStatus()));
        }
```

where "postman99@mail.com" is not a valid user in the Org.

with 10.0.0 results,
```
getLocalizedMessage: HTTP 404, Okta 404 (Not found: Resource not found: postman99@mail.com (User)), ErrorId oae8WC7L-klR_u_63LkxgB8vw
com.okta.sdk.error.ResourceException
getCode(): 404
getStatus(): 404
```

with 8.x.x results,
```
getLocalizedMessage: HTTP 404, Okta E0000007 (Not found: Resource not found: postman99@mail.com (User)), ErrorId oaeAmtvzcCLSqyruoj1F1MpFA
com.okta.sdk.resource.ResourceException
getCode(): E0000007
getStatus(): 404
```

### Additional Information?

I haven't tested this but at [this line](https://github.com/okta/okta-sdk-java/blob/master/api/src/main/java/com/okta/sdk/error/ErrorHandler.java#L36) should there be an additional definition of something like,
`static final String ERROR_CODE_PROPERTY = "errorCode";`
Then change [this line](https://github.com/okta/okta-sdk-java/blob/master/api/src/main/java/com/okta/sdk/error/ErrorHandler.java#L68) to something like,
`return String.valueOf(errorMap.get(ERROR_CODE_PROPERTY));`

### Java Version

```
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```

### SDK Version

10.0.0

### OS version

Darwin C02YR68WLVCG 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

**Comment by emanor-okta** [comment]
OKTA-564636 created

**Comment by arvindkrishnakumar-okta** [comment]
Fix merged to `main` branch.
