### ISSUE TITLE
Add possibility to choose Okta Auth Server for Oauth2 authentication method

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#798]
### Describe the feature request?

The SDK today works with the default authorization server when building the `ApiClient` client.

Where configuring it we can only choose the Okta URL domain but not specifically any custom authorization server for example. Which could be : 

```
ApiClient client = Clients.builder()
    .setIssuer("https://{yourOktaDomain}/oauth2/{SERVER_ID}");
    .setAuthorizationMode(AuthorizationMode.PRIVATE_KEY)
    .setClientId("{clientId}")
    .setKid("{kid}") // optional
    .setScopes(new HashSet<>(Arrays.asList("okta.users.manage", "okta.apps.manage", "okta.groups.manage")))
    .setPrivateKey("/path/to/yourPrivateKey.pem")
    .build();
```

### New or Affected Resource(s)

.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

We will review this feature request and get back with an update.

**Comment by arvindkrishnakumar-okta** [comment]
@jeremieLyvoc The Custom AS (Authorization Server) must ideally be used for your own APIs (not Okta's management APIs). Ref https://developer.okta.com/docs/concepts/auth-servers/#which-authorization-server-should-you-use for more insights. 

Only Org AS’s token can be used to access Okta Management APIs, Custom AS's token cannot use Okta Management APIs. 

Hope that helps!

**Comment by jeremieLyvoc** [comment]
Hi,

Thank you that's clear
