### ISSUE TITLE
Cache key implementation seems to be incorrect in invokeApi() method of ApiClient.java 

### ISSUE THREAD

**Issue by sunilchaurha** [okta/okta-sdk-java#804]
### Describe the bug?

I was trying to implement caching for get user operation, but when I test it, I say that in any case cache id deleted for key generated from below code.

RequestEntity<Object> requestEntity = requestBuilder.body(selectBody(body, formParams, contentType));
String cacheKey = requestEntity.getUrl().toString();
if (Objects.nonNull(requestEntity.getUrl().getQuery())) {
   cacheKey = requestEntity.getUrl().toString().split("\\?")[0];
}
if (method == HttpMethod.DELETE) {
cache.remove(cacheKey);
}

String[] uriSegments = uri.getPath().split("/");

// I am using GET method, what is the need to remove cache for generated key??? Even If I set query parameter, then also this code is taking value from zeroth index and in any case uriSegments length will exceed 5 chars and below code will remove cache for generated key.  
// This is incorrect logic I believe

**if (uriSegments != null && uriSegments.length >= 5) {
    String key = getBasePath() + "/" + uriSegments[1] + "/" + uriSegments[2] + "/" + uriSegments[3] + "/" + uriSegments[4];
     if (cache.get(key) != null) {
       cache.remove(key);
       }
}**

if (method == HttpMethod.GET && !returnType.getType().getTypeName().contains("List") &&
                                !(Objects.nonNull(requestEntity.getUrl().getQuery()) && requestEntity.getUrl().getQuery().contains("expand"))) {

    ResponseEntity<T> cacheData = cache.get(cacheKey); 

### What is expected to happen?

Cache should not be deleted in case of get method.

### What is the actual behavior?

It's deleting cache for GET method.

### Reproduction Steps?

Call get user in same flow...   from second call onwards use should be returned from cache.

### Java Version

JDK-11

### SDK Version

JDK-11

### OS version

Windows - 10

**Comment by sunilchaurha** [comment]
Hi @aravindanranganathan-okta, could you please check and suggest.

**Comment by arvindkrishnakumar-okta** [comment]
@sunilchaurha Thanks for reporting and sorry for the delay.

We are forcefully evicting the entry from cache in this case you mentioned, but if you look at code down below, we're updating the cache again with latest info when the next time GET is called.

![image](https://user-images.githubusercontent.com/61501885/217568888-8f369b5c-dd40-4493-884c-4e201edf1b74.png)

This means that the cache is up-to-date with the latest info from backend. 

So, this should not ideally cause any issue.

Are you seeing any issue (or outdated cache?) invoking any particular endpoint?

**Comment by sunilchaurha** [comment]
Thanks @arvindkrishnakumar-okta , I think I was not using the API in right way.  I can now get user from cache, Thanks for response.
