### ISSUE TITLE
Automatic pagination in 10.2.0 should be reverted

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-java#823]
### Describe the bug?

In #806, automatic pagination was added to all paginated methods, with no opt-out.

This breaks many use cases, like when listing users on a domain with lots of them. 

### What is expected to happen?

Pagination should work as before 10.2.0, with possibly additional methods or new parameters to existing methods to enable it.

Ideally, new methods should return an object that can stream the results while not keeping them in memory, like an Iterable or a Java 8 Stream.

### What is the actual behavior?

The paginated methods will return all items at once, possibly throwing OOME when item count is high (like users). 

### Reproduction Steps?

Use any paginated method with a high amount of items like `new UserApi(client).listUsersWithPaginationInfo(...)`

### Java Version

Any	

### SDK Version

10.2.0

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks for posting!

If you want to opt out of pagination, you should use `new UserApi(client).listUsers(..)`.

**Comment by clementdenis** [comment]
Hi @arvindkrishnakumar-okta,

`new UserApi(client).listUsers(..)` will only get a single page of results, I still want to get all available results, but not in a single huge call that will return possible millions of results.

**Comment by ilgrosso** [comment]
I am exactly in the same position, thanks @clementdenis for reporting.
Incidentally, I note that this issue applies to all entities: users, groups, applications, ...

There are use cases where pagination shall be left for caller handling.

If you don't want to revert, at least make the `listXXXWithHttpInfo` methods from `private` to `public`.

**Comment by arvindkrishnakumar-okta** [comment]
@ilgrosso @clementdenis PR https://github.com/okta/okta-sdk-java/pull/825 created.

**Comment by arvindkrishnakumar-okta** [comment]
PR #825 merged.

**Comment by ilgrosso** [comment]
Thank you @arvindkrishnakumar-okta 
Is there any Maven repository from which I could download artifacts with version 10.2.1-SNAPSHOT, including the change from #825?

**Comment by arvindkrishnakumar-okta** [comment]
@ilgrosso I'll create a release and push the next version 8.2.1 to maven central most likely today.

**Comment by arvindkrishnakumar-okta** [comment]
@ilgrosso typo.. fixed.

**Comment by arvindkrishnakumar-okta** [comment]
Released 10.2.1, it should be available in Maven Central in few hours.

**Comment by clementdenis** [comment]
Hi @arvindkrishnakumar-okta,

Let me try to summarize the current situation:
- The now-public `listXXXWithHttpInfo(...)` method returns the low-level `ResponseEntity<List<XXX>>` object (which is great to obtain rate limit headers BTW), and does not have automatic pagination, providing full control to developers
- The `listXXX(...)` methods just delegates to `listXXXWithHttpInfo()` and unwraps the response, so it does not have auto pagination either
- The `listXXXWithPaginationInfo(...)` method returns a `PagedList<XXX>`which encapsulates pagination info and implements auto-pagination

When compared to 8.x:
- List methods had 2 variants: parameterless, and with search / sort options
- Both were returning all results with automatic pagination, BUT the returned object was lazy (iterating pages as needed) AND provided a pointer to the next page, which could be used to resume listing using the DataStore directly

I see a few problems with version 10.x:
- `listXXX(...)` method has the  "after" parameter, but with no way to get it from the return value `List<XXX>`
- `listXXXWithPaginationInfo(..)` returns a `PagedList<XXX>`, providing access to the "after" value to iterate manually, but has automatic pagination, effectively returning a null "after" in all cases
- Also, results are not fetched lazily when paginating automatically, which is a big regression from 8.x in terms of memory usage.

=> Why not switch and have `listXXX(...)` iterate pages automatically (and remove the useless "after" param), while providing full control over pagination with `listXXXWithPaginationInfo(...)`?
=> Also, couldn't the PagedList object iterate over pages lazily, like it was done in 8.x?
=> Finally, could you add a parameter-less `listXXX()` like there was in 8.x?

In the meantime, I'll be using listXXXWithHttpInfo(), which provide the low-level access I need to implement my own result streaming and resumability logic, but people looking for an easy migration path from 8.x might have some issues.
