### ISSUE TITLE
Manage Group membership missing or moved in 10.2.2

### ISSUE THREAD

**Issue by EarlM1** [okta/okta-sdk-java#844]
### Describe the bug?

The latest 10.2.2 okta -sdk-java is missing the method to add existing users to groups from the user api. 

The main github page shows the add a user to a group example but is not available in 10.2.2. I also dont see a remove user from group option. The only option I see that works is adding a new user to a group with UserBuilder. 

### What is expected to happen?

Expected to see the addtoGroup method as shown in the example below taking from the official okta sdk java page.

user.addToGroup("groupId");

[user.addToGroup("groupId");](https://github.com/okta/okta-sdk-java#add-a-user-to-a-group)

### What is the actual behavior?

The method is not recognized. 

### Reproduction Steps?

Try using this method "user.addToGroup("groupId");" with the 10.2.2 sdk. It previously worked in 8.2.3

### Java Version

17 LTS

### SDK Version

10.2.2 okta-sdk-api/okta-sdk-impl

### OS version

Windows 11

**Comment by arvindkrishnakumar-okta** [comment]
10.x is a major release that is drastically different from 8.x series. 

`User` model will no longer have `addToGroup` method. You should use `CreateUserRequest` model to populate the necessary groups and then use it with `UserApi` to create a user. This is exactly how the `UserBuilder` creates the user and you should follow along the same lines. 

Let me know if you have more questions.

**Comment by EarlM1** [comment]
Im trying to edit existing users group memberships. Im already able to add groups while creating users with UserBuilder

**Comment by arvindkrishnakumar-okta** [comment]
You should be able to use `groupApi.assignUserToGroup()` to achieve this.

**Comment by arvindkrishnakumar-okta** [comment]
@EarlM1 thanks for catching that, will update.
