### ISSUE TITLE
UserFactorApi.listFactors erases the profile data of the factor

### ISSUE THREAD

**Issue by patrick-m-m** [okta/okta-sdk-java#846]
### Describe the bug?

We updating a Java middleware app from SDK v4 to v10 and I discovered something I think is a bug. We have an endpoint to expose the SMS PhoneNumber of a factor for a given user, on v4 we could do this.

```
    User oktaUser oktaClient.getUser(uId);
    return oktaUser
        .listFactors()
        .stream()
        .filter(f -> f.getFactorType() == SMS)
        .map(f -> (SmsUserFactor) f)
        .map(PhoneNumber::new)
        .collect(Collectors.toList());
```

Upgrading to v10, the equivalent code is 

```
    return userFactorApi.listFactors(uid)
        .stream()
        .filter(f -> f.getFactorType() == SMS)
        .map(f -> (SmsUserFactor) f)
        .map(PhoneNumber::new)
        .collect(Collectors.toList());
```

However, this fails due to listFactors strictly returning `UserFactor` objects, which can no longer be cast to the `SmsUserFactor` type.

> java.lang.ClassCastException: class org.openapitools.client.model.UserFactor cannot be cast to class org.openapitools.client.model.SmsUserFactor

I can't find a way to get the profile object off of the base `UserFactor` class. It seems the only work around would be to separately query the individual factor with `userFactorApi.getFactor(uId, f.getId)`. I haven't tested, but it seems this would prevent reading the profile of other factor types (e.g., the Email off of a UserFactor that had `getFactorType() == EMAIL`).

The `profile.phoneNumber` section is definitely still returned by the Okta API for [List enrolled Factors GET /api/v1/users/${userId}/factors](https://developer.okta.com/docs/reference/api/factors/#list-enrolled-factors), so this seems like an extra step that the SDK could preempt by restoring the v4 behavior and returning the sub-typed object in the list operation.

Please let me know if I'm missing something on the API or return type. Also, I apologize if this should be a Feature Request, but it feels like a regression to me.

### What is expected to happen?

UserFactorApi.listFactors should make the factor profile data available on every factor that includes it.

### What is the actual behavior?

UserFactorApi.listFactors strictly returns `UserFactor` class objects instead of the properly sub-classed object.

### Reproduction Steps?

See code samples in issue description.

### Java Version

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### SDK Version

10.2.2

### OS version

Darwin RMN-pmacklin-mac 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by patrick-m-m** [comment]
Now I really hope I'm doing something wrong. I tried out the workaround I mentioned, to query the userFactorApi.getFactor method, and it is showing the same behavior.

```
    return getUserFactors(uid)
            .stream()
            .filter(f -> f.getFactorType() == SMS)
            .map(f -> (SmsUserFactor) userFactorApi.getFactor(uid, f.getId()))
            // collector/return
```

> java.lang.ClassCastException: class org.openapitools.client.model.UserFactor cannot be cast to class org.openapitools.client.model.SmsUserFactor (org.openapitools.client.model.UserFactor and org.openapitools.client.model.SmsUserFactor are in unnamed module of loader 'app')

Is there any way to get the profile fields out of the UserFactorApi methods? If this is something weird with my environment or classpath, is there any other information I can supply to track it down?

**Comment by arvindkrishnakumar-okta** [comment]
@patrick-m-m Thanks for posting!

This issue seems related to the refactoring we did recently in the open api spec v3 which the 10.x SDK generates code out of (with [openapi-generator](https://github.com/OpenAPITools/openapi-generator)). 

Like you pointed out, the most direct workaround (short term) would be to use the `userFactorApi.getFactor(uId, f.getId)` to get the subtypes of user factor that you are looking for.

**Comment by patrick-m-m** [comment]
Thanks for the reply @arvindkrishnakumar-okta , it is always reassuring to know I'm not going crazy.

As I noted in my second post, `userFactorApi.getFactor(uId, f.getId)` is experiencing the same erasure of the profile data.

I will give a go at invoking the endpoint directly for the full data and post some code when I have it working.

**Comment by patrick-m-m** [comment]
As expected, using `invokeApi` can properly fill the sub type. Here's where I landed:

```
                SmsUserFactor smsFactor = oktaApiClient
                    // Note: UserFactorApi#getFactor(uid, factorId) has the same problem of
                    // returning a plain UserFactor; use invokeAPI to get the profile data
                    .invokeAPI(
                        GET_FACTOR_ENDPOINT,
                        HttpMethod.GET,
                        Map.of("userId", uid, "factorId", f.getId()),
                        null,
                        null,
                        new HttpHeaders(),
                        new LinkedMultiValueMap<>(),
                        null,
                        Collections.singletonList(MediaType.APPLICATION_JSON),
                        MediaType.APPLICATION_JSON,
                        new String[] {"apiToken"},
                        new ParameterizedTypeReference<SmsUserFactor>() {})
                    .getBody())
```

Thanks again for acknowledging the bug. I look forward to using the `UserFactorApi` convenience methods in the future.

I found another issue that seems likely related to the same refactoring you mentioned, but it seemed worthy of a separate issue, so I opened https://github.com/okta/okta-sdk-java/issues/848

**Comment by arvindkrishnakumar-okta** [comment]
Glad you got the workaround working for now.

Yes, will plan to add the convenience method to `UserFactorApi` so you don't have to follow the above workaround for long term. 

And reg the other 'profile erasure' issue you reported, I noticed our spec is missing `profile` field in `UserFactor` model. This issue will be fixed with the spec update shortly.

**Comment by arvindkrishnakumar-okta** [comment]
The "profile erasure" issue is fixed.

**Comment by arvindkrishnakumar-okta** [comment]
Closing this issue as completed, feel free to reopen if you have any followups.
