### ISSUE TITLE
Support revokeSessions for changing password

### ISSUE THREAD

**Issue by Marek26** [okta/okta-sdk-java#847]
Currently changePassword doesn't support the revokeSessions property.

Requesting to support this within the SDK for the API call.

### New or Affected Resource(s)

UserApi.changePassword

https://developer.okta.com/okta-sdk-java/apidocs/org/openapitools/client/api/UserApi.html#changePassword(java.lang.Class,java.lang.String,org.openapitools.client.model.ChangePasswordRequest,java.lang.Boolean)

Class ChangePasswordRequest

https://developer.okta.com/okta-sdk-java/apidocs/org/openapitools/client/model/ChangePasswordRequest.html

### Provide a documentation link

https://developer.okta.com/docs/reference/api/users/#change-password

**Comment by Marek26** [comment]
@arvindkrishnakumar-okta Thanks for the quick update?

Do you have a rough timeline for that?

**Comment by arvindkrishnakumar-okta** [comment]
Planning to group in few other bug fixes into the next release, so it could be in the next week or so (tentatively). I'd get the fix merged to master shortly.
