### ISSUE TITLE
Add a way to get a PasswordPolicy without calling invokeApi manually.

### ISSUE THREAD

**Issue by literallyjustroy** [okta/okta-sdk-java#859]
### Describe the feature request?

The policy api returns a "settings" field if a Password Policy is the target of a GET. This value should be available within the SDK without having to resort to manually calling invokeAPI on the request.

### New or Affected Resource(s)

PolicyApi

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting @literallyjustroy!

Will get this addressed, we welcome PRs also, feel free to submit a PR if you could.

**Comment by literallyjustroy** [comment]
So the real problem is that the `PolicyApi getPolicy` method returns a `Policy`, which doesn't have a settings field. Since it doesn't even hold the arbitrary data, it can't be cast to a `PasswordPolicy`. It appears my only option is to call the api directly:
```java
PasswordPolicy passwordPolicy = oktaPolicyApi.getApiClient()
    .invokeAPI("/api/v1/policies/{policyId}",
        HttpMethod.GET,
        Collections.singletonMap("policyId", passwordPolicyId),
        null,
        null,
        new HttpHeaders(),
        new LinkedMultiValueMap<>(),
        null,
        Collections.singletonList(MediaType.APPLICATION_JSON),
        MediaType.APPLICATION_JSON,
        new String[]{"apiToken", "oauth2"},
        new ParameterizedTypeReference<PasswordPolicy>() {}
    ).getBody();
```

It seems like this usage is flawed, there is no way to get anything other then the general Policy info from the SDK (other than calling endpoints directly). It seems like the `getPolicy` method shouldn't return a `Policy` but an object that extends `Policy`. 

On a somewhat similar note, I am not seeing a way to create a new IDP_DISCOVERY Policy Rule. There is no `IdentityProviderPolicyRule` class. The `AccessPolicyRule` class seems to include most of the same fields so I can use that perhaps, but when I need to specify the `IdpPolicyRuleActionProvider` there is no way to set the ID, so I get stuck. I'm not sure if I'm missing something glaring or if this just cannot be done with the version 10 Okta SDK.

If you believe any of this is relatively easy to add I do not mind to spend a few days looking into it.

**Comment by arvindkrishnakumar-okta** [comment]
@literallyjustroy 11.0.0 just got released.

With this latest release, you should be able to use `PolicyApiHelper` to get sub-typed `Policy` objects.

```
PolicyApiHelper<Policy> policyApiHelper = new PolicyApiHelper<>(new PolicyApi(getClient()));
PasswordPolicy passwordPolicy = (PasswordPolicy) policyApiHelper.getPolicy(policy.getId(), null);

```

Similarly, `PolicyRule` sub-classes can be created using the `PolicyApiHelper` instance:

See https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/PoliciesIT.groovy#L141-L142

Let me know if that helps!

**Comment by literallyjustroy** [comment]
From a brief test that looks like exactly what we are looking for! Thanks for getting on this so quickly.
