### ISSUE TITLE
Set Application Visibility is not functioning

### ISSUE THREAD

**Issue by justkoch** [okta/okta-sdk-java#861]
### Describe the bug?

The SetVisibility() method for the Application object is not working as expected.

### What is expected to happen?

The setting "Do not display application icon in the Okta Mobile app" under
Application -> General -> App Settings -> Application Visibility
should change.

### What is the actual behavior?

No errors were reported but the setting is not changed.

### Reproduction Steps?

private void setMobileVisiblility(Application app) throws Exception {
    if (!(app.getVisibility().getHide().getIOS())) {
        try {
            app.setVisibility(client.instantiate(ApplicationVisibility.class)
                              .setHide(client.instantiate(ApplicationVisibilityHide.class)
                              .setIOS(true)));
            System.out.println("Set IOS Visibility for "+app.getLabel());
        } catch (Exception e) {
            System.out.println("ERROR: Could not set IOS Visibility for "+app.getLabel()+". "+e.getMessage());
        }
    }
}

### Java Version

amazon-corretto-18.0.2.9.1-windows-x64-jdk

### SDK Version

okta-sdk-api-8.2.2

### OS version

BuildNumber  Caption                          OSArchitecture  Version
19044        Microsoft Windows 10 Enterprise  64-bit          10.0.19044

**Comment by arvindkrishnakumar-okta** [comment]
Just to confirm if its an SDK issue or not, would it be possible for you to try the request in postman/rest client and see if it works?

Ref: https://developer.okta.com/docs/reference/api/apps/#application-object

**Comment by justkoch** [comment]
The update application API is working.Thank you JohnSent from my iPhoneOn Apr 26, 2023, at 10:53 AM, Arvind Krishnakumar ***@***.***> wrote:﻿
Just to confirm if its an SDK issue or not, would it be possible for you to try the request in postman/rest client and see if it works?
Ref: https://developer.okta.com/docs/reference/api/apps/#application-object
