### ISSUE TITLE
Auto pagination causes throttling & memory problems for large result sets

### ISSUE THREAD

**Issue by seanmflannery** [okta/okta-sdk-java#863]
### Describe the bug?

This is in between a bug and a feature request, but the pagination changes in 10.x cause issues for clients iterating over giant result sets. In a way, I suppose I'm asking to restore pre 10.x lazy loading of paged results or add flags to your new methods that allow for more pagination control.

Currently, you can only do one of the following:

listUsersWithPaginationInfo: gets ALL results back in one load (i.e. it will autocomplete to the final page). This can cause throttling dangers for us plus its a massive memory hog when running reports. For someone with a lot of users, this is non-ideal to dangerous when compared to the older implementation (pre 10) where the pagination was handled by the UserList response object and UserList lazy loaded its pages, so you never had more than 200 objects loaded at once.

or

listUsers and listUsersWithHttpInfo: both return only the first page with (it seems) no information on wider results.

This means that clients that don't want every page autofilled don't seem to have a SDK solution.

### What is expected to happen?

pagination should not automatically iterate to the final page before returning or, at a min, there should a solution where that behave can be disabled or modified so controlled pagination can happen.

### What is the actual behavior?

listUsersWithPaginationInfo will return all results in one gigantic response.

### Reproduction Steps?

invoke listUsersWithPaginationInfo on query that will return more than 200 results- you will get the total results of all pages when it returns.

### Java Version

All

### SDK Version

All

### OS version

All

**Comment by arvindkrishnakumar-okta** [comment]
@seanmflannery Thanks for posting!

We will address this in the next release.

**Comment by arvindkrishnakumar-okta** [comment]
Effective `12.x.x` (to be released within the next few days), the way to paginate has changed (`listUsersWithPaginationInfo(..)` is removed). 

Please refer https://github.com/okta/okta-sdk-java#pagination for more info.

Will be closing this ticket, please feel free to reopen if further followup on this is needed.
