### ISSUE TITLE
GetFactorType() returning IllegalArgumentException

### ISSUE THREAD

**Issue by kiranbud** [okta/okta-sdk-java#864]
### Describe the bug?

I am iterating through a list of factors that I received from **/api/v1/users/{userId}/factors** and when calling **factor.getFactorType()**, it is returning the following exception:
**java.lang.IllegalArgumentException: No enum constant com.okta.sdk.resource.user.factor.FactorType.signed_nonce**
I do not see signed_nonce as one of the FactorType.
Am I missing something here or if I am doing something wrong, can someone please help me to point in the right direction?

### What is expected to happen?

Should not receive any exception.

### What is the actual behavior?

Receiving IllegalArgumentException

### Reproduction Steps?

factorType = factor.getFactorType();

### Java Version

1.8

### SDK Version

okta-sdk-api-1.5.2

**Comment by clementdenis** [comment]
The fix for this specific issue is quite easy, I did this in my fork:
https://github.com/okta/okta-sdk-java/compare/master...clementdenis:okta-sdk-java:signed_nonce?expand=1

However, the schema for the UserFactor corresponding to factorType=signed_nonce is probably incorrect, so I did not submit a PR for this.

**Comment by kiranbud** [comment]
Yes, unfortunately we are using 1.5.2
We decided to upgrade but that is going to take sometime as we have to test so many cases.
We enrolled in SMS (Okta), Phone, Push (Okta) factors. But not sure how this `signed_nonce` factor is coming up by default. I also see `token:software:totp` coming up by default but this is present in the factor-type list.

**Comment by arvindkrishnakumar-okta** [comment]
@kiranbud I'll reach out to internal teams to see if this is missed in documentation.

**Comment by arvindkrishnakumar-okta** [comment]
PR https://github.com/okta/okta-sdk-java/pull/903 will fix this.

**Comment by arvindkrishnakumar-okta** [comment]
PR merged to master, next release will be cut soon.

**Comment by arvindkrishnakumar-okta** [comment]
12.0.0 is released with the fix.

**Comment by kiranbud** [comment]
Thank you @arvindkrishnakumar-okta
