### ISSUE TITLE
setCity method in the UserBuilder API sets the employeeNumber

### ISSUE THREAD

**Issue by EarlM1** [okta/okta-sdk-java#865]
### Describe the bug?

While calling setCity to create a user from UserBuilder interface. setCity sets the city on the okta city and employeeNumber variable. 

 UserApi userApi = new UserApi(client);
            User user = UserBuilder.instance()
                    .setEmail(email)
                    .setLogin(email)
                    .setFirstName(firstName)
                    .setLastName(lastName)
                    .setEmployeeNumber(employeeNumber)
                    .setCity(city)

### What is expected to happen?

setCity should only set the city attribute and setEmployeeNumber should set the employeeNumber.

### What is the actual behavior?

setCity from the UserBuilder instance sets the employeeNumber attribute to the city attribute.

### Reproduction Steps?

Call setCity and setEmployeeNumber while CREATING a new user and the employeenumber attribute will be populated with the city. 

### Java Version

Java 17 LTS

### SDK Version

10.3.0

### OS version

Windows 10\Windows Server 2022

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

PR https://github.com/okta/okta-sdk-java/pull/866 created to fix this.
