### ISSUE TITLE
Cannot get application subclass using ApplicationApi in 10.3

### ISSUE THREAD

**Issue by chairbender** [okta/okta-sdk-java#867]
### Describe the feature request?

We are upgrading from an older version of the SDK and ran into an issue blocking us from proceeding. 

Some methods on ApplicationApi have an overload which accepts a Class<T> parameter, for example createApplication. This allows retrieving the details of the application which are only present in the subclass (for example OpenIdConnectApplication). Example `createApplication(OpenIdConnectApplication.class, application, true, null)`

This capability is not consistently present on all methods of ApplicationApi which return Application-type objects or aggregations of them. 

The most glaring example, and the main issue we are facing, is that it is not even present on getApplication or listApplications.

Worse, all of the methods which just return Application are actually returning Application as the concrete type. So it is not just a matter of casting to OpenIdConnectApplication (which is something we were doing in the older version of the SDK). In other words, it seems like the SDK is actually discarding that extra information when it deserializes the raw response from the Okta API and returns it to us.

So, we are wondering how we are supposed to get fields which are only present on OpenIdConnectApplication using this SDK when getting or listing apps. It seems impossible currently, but we definitely need those details, hence this feature request.

It would be convenient if methods which returned Application used the correct subclass as the concrete type, so casting is possible, instead of discarding that information which is presumably present in the raw Okta API response. If not, at least provide a Class<?> overload for all methods which return Application or lists of applications. Note that approach would run into issues if you try to list apps and one of them is not of the expected type (and there is no filtering done based on app type), or get apps and it is not of the expected type

Note: I am not sure if this affects other resources that have subclasses but it may be worth checking.

### New or Affected Resource(s)

Application

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

I've created a PR https://github.com/okta/okta-sdk-java/pull/868 which will let users do what is mentioned in the issue.

**Comment by chairbender** [comment]
@arvindkrishnakumar-okta it looks like this only covers getApplication, not listApplications. That's not the only issue I see...With the approach in that PR, if we do not actually know the type of the app, we cannot get it as the correct subclass. We would have to call get once to get it as a generic App, then check its sign on mode, then call get again just to get it as the correct subclass based on sign on mode. So that's 2 round trips to Okta, even though all of the info was theoretically present in the first response from Okta.

Couldn't we instead have the same behavior as with the previous versions, where the concrete type is the correct subclass, so we can just call get (or list) once and use instanceof / casting? In my temporary workaround, I have extended ApplicationApi and I have it working like that.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for the feedback @chairbender !

Would be happy to review your PR if you could submit it?

**Comment by chairbender** [comment]
@arvindkrishnakumar-okta The way I have it working involves extending / modifying the generated code (ApplicationApi itself). I am not familiar enough with the code generation being used in this repo to submit a PR that would fix the code generation itself. If the SDK was not relying so heavily on code generation, it would otherwise be an easy fix.

**Comment by chairbender** [comment]
> Let me know when you have a PR that works with the codegen tooling we have.

I don't understand. Are you asking me to do the work to fix the SDK?

**Comment by arvindkrishnakumar-okta** [comment]
Ah, sorry for the confusion.. never mind, I'll open a PR that'd address these two issues (get & list) that works with the generated code.

**Comment by arvindkrishnakumar-okta** [comment]
PR merged to `master` branch.
