### ISSUE TITLE
PolicyAPI listPolicies is not returning the conditions and settings attributes

### ISSUE THREAD

**Issue by okra-okta** [okta/okta-sdk-java#873]
### Describe the bug?

Using the code below to retrieve MFA Enrollment policies, we can observe that the conditions and settings attributes are missing.
policy = policyApi.listPolicies("MFA_ENROLL", "ACTIVE", null);

Suspect that OpenAPI spec does not include these attributes.

### What is expected to happen?

If I make an API call to /api/v1/policies?type=MFA_ENROLL via curl/Postman, I can see the conditions and settings in the response.

Example:
```
{
    "id": "....",
    "status": "ACTIVE",
    "name": "SSR",
    "conditions": {
        "people": {
            "groups": {
                "include": [
                    "...."
                ]
            }
        }
    },
    "settings": {
        "type": "AUTHENTICATORS",
        "authenticators": [
            {
                "key": "okta_email",
                "enroll": {
                    "self": "REQUIRED"
                }
            }
        ]
    },
    ...
}
```

### What is the actual behavior?

Conditions and settings attributes are missing.

### Reproduction Steps?

Run the following code:
```
List policy = new ArrayList();
PolicyApi policyApi = new PolicyApi(client);
policy = policyApi.listPolicies("MFA_ENROLL", "ACTIVE", null);
```

### Java Version

17.0.1

### SDK Version

10.3.0

### OS version

Darwin Kernel Version 22.4.0

**Comment by nallamk2307** [comment]
Customer is looking for this, Any update on ETA?

**Comment by nallamk2307** [comment]
Thanks Arvind!

Thanks & Regards,
*Kiran Nallam*
Senior Services Consultant
945-208-4231
***@***.*** ***@***.***>* <https://www.okta.com/>
