### ISSUE TITLE
ApiClient does not get a new access token when it expired.

### ISSUE THREAD

**Issue by kluimeechai** [okta/okta-sdk-java#879]
### Describe the bug?

When using ApiClient with Oauth 2 authorization, The ApiClient does not get a new token after the access token expired (1 hour)

setAuthorizationMode(AuthorizationMode.PRIVATE_KEY)

### What is expected to happen?

The client should automatically refresh the token. 

### What is the actual behavior?

The client throws an exception
 org.springframework.web.client.ResourceAccessException: I/O error on GET request for "xxxxxxxx": No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]

### Reproduction Steps?

Instantiate an ApiClient object with  Private_KEY authorization mode and wait for 1 hour

ApiClient client = Clients.builder()
    .setOrgUrl("https://{yourOktaDomain}")  // e.g. https://dev-123456.okta.com
    .setAuthorizationMode(AuthorizationMode.PRIVATE_KEY)
    .setClientId("{clientId}")
    .setKid("{kid}") // optional
    .setScopes(new HashSet<>(Arrays.asList("okta.users.manage", "okta.apps.manage", "okta.groups.manage")))
    .setPrivateKey("/path/to/yourPrivateKey.pem")
    .build();

### Java Version

11

### SDK Version

10.3.0

### OS version

Alpine

**Comment by arvindkrishnakumar-okta** [comment]
Closing this as a suplicate of https://github.com/okta/okta-sdk-java/issues/891
