### ISSUE TITLE
Bring back Pagination in v11.0.0

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [okta/okta-sdk-java#884]
### Describe the feature request?

Bring back list*WithPaginationInfo in 11.0.0 SDK version.

### New or Affected Resource(s)

All APIs that return a collection of models.

**Comment by clementdenis** [comment]
Hi @arvindkrishnakumar-okta,

I've implemented a quick and easy solution to bring back pagination in v11:
https://github.com/clementdenis/okta-sdk-java/commit/6879127a557d7f5b1247183e52db1b47330458ba?w=1

The idea is to wrap List<> responses with pagination info (self / next link headers) in a PagedList instance (I just brought back the oe from v10, but made it extend ArrayList).

Paginating is done this way:
```java
UserApi userApi = new UserApi(client);
int limit = 2;
List<User> pagedUserList = null;
do {
    pagedUserList = userApi.listUsers(null, PagedList.getAfter(pagedUserList), limit, null, null, null, null);
    //pagedUserList can also be casted to a PagedList instance
    // loop through all of them
    for (User tmpUser : pagedUserList.getItems()) {
        log.info("User: {}", tmpUser.getProfile().getEmail());
    }
} while (PagedList.hasMoreResults(pagedUserList));
```

Feel free to use this code, or I can create a PR if you prefer.

PS: I took the liberty of reformating ApiClient.mustache properly, it's much easier to add changes that way.

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks, I'll create a PR for Pagination shortly.

**Comment by arvindkrishnakumar-okta** [comment]
PR merged to master, will cut a new major release in a week.
