### ISSUE TITLE
Exceptions should be unchecked in v11 and return a structured Error

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-java#889]
### Describe the bug?

Until v11 (in v10 / v8), ResourceException has always been an unchecked exception, and it was possible to get details about the Okta error.

But since v11, it was replaced by a more generic ApiException, that is now a checked exception, and only provides the response body as a String.

This makes migrating to the new version much harder than it should, as a lot of code now needs exception handling.
This is especially a problem when using lambda or method reference.

### What is expected to happen?

The new ApiException should be unchecked and allow to get a structured Error instance

To do so, you just need to add this to the generate goal of openapi-generator-maven-plugin
```xml
<configOptions>
    <useRuntimeException>true</useRuntimeException>
</configOptions>
```

For the structured Error, a helper would be enough (the Error class is already generated, but not used anywhere).

Both changes are implemented in this branch:
https://github.com/okta/okta-sdk-java/compare/master...clementdenis:okta-sdk-java:v11_runtime_exceptions?expand=1

### What is the actual behavior?

It is a checked exception and only provides the error response as a JSON string.

### Reproduction Steps?

N/A

### Java Version

Any

### SDK Version

v11

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks!

Please feel free to create a PR and I'll get that merged in.

**Comment by clementdenis** [comment]
Seems you already opened the PR :-)

**Comment by arvindkrishnakumar-okta** [comment]
https://github.com/okta/okta-sdk-java/pull/914 will fix this.
