### ISSUE TITLE
Auto-refresh authentication when working with private key

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-java#891]
### Describe the feature request?

When working with AuthorizationMode.PRIVATE_KEY, the authorization expires after 1 hour.

As the private key is available to the API client, it should be possible to auto-refresh the authorization before it expires.

### New or Affected Resource(s)

N/A

### Provide a documentation link

https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/

### Additional Information?

I implemented a solution for this here:
https://github.com/clementdenis/okta-sdk-java/commit/1622ea1a486837ae86b334623049a32176ca75af

It involves some changes to ApiClient.mustache, which is not ideal, but I did not find another nice way to hook auto-refresh into the generated ApiClient. The changes are still minimal. Let me know if you want to rework this or if I should create a PR directly.

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks, please feel free to create your own PR and send in a signed CLA.

**Comment by clementdenis** [comment]
I sent the signed CLA and opened https://github.com/okta/okta-sdk-java/pull/893
