### ISSUE TITLE
Cannot get "after" value from paginated response in v11.

### ISSUE THREAD

**Issue by JFreakDK** [okta/okta-sdk-java#897]
### Describe the bug?

With version 10.3.0 of the API I was using this code to get the "after" and "limit" value:
```
    public com.okta.sdk.resource.common.PagedList<User> getUsers(String sortBy, String sortOrder, String search, Integer limit, String after) {
        ResponseEntity<List<User>> listResponseEntity = apiClient.listUsersWithHttpInfo(null, after, limit, null, search, sortBy, sortOrder);
        return com.okta.sdk.resource.common.PagedList.constructPagedList(listResponseEntity);
    }
```
From the PagedList object I could get the "after" and "limit" value.
I don't see a way of getting this information in the new v11.0.2 API.

### What is expected to happen?

I would expect `org.openapitools.client.api.UserApi#listUsers(java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String)` to return the `List` of users and the "after" and "limit" property.

### What is the actual behavior?

Only the `List` of users are returned without the "after" and "limit" value needed to request the next page.

### Reproduction Steps?

The code in the description is hopefully sufficient.

### Java Version

openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode, sharing)

### SDK Version

11.0.2

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting! This will get addressed in the upcoming major release.

**Comment by arvindkrishnakumar-okta** [comment]
This issue will be fixed as part of https://github.com/okta/okta-sdk-java/issues/884. Therefore, closing this as a duplicate.
