### ISSUE TITLE
Make model objects implement `java.io.Serializable`.

### ISSUE THREAD

**Issue by JFreakDK** [okta/okta-sdk-java#901]
### Describe the feature request?

Could we make the model implement `java.io.Serializable`? That would make it easier to use Redis for caching since `org.springframework.data.redis.cache.RedisCache` relies on Javas serialization mechanism.

### New or Affected Resource(s)

All classes in the package `org.openapitools.client.model`

**Comment by arvindkrishnakumar-okta** [comment]
PR merged to master branch. Will cut next release by next week.
