### ISSUE TITLE
Default okta.properties missing in com.okta.sdk:okta-sdk-impl:12.0.2

### ISSUE THREAD

**Issue by JFreakDK** [okta/okta-sdk-java#929]
### Describe the bug?

The issue I originally faced was the the caching wasn't working after upgrading okta-sdk-impl from 11.0.2 to 12.0.2.

Debuging the code I found the property `okta.client.cache.enabled`. This was set to false at runtime.

Looking at the okta-sdk-impl-12.0.2.jar file's content this file is missing:
https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/resources/com/okta/sdk/config/okta.properties

### What is expected to happen?

I would expect the default property settings to be included.

A temporary workaround could be to include the default okta.properties file directly in my project.

If the default properties file is not included on purpose the property for enabling the cache should be set automatically if the client is configured with a cache manager or the property should be documented.

### What is the actual behavior?

The default properties file is missing in the jar file.

### Reproduction Steps?

One way to reproduce this is to build a client with a cache manager and verify that it is used:

```
Clients.builder()
                .setCacheManager(new MyCacheManager())
                .build();
```

### Java Version

openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment Temurin-20.0.2+9 (build 20.0.2+9)
OpenJDK 64-Bit Server VM Temurin-20.0.2+9 (build 20.0.2+9, mixed mode, sharing)

### SDK Version

20.0.2

**Comment by arvindkrishnakumar-okta** [comment]
@JFreakDK Thanks for catching this!

I've opened a PR that would fix this. Will get this merged soon.

**Comment by arvindkrishnakumar-okta** [comment]
Merged to main branch.
