### ISSUE TITLE
An attempt to remove profile attribute value does not succeed

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-sdk-java#937]
### Describe the bug?

If I try to remove a value from a user profile attribute, SDK does not work, the value stays the same after update and then get.

### What is expected to happen?

We should be able to wipe non-mandatory attributes

### What is the actual behavior?

If I try to assign an empty string or null to an attribute value and update, the value stays in the user profile

### Reproduction Steps?

```kotlin  
    val userId = "<some user guid>"
    val userOld = userApi.getUser(userId)

    // setting the value to something before wiping
    val userProfile = userOld.profile
    userProfile?.middleName = "A"
    userApi.updateUser(userId, UpdateUserRequest().also {
        it.profile = userProfile
    }, true)

    // check "A" is written
    var userNew = userApi.getUser(userId)
    var userProfileNew = userNew.profile

    // trying to remove middleName value
    userApi.updateUser(userId, UpdateUserRequest().also {
        it.profile = userProfileNew.also { profile ->
            profile?.middleName = ""
        }
    }, true)

    // checking the result
    userNew = userApi.getUser(userId)
    userProfileNew = userNew.profile
```

### Java Version

openjdk version "20" 2023-03-21
OpenJDK Runtime Environment Homebrew (build 20)
OpenJDK 64-Bit Server VM Homebrew (build 20, mixed mode, sharing)

### SDK Version

13.0.1

**Comment by arvindkrishnakumar-okta** [comment]
@phi1ipp Thanks for posting!

#938 should fix this.

**Comment by arvindkrishnakumar-okta** [comment]
Fix merged to main branch.
