### ISSUE TITLE
Missing "List groups assigned to application"

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-sdk-java#954]
### Describe the feature request?

This endpoint isn't accessible using Application API : https://developer.okta.com/docs/reference/api/apps/#list-groups-assigned-to-application

### New or Affected Resource(s)

Application API

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!This appears to be missing from our open api spec, will update the spec to address this.On Oct 18, 2023, at 3:35 AM, jeremieLyvoc ***@***.***> wrote:﻿

This message originated outside your organization.
  

Describe the feature request?
This endpoint isn't accessible using Application API : https://developer.okta.com/docs/reference/api/apps/#list-groups-assigned-to-application
New or Affected Resource(s)
Application API
Provide a documentation link
No response
Additional Information?
No response

**Comment by jeremieLyvoc** [comment]
Good for me, waiting for release
