### ISSUE TITLE
OAUTH_AUTHORIZATION_POLICY PolicyType missing in latest spec

### ISSUE THREAD

**Issue by B-Iglesia** [okta/okta-sdk-java#959]
### Describe the bug?

I originally created this [Okta-Dev forum post](https://devforum.okta.com/t/policy-creation-fails-after-upgrading-to-sdk-v13-0-2/25445) about not being able to make Policies using the Java SDK with the policy type `OAUTH_AUTHORIZATION_POLICY` 

A Okta team member got back to me and said "this looks like a bug", but didn't give any indication when this might be solved or when it might be implemented.

This is a link to the yaml spec where this policy type is not listed: https://github.com/okta/okta-sdk-java/blob/30b17aea065c2126eee2609c0e2f5babeaf61320/src/swagger/api.yaml#L28770C1-L28777C18

The API documentation also EXPLICITLY uses this type as the example: https://developer.okta.com/docs/reference/api/authorization-servers/#create-a-policy

### What is expected to happen?

I should be able to choose the ENUM `OAUTH_AUTHORIZATION_POLICY` when using the PolicyApi sdk client to create a policy in my Spring Boot java app

### What is the actual behavior?

`OAUTH_AUTHORIZATION_POLICY` doesn't exist

### Reproduction Steps?

Attempt to use the `OAUTH_AUTHORIZATION_POLICY` PolicyType
- It doesn't exist so it won't import

### Additional Information?

My team wants to be able to upgrade our spring version to Spring 3. We are currently using the Okta v10.3.0 SDK. 

Unless we can use this the v10.3.0 version with Spring 3, we will be blocked from upgrading.

### Java Version

openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Homebrew (build 17.0.6+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.6+0, mixed mode, sharing)

### SDK Version

v13.0.2

We are currently using v10.3.0 which doesn't have this issue

**Comment by arvindkrishnakumar-okta** [comment]
@B-Iglesia Thanks for posting!

Will get this addressed.

**Comment by B-Iglesia** [comment]
Hey @arvindkrishnakumar-okta , thanks for your response.

My main question is now surrounding `authorization server` policies (https://developer.okta.com/docs/reference/api/authorization-servers/#policy-operations), and the `policy` API that you sent me.

What is the distinct difference between them?

My follow up would be: what is SDK equivalent for creating a policy with an `OAUTH_AUTHROIZATION_POLICY` policy type in the latest SDK? As I mentioned, we would like to be on the latest SDK. 

`java
        AuthorizationServerPolicy authorizationServerPolicy = new AuthorizationServerPolicy();
        authorizationServerPolicy.setName(applicationName);
        authorizationServerPolicy.setDescription(POLICY_DESCRIPTION);
        authorizationServerPolicy.setType(**PolicyType.OAUTH_AUTHORIZATION_POLICY**);
        authorizationServerPolicy.setStatus(LifecycleStatus.ACTIVE);
        authorizationServerPolicy.setPriority(1);
        authorizationServerPolicy.setSystem(true);
`

**Comment by arvindkrishnakumar-okta** [comment]
`OAUTH_AUTHORIZATION_POLICY` is a string that should be used to set the AuthorizationServerPolicy type like your code snippet shows above. However, this is NOT part of the `PolicyType` that is publicly documented at https://developer.okta.com/docs/reference/api/policy/#policy-object. They both should not be correlated/confused with each other. Please use the String type `OAUTH_AUTHORIZATION_POLICY` when you work with `AuthorizationServerPolicy`. Hope this clarifies.

**Comment by B-Iglesia** [comment]
This clarifies a lot actually. Thank you. I was confused as in v10.3.0 `OAUTH_AUTHORIZATION_POLICY` type it is in a `PolicyType` enum.

Lastly, as a clarification, is this `OAUTH_AUTHORIZATION_POLICY` part of an enum somewhere or would it suffice to just have a local private variable. Asking as v10.3.0 of `.setType()` specifically requires a `PolicyType` Enum

**Comment by arvindkrishnakumar-okta** [comment]
@B-Iglesia I hear you and sorry for the confusion this has caused. 

When 10.3.0 was released, the backend API team possibly had this PolicyType documented in the public facing API doc and that was why it was included as part of the spec that went into 10.3.0

The latest release 13.0.2, took into the fact that the value `OAUTH_AUTHORIZATION_POLICY` was not publicly documented in API doc and hence was removed from the spec. 

I'll have to double check with internal team that owns this API if this value needs to be added to the `PolicyType` in the list of allowed policy types in public facing API docs.

**Comment by arvindkrishnakumar-okta** [comment]
@B-Iglesia I'll get this value added back to `PolicyType` enums in the spec and this change will get released as part of upcoming 14.0.0 release.

**Comment by B-Iglesia** [comment]
Hey @arvindkrishnakumar-okta , this is great news. I trust that this works, and will follow up when we attempt to implement this. Thank you very much for your help on this manner.

**Comment by jilds-wex** [comment]
This still not working since that in the version 14.0.0 we have the not the right PolicyType
![image](https://github.com/okta/okta-sdk-java/assets/107489287/21865560-a7f0-4fe0-9321-a469cc34317a)
