### ISSUE TITLE
With 14.0.0 the application id is always null upon create

### ISSUE THREAD

**Issue by ilgrosso** [okta/okta-sdk-java#961]
### Describe the bug?

We are generating the request below by invoking `com.okta.sdk.resource.api.ApplicationApi.createApplication(Application, Boolean, String)`

on a server mock generated from https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml

The following create request:

```
Address: https://localhost:8443/fit/okta/api/v1/apps?activate=true
Encoding: UTF-8
Http-Method: POST
Content-Type: application/json; charset=UTF-8
Headers: {Accept=[application/json], accept-encoding=[gzip, x-gzip, deflate], Authorization=[SSWS xxxxxxxxxxxxxx], connection=[keep-alive], Content-Length=[91], content-type=[application/json; charset=UTF-8], host=[localhost:8443], user-agent=[okta-sdk-java/14.0.0 spring/5.3.30 java/1.8.0_392 Linux/6.2.0-36-generic]}
Payload: {
  "signOnMode" : "Application",
  "label" : "stoka05a3e8cd-3551-4511-bfa7-ccb95175d4c9"
}
```

is producing this response:

```
Response-Code: 200
Content-Type: application/json
Headers: {Content-Type=[application/json], Date=[Mon, 13 Nov 2023 09:14:56 GMT]}
Payload: {"created":"2023-11-13T09:14:56.803Z","id":"aa6b5407-85b9-4731-b4b2-082d36d5bfa1","label":"stoka05a3e8cd-3551-4511-bfa7-ccb95175d4c9","lastUpdated":"2023-11-13T09:14:56.803Z","status":"ACTIVE"}
```

Starting with Okta SDK 14.0.0, however, the returned value from the call above is `null`, so it seems value binding is somewhat failing.
Everything works with Okta SDK 13.0.2

### What is expected to happen?

Call to `com.okta.sdk.resource.api.ApplicationApi.createApplication(Application, Boolean, String)` shall be returning an `Application` instance.

### What is the actual behavior?

The call as above is returning `null` despite of the returned HTTP headers and JSON body.

### Reproduction Steps?

Not sure if actually required, in case the reference project is https://github.com/Tirasa/ConnIdOktaBundle

### Java Version

openjdk version "1.8.0_392"
OpenJDK Runtime Environment (Zulu 8.74.0.17-CA-linux64) (build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (Zulu 8.74.0.17-CA-linux64) (build 25.392-b08, mixed mode)

### SDK Version

14.0.0

### OS version

PRETTY_NAME="KDE neon 5.27"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="5.27"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy
LOGO=start-here-kde-neon

**Comment by arvindkrishnakumar-okta** [comment]
@ilgrosso Thanks for posting!

I am not sure if I understand your issue, we do have integration tests inside the SDK for all Apps API operations (see https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/AppsIT.groovy#L43) and they all work/test fine. Given that, I'd like to understand a bit more on what "binding" you think is failing?

Please clarify more!

**Comment by ilgrosso** [comment]
@arvindkrishnakumar-okta never mind, I have figured out that the issue was that my code was not correctly managing the `signOnMode` property.
Thanks for your support.
