### ISSUE TITLE
ClassNotFoundException with current dependencies in Gradle build

### ISSUE THREAD

**Issue by matndev** [okta/okta-sdk-java#962]
### Describe the bug?

Unable to build project cause of insufficient dependencies when using :

```
compileOnly "com.okta.sdk:okta-sdk-api:14.0.0"
runtimeOnly "com.okta.sdk:okta-sdk-impl:14.0.0"
```

### What is expected to happen?

Be able to launch build without errors

### What is the actual behavior?

I get errors during the build.
Here the output : 

```
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.config.ConnectionConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 34 common frames omitted
```

### Reproduction Steps?

Install okta-sdk-java with tutorial : 
compileOnly "com.okta.sdk:okta-sdk-api:${okta.sdk.version}"
runtimeOnly "com.okta.sdk:okta-sdk-impl:${okta.sdk.version}"

### Java Version

java version "17.0.3.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

### SDK Version

13.0.2 and 14.0.0 both failed

### OS version

Windows 10 Enterprise

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

How are you building the project?

**Comment by matndev** [comment]
I built with this command in the terminal of root folder project and module folder where is the lib is used (multi module project) : `gradle build`
I use Intellij as well and with the button build the result is the same

**Comment by jfb-NRB** [comment]
The com.okta.sdk:okta-sdk-api:14.0.0 dependency uses org.apache.httpcomponents.client5:httpclient5 but the minimum version 5.2.1 is defined in the pom.xml of the com.okta.sdk:okta-sdk-root.
If in your project the httpclient5 dependency is in a smaller version, the ConnectionConfig class does not exist.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks @jfb-NRB!

Closing this issue now, please feel to reopen if further followup is needed.
