### ISSUE TITLE
Getting a new UserBuilder instance?

### ISSUE THREAD

**Issue by RvPr** [okta/okta-sdk-java#97]
The README shows the following code snippet for creating a new user:

return UserBuilder.INSTANCE
                .setEmail(email)
                .setLogin(userName)
               ......

However, the UserBuilder.INSTANCE is simply a single global instance:
UserBuilder INSTANCE = Classes.newInstance("com.okta.sdk.impl.resource.DefaultUserBuilder");

This can lead to all sorts of unexpected behavior. For example, if multiple threads want to create users in parallel, they would overwrite one another if they all use UserBuilder.INSTANCE at the same time. 

Another problem: suppose we first use UserBuilder.INSTANCE to create an account with name=Joe. Then, we want to create a new account for a different user, but this time, the name is not specified. If we simply call UserBuilder.INSTANCE and omit calling setName, the previous value of Joe will still stick around for the second account.

It would be much preferable if I could construct a new instance of UserBuilder for each time I want to create a user, but I don't see any way to create a new instance currently.

**Comment by bdemers** [comment]
@RvPr good point, this defiantly limits the usefulness. I meant to go back and clean this up after initially creating the UserBuilder interface.

For now you can just switch to a runtime dependency on the `okta-sdk-impl` and create a instance of a `DefaultUserBuilder` directly.

This will defiantly be fixed for the next release. Likely some type of simple factory. But again, this is just to remove the direct dependency on the impl package, so you can always just compile against it directly.

Thanks for the report!

**Comment by RvPr** [comment]
Sure, thanks for clarifying! I'm not under any immediate time pressure, but as a current stormpath user, I need to get my code-base migrated to okta prior to the shutdown on Aug 17. Can you clarify if the next release is scheduled for before that?

Also, do you think this SDK will be stable enough for production use prior to Aug 17? Or would you recommend not relying on this SDK for any production code before then?

**Comment by bdemers** [comment]
@RvPr, we will be pushing releases frequently. I don't have an ETA on the next one, but at this point likely every few bug fixes or so (and when new features are added)

Re the Stormpath SDK.  This SDK will not be a full replacement for that one.  We are targeting Okta's managment SDKs first (user, group, application, etc).  And not Okta's AuthN API.  And integrations with (Spring, Servlet, etc) will also come later).  I'm sure all of he Stormpath goodness will make it's way in to this SDK, just not before Aug 17th.  The recommended strategy is to use one of the Stormpath Integrations until then: https://github.com/stormpath/stormpath-sdk-java/tree/okta.  That said if your use cases are not covered, reach out to support@stormpath.com and we can help.

**Comment by bdemers** [comment]
Replaced `.INSTANCE`with `.instance()` this will likely change a little in the future, but this should work for now

**Comment by RvPr** [comment]
Thanks for the updates!
