### ISSUE TITLE
Create authorization server policy with type OAUTH_AUTHORIZATION_POLICY get error

### ISSUE THREAD

**Issue by jilds-wex** [okta/okta-sdk-java#975]
### Describe the bug?

When making the call they are generate the body this way:

`{
		"type": "AuthorizationServerPolicy",
		"status": "ACTIVE",
		"name": "Jonathan App12 AuthServer Policy",
		"description": "Jonathan App12 AuthServer Policy",
		"priority": 1,
		"system": false,
		"conditions": {
			"clients": {
				"include": [
					"ALL_CLIENTS"
				]
			}
		}
	}`

### What is expected to happen?

Is expected to generate this way, with the right type
`{
	"type": "OAUTH_AUTHORIZATION_POLICY",
	"status": "ACTIVE",
	"name": "Jonathan App12 AuthServer Policy",
	"description": "Jonathan App12 AuthServer Policy",
	"priority": 1,
	"conditions": {
		"clients": {
			"include": [
				"ALL_CLIENTS"
			]
		}
	}
}`

### What is the actual behavior?

return the following response because the wrong type:
`{
   "errorCode" : "E0000003",
   "errorSummary" : "The request body was not well-formed.",
   "errorLink" : "E0000003",
   "errorId" : "oae5ancVR41QveuOA4vfhgwkQ",
   "errorCauses" : [ ]
}`

### Reproduction Steps?

Try to create a new AuthorizationServerPolicy using the AuthorizationServerApi.createAuthorizationServerPolicy

### Additional Information?

The fix can be done in the Policy.java, where the converter for implementation AuthorizationServerPolicy can be done  for field type from **AuthorizationServerPolicy** to **OAUTH_AUTHORIZATION_POLICY**
![image](https://github.com/okta/okta-sdk-java/assets/107489287/53c0d19f-c9fd-4522-a193-3c3f1a10d032)

### Java Version

17

### SDK Version

14.0.0

### OS version

Windows 10

**Comment by arvindkrishnakumar-okta** [comment]
@jilds-wex Thanks for posting! Will look into this shortly.

**Comment by jilds-wex** [comment]
@arvindkrishnakumar-okta, I make some local tests and in the api.yaml file at the definition for Policy, the decriminator is missing this definition as well: OAUTH_AUTHORIZATION_POLICY: '#/components/schemas/AuthorizationServerPolicy'
