### ISSUE TITLE
Support for Factors enrolment

### ISSUE THREAD

**Issue by AlainODea** [okta/okta-sdk-java#98]
The FactorsApiClient is gone. How do I enrol factors with the new version?

**Comment by bdemers** [comment]
That API hasn't been added yet, it is on the list though

**Comment by chris-whittick-vgh** [comment]
Yeah the feature set of this new release is way behind the legacy version, honestly it being released in this state is frustrating and I am not convinced it adds value.

**Comment by bdemers** [comment]
@chris-whittick-vgh, it may not for your use cases.  You can stick with the 0.0.4 version until the functionality is added. Suggestions on which use cases are most important to you is always welcome.

**Comment by AlainODea** [comment]
@bdemers we are using factors enrolment and events API in production. We're also using a idps API with a client we added and haven't opened a pull request for yet.

We don't want to drift indefinitely apart from the new mainline here.

I can see the swagger codegen. Can you provide a hello world example of adding an API or point to a commit with a straight-forward example?

**Comment by bdemers** [comment]
@AlainODea We are generating the spec internally, technically the spec source is an NPM module, but I've just included the file to reduce the external dependency.

At Stormpath we were manually creating the api/impl models, the swagger portion is new, but it also means the all of our _supported_ api will be defined that way.

That said you could define a new model, and manage it with the `DataStore` interface for an example you could look at the generated `User` and `DefaultUser` classes.  We DO want to support this type of extension.

Also, please create an GH issue for each endpoint you are using, others can vote, and it will help us prioritize the order we implement them.

**Comment by AlainODea** [comment]
That works for me.

**Comment by bdemers** [comment]
We've been working on this `factor-hacking` branch. The history of the branch is a little rough,  I need to give it a once over, and check the coverage, but it should be in pretty good shape.  I'll update this issue when it gets released

**Comment by AlainODea** [comment]
Thank you, @bdemers :)

**Comment by bdemers** [comment]
Factors support is in the latest release: 0.8.1 !

**Comment by AlainODea** [comment]
Woo! Thanks :)
