### ISSUE TITLE
GroupsAPI - Custom group profile attributes missing

### ISSUE THREAD

**Issue by Marek26** [okta/okta-sdk-java#984]
### Describe the bug?

We added some custom attributes to the default Okta group profile.
With version 8.2.5, it was possible to access these attributes via the `additionalProperties` map from the `listGroups` result (before `Client`, now `GroupApi`).
With version 15.0.0, the `additionalProperties` map is now empty, so it's no longer possible to access the custom attributes via the SDK.
 
If you request the API manually, you will get the correct result:
 
```json
GET xxx/api/v1/groups?q=xxx
 
[
    {
        "id": "xxx",
        "created": "2022-11-16T05:38:16.000Z",
        "lastUpdated": "2022-11-16T05:38:16.000Z",
        "lastMembershipUpdated": "2024-01-02T13:04:06.000Z",
        "objectClass": [
            "okta:user_group"
        ],
        "type": "OKTA_GROUP",
        "profile": {
            "name": "xxx",
            "description": "xxx",
            "customGroupProfileAttribute": [
                "xxx"
            ]
        },
        "_links": {
            "logo": [
                {
                    "name": "medium",
                    "href": "xxx",
                    "type": "image/png"
                },
                {
                    "name": "large",
                    "href": "xxx",
                    "type": "image/png"
                }
            ],
            "users": {
                "href": "xxx"
            },
            "apps": {
                "href": "xxx"
            }
        }
    }
]
```

### What is expected to happen?

All custom attributes should be available via the `additionalProperties` map (such as for users where the custom attributes are available via the `additionalProperties` map).

### What is the actual behavior?

The `additionalProperties` map is always empty for results of `GroupApi.listGroups`.

### Reproduction Steps?

```
return groupApi.listGroups("groupName", null, null, null, null, null, null, null).stream().findFirst()
```

### Java Version

temurin-21.0.2

### SDK Version

<dependency>
    <groupId>com.okta.sdk</groupId>
    <artifactId>okta-sdk-api</artifactId>
    <version>15.0.0</version>
</dependency>
 
com.okta.sdk okta-sdk-impl 15.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@biochimia Thanks for posting!

I'll get the next SDK version released by end of this week.
