### ISSUE TITLE
OpenAPI spec missing some default role type

### ISSUE THREAD

**Issue by clementdenis** [okta/okta-sdk-java#993]
### Describe the bug?

IGA  admin roles ACCESS_CERTIFICATIONS_ADMIN and ACCESS_REQUESTS_ADMIN are missing from the RoleType in the [OpenAPI spec](https://github.com/okta/okta-sdk-java/blob/c8417693687be51711998f60138a073cd6d9aa26/src/swagger/api.yaml#L29847), resulting in null value when deserializing.

### What is expected to happen?

The enum values should exist and the com.okta.sdk.resource.model.Role instance should contain these values.

### What is the actual behavior?

A null value is set in the deserialized com.okta.sdk.resource.model.Role instance.

### Reproduction Steps?

Get the roles of user with any of the IGA role admins.

### Additional Information?

You should consider enabling [enumUnknownDefaultCase](https://openapi-generator.tech/docs/generators/java/) in the OpenAPI generator to have a default enum value (still not ideal, but better than a null value).

### Java Version

any

### SDK Version

15

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks for posting!

`ACCESS_CERTIFICATIONS_ADMIN` & `ACCESS_REQUESTS_ADMIN` role types are currently missing from spec because they are not GA (Generally Available) yet (from Okta core API's side). These are in EA (Early Access) stage presently, and will be added to spec when they are GA.

**Comment by clementdenis** [comment]
Thanks for the quick answer! However, would you still consider adding the [enumUnknownDefaultCase](https://openapi-generator.tech/docs/generators/java/) flag to the OpenAPI generation. It will avoid NPE in consumer code when unknown enums are encountered.

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Yes, noted and will do. Thanks!
