### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by duttkin** [okta/okta-sdk-java#998]
### Describe the bug?

We are experiencing an issue with the SDK around calls to the UserApi.  Everything will be fine for several days then we receive an error "Invalid Session" and once the error occurs the api calls continually fail until we restart the process.  There seems to be some state maintained by the client that does not attempt to get a new session once it is no longer valid.

com.okta.sdk.resource.client.ApiException: {"errorCode":"E0000005","errorSummary":"Invalid session","errorLink":"E0000005","errorId":"xxxxxxx","errorCauses":[]}
	at com.okta.sdk.resource.client.ApiClient.processResponse(ApiClient.java:957)
	at com.okta.sdk.resource.client.ApiClient.invokeAPI(ApiClient.java:1072)
	at com.okta.sdk.resource.api.UserApi.getUser(UserApi.java:1201)
	at com.okta.sdk.resource.api.UserApi.getUser(UserApi.java:1151)

### What is expected to happen?

A new session is established once the current session becomes invalid

### What is the actual behavior?

API keeps throwing invalid session error

### Reproduction Steps?

This just occurs randomly.  Sometimes it takes a couple days, sometimes it takes a couple weeks

### Java Version

JDK java 17

### SDK Version

13.0.2

### OS version

Kubernetes linux distroless gcr.io/distroless/java17-debian12

**Comment by arvindkrishnakumar-okta** [comment]
@duttkin Thanks for your post!

If not already, I recommend you take a look at https://support.okta.com/help/s/article/Reactivate-User-API-call-returning-error-E0000005?language=en_US to see if it helps.

**Comment by duttkin** [comment]
@arvindkrishnakumar-okta 

Thanks for providing the URL but unfortunately when this error starts occuring, it impacts all UserApi calls.  The most impactful one to use is actually the userApi.getUser call.  We actually don't use an API token for these calls.  We use a Private Key and scope "okta.users.manage".  The only way to get things working again is to kill the application and force a restart.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for the context. The SDK does NOT maintain session with the backend and does not cache the API key. From the looks of it, it does NOT appear to be an SDK issue. Can you please open a ticket with [Okta Help Center](https://support.okta.com/help/s/?language=en_US)?

**Comment by abhishek-workday** [comment]
Hi @duttkin , I am also facing the exact same issue. Is this resolved for you? If yes, what steps did you follow?

**Comment by iabhishekrajput** [comment]
Hi @duttkin , did you manage to debug and resolve this issue? If yes, could you please let us know the resolution?
